--------------------------------------------------------
--  File created - Tuesday-May-21-2024   
--------------------------------------------------------
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\BP_JOB_PURGE.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\CHECK_INSERT_OF_LV1LOC_ID.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\CHECK_INSERT_OF_LV2LOC_ID.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\CHECK_INSERT_OF_LV3LOC_ID.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\CHECK_INSERT_OF_LV4LOC_ID.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\CHECK_INSERT_OF_LV5LOC_ID.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\CHECK_INSERT_OF_LV6LOC_ID.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\CHECK_INSERT_OF_LV7LOC_ID.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\CHECK_INSERT_OF_LV8LOC_ID.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\CHECK_INSERT_OF_LV9LOC_ID.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\CHECK_LV2CTREE.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\CHECK_LV3CTREE.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\CHECK_LV4CTREE.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\CHECK_LV5CTREE.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\CHECK_LV6CTREE.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\CHECK_LV7CTREE.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\CHECK_LV8CTREE.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\CHECK_LV9CTREE.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\DM_UPDATE_STORE.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\F_GET_PERIOD_CYCLE.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\GET_CTREE_FROM_CMAST_ID.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\INS_CORP_STORE_LOG.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\INS_IMPORT_LOG.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\INSERT_CTREE.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\INSERT_DEL_LOC.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\MCX_PURGE_USER_PA.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\MODEL_POG_PERF.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\MRI_PREP_FOR_PURGE10.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_ACTIVATE_LAYERS.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_ACTIVATE_VERSION.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_ADJUST_KPI_RECORDS.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_ADJUST_KPI_WRAPPER.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_AGG_BATCH.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_AGG_CHK_COL_RULE.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_AGG_COL_RULE.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_AGG_COUNT.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_AGG_INIT.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_AGG_LOAD.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_AGG_LOCATION.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_AGG_LOGGER.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_AGG_MERCH.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_AGG_POST.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_AGG_RECOVER.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_AGG_RECREATE_WORKTBL.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_AGG_REINDEX.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_AGG_SCHED.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_AGG_STAGE.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_AGG_STAGE_CHILDREN.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_AGG_TIME.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_AGGR_HIER.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_BP_GET_CHILD_JOBS.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_BP_RESET_BATCH_FLG.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_CALC_DAYS_OFFSET.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_CALC_USED_SPACE.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_CHANGE_MERCH_PARENT.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_CHECK_TABLE_PREFIX.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_CLUSTER_STORE.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_CLUSTER_STORE_L6.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_COMPLETE_MERCH_TREE.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_COMPLETE_MERCH_TREE_APP.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_COMPLETE_MERCH_TREE_LOAD.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_COMPLETE_MERCH_TREE2.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_COMPOSE_QUERY.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_CONSOLID_PERF.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_CONVERT_STDHIER2DIMSET.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_COPY_CLSTR_ST.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_COPY_FAV_ASSIGN.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_COPY_PLANVERSION.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_COPY_PLANWORKSHT.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_COPY_PW_TMPL.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_COPY_TMPL_ONE.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_CREATE_BATCH_JOB.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_CREATE_BI_BRIDGE_TBL.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_CREATE_GPF_TMPTBLS.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_CUSTOM_AGGR.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_DB_GET_CONCURRENCY_SLOT.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_DB_MAKE_TABLE_PARTITION.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_DB_MAKE_TABLESPACE.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_DEL_CUBE_DIMENSION.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_DEL_PLANTABLE.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_DELETE_VERSION.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_DM_SET_CL_STATUS.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_DO_MODEL_RES.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_DROP_ALL_TMP.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_DROP_CL_HIST_DV.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_DROP_PW_CL_HIST.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_DROP_T_CL_TBL.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_DROP_T_TBL.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_DROP_T_TMPL_TBL.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_DROP_TABLE.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_EXECUTE_DDL_SQL.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_EXECUTE_DDL_WAIT.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_FES_ADD_MPLAN_NEW.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_FES_ADD_NEW_SKU.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_FES_COPY_SHOP_WKSHT.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_FES_COPY_SHOP_WRAPPER.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_FES_DUP_NEW_SKU.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_FES_MDOEL_STYLE_REPORT.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_FES_UPDATE_RESKEY.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_FILL_4KEY_ML.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_FILTER_TD_BU.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_FLAG_CURRENT_POG.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_GEN_LOC_TIME_2D.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_GEN_LV10POS.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_GEN_LV1MROLL.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_GEN_LV2MROLL.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_GEN_LV3MROLL.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_GEN_LV4MROLL.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_GEN_LV5MROLL.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_GEN_LV6MROLL.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_GEN_LV7MROLL.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_GEN_MERCH_1D.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_GEN_ROLL.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_GEN_TIME_INCLAUSE.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_GET_CL_HIST.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_GET_CL_HIST_BAT.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_GET_DEF_SECTIONS.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_GET_PLANOGRAMS.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_GET_QUERY_HINT.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_GET_VER_PARENTS.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_GETVERLOCLINKID.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_HIGHLIGHT_LOCATIONS.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_INSERT_BI_TRANSACTION.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_INSERT_CL_STATUS.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_LABEL_FIXTURE.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_LOG.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_LOG_MODEL_RES_STATUS.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_LOG_XREF_MODEL_RES_STATUS.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_LV1_FINC_ALL.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_LV10FINC_PERIOD.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_LV2_FINC_ALL.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_LV3_FINC_ALL.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_LV6_1FINC_PERIOD.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_LV9_7FINC_PERIOD.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_MCX_SUBMIT_CUMS_BATCH.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_MCX_ZERO_SHRINK.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_MFINC_MODELSKU_VIEW.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_MINVENTORY_MODELSKU_VIEW.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_NEW_VERSION.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_NO_MVMT_FLAG.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_POG_ANALYZER.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_POG_APPROVAL.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_POP_LOC_QUEUE.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_POP_LVXREF_MODEL_RES.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_POP_MERCH_QUEUE.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_POP_T_CUBE_TBL.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_POPULATE_1D.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_REBUILD_TEMP_POS.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_RECALC_LV5LOC.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_RECALC_LV7LOC.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_RECALC_SPACE.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_REPLACE_MODEL_RES.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_SAVE_AS_PLANWORKSHT.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_SET_BI_JOB_STATUS.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_SET_BI_TRANSACTION.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_SET_CL_STATUS.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_SET_HIER_LEV_SEQ.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_SETPROTOTYPE.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_SPECIAL_PLANWORKSHT.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_TRUNC_TABLES.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_TRUNCATE_TABLE.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_UPD_CTREE_ID.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_UPD_DYNAMIC_DATES.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_UPD_LVL321_SPACE.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_UPD_POG.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_UPD_POG_STATUS.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_UPD_POS.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_UPDATE_CLOSED_STORE.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_UPDATE_RES_STATUS_ATTRIB.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_UPDATE_RESKEY_ATTRIB.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_UPDATE_RESOLVED_MEMBER.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_VALIDATE_MODEL_RES.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_VERSION_LAYERS.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_WL_CLEANUP_JOB.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_WL_COPY_OBJECT.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_WL_COPY_SUBTREE.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_WL_COPY_TEMPLATE.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_WL_DELETE_OBJECT.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_WL_DELETE_PERMANENT_ROWS.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_WL_DELETE_TEMPLATE.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_WL_DELETE_WORKING_ROWS.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_WL_FIX_KPIDV.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_WL_GENERATE_OBJECT_NO.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_WL_NEXT_OBJECT_NO.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_WL_POST_TEMPLATE.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_WL_PROMOTE_TASK.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_WL_PRUNE_OBJECT.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_WL_STAGE_TEMPLATE.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_WL_TRANSFER_CASE.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_WL_TRUNCATE_CUBE.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_WL_VALIDATE_OBJECT.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_WL_VALIDATE_PERM_KPI_PA.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_WL_VALIDATE_PERM_SUBTREE.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_WL_VALIDATE_WORK_KPI_PA.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\P_WL_VALIDATE_WORK_SUBTREE.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\PEGFIXING.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\POG_ASSIGN_PERF.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\REVERSE_PEGFIXING.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\UPDATE_LV1_LOC.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\UPDATE_LV10MAST.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\UPDATE_LV10MERCH.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\UPDATE_LV2_LOC.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\UPDATE_LV3_LOC.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\UPDATE_LV4_LOC.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\UPDATE_LV5_LOC.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\UPDATE_LV6_LOC.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\UPDATE_LV7_LOC.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\UPDATE_LV8_LOC.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\UPDATE_LV9_LOC.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\UPDATE_LVXCMAST.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\UPDATE_PARENTS.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\AdditionalSQLFiles\UPDATE_TOT_ITEMS.sql
