--------------------------------------------------------
--  File created - Tuesday-May-21-2024   
--------------------------------------------------------
@C:\Users\sarik\Documents\SAS\SQLFiles\COMPILE_INVALID.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\MAKE_TABLE_P8_ONWARD.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\MRI_PREP_FOR_PURGE10.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\P_WKLY_CART_CALC.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\P_WKLY_IM_GROUP.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\P_WKLY_IM_GROUP_TYPES.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\P_WKLY_IN_OUT_TRFS.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\P_WKLY_INS_CALC.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\P_WKLY_INVENTORY_EXTRACT.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\P_WKLY_INVENTORY_EXTRACT_ARC.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\P_WKLY_MARK_DOWN.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\P_WKLY_MERGE_ADJ.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\P_WKLY_MERGE_BOP_COST.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\P_WKLY_MERGE_BOP_RETAIL.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\P_WKLY_MERGE_CLAIMS.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\P_WKLY_MERGE_END.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\P_WKLY_MERGE_EOP_COST.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\P_WKLY_MERGE_EOP_RETAIL.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\P_WKLY_MERGE_MD.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\P_WKLY_MERGE_PREP.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\P_WKLY_MERGE_RCPTS.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\P_WKLY_MERGE_SALES.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\P_WKLY_MERGE_WKLY_QTY.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\P_WKLY_MERGE_XFER.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\P_WKLY_PROD_MASTER.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\P_WKLY_SAS_BOP_EOP.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\P_WKLY_SAS_BOP_EOP_SHRINK.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\P_WKLY_SAS_BOP_EOP_SP.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\P_WKLY_SAS_INV.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\P_WKLY_SAS_INV_SP.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\P_WKLY_SUM_CART.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\P_WKLY_SUM_TOTAL.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\P_WKLY_TIME_PERIOD.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\P_WKLY_TIME_PERIOD_SP.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\P_WKLY_TYPES.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\P_WKLY_UPD_RETAIL_FINAL.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\PROC_SAS_RECLASS_JOB.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\PURGE_RECYCLEBIN.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\RDI_SEND_MAIL.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\SAS_MARKER_UTIL.sql
@C:\Users\sarik\Documents\SAS\SQLFiles\THIS_MERCH_DATE.sql
