#!/usr/local/mccs/perl/bin/perl
#---------------------------------------------------------------------
# Program    : storable_styles
# Author     : Hanny Januarius
# Created    : Mon Oct  5 12:50:40 EDT 2015
# Description: Create storable file for style_id from styles table
#              RMS database
#---------------------------------------------------------------------
use strict;
use IBIS::DBI;
use IBIS::Log::File;
use File::Basename;
use File::Path;
use Readonly;
use MCCS::Config;
use Data::Dumper;
use Fcntl qw(:flock);
use MCCS::WMS::Sendmail;
use Getopt::Std;
use DateTime;
use MCCS::Storable::Table;

# Flush output
$| = 1;

#- One process at a time ---------------------------------------------
my $lock_file = "/usr/local/mccs/tmp/" . basename($0) . ".lck";
open SELF, "> $lock_file" or die "Could not create lock file $lock_file";
flock SELF, LOCK_EX | LOCK_NB or die "Another $0 process already running";

#- Get option switches -----------------------------------------------
our %g_opt = (
    d => 0
);
getopts('d', \%g_opt);
my $DEBUG = $g_opt{d};

#- Configuration files -----------------------------------------------
my $g_cfg = new MCCS::Config;

my $g_emails = $g_cfg->storable->{emails};  #TODO

print Dumper $g_emails if $DEBUG;

#- Global variables --------------------------------------------------
my $g_verbose = 0;
Readonly my $g_logfile => '/usr/local/mccs/log/PriceChanges/' . basename(__FILE__) . '.log';
my $g_long_date = `date +"%D %r"`;
chomp($g_long_date);
my $g_log = IBIS::Log::File->new( { file => $g_logfile, append => 1, level => 4 } );
my $g_host = `hostname`; 
chomp($g_host);
my $go_mail = MCCS::WMS::Sendmail->new();

#---------------------------------------------------------------------
# SUBS
#---------------------------------------------------------------------
sub send_mail {
    my $msg_sub  = shift;
    my $msg_bod1 = shift;
    my $msg_bod2 = shift || '';
    my @body = ($msg_bod1, $msg_bod2);

    return if $g_verbose;    # Dont want to send email if on verbose mode

    $go_mail->logObj($g_log);
    $go_mail->subject($msg_sub);
    $go_mail->sendTo($g_emails);
    $go_mail->msg(@body);
    $go_mail->hostName($g_host);
    $go_mail->send_mail();
}

#---------------------------------------------------------------------
sub fatal_error {
    my $msg = shift;
    send_mail( "ERROR on " . __FILE__ . ' ' . $g_long_date, $msg );
    $g_log->error($msg);
    die $msg;
}

#---------------------------------------------------------------------
#---------------------------------------------------------------------

#---------------------------------------------------------------------
# Pseudo Main which is called from MAIN
#---------------------------------------------------------------------
sub my_main {
    my $sub = __FILE__ . " the_main";
    if ($g_verbose) {

        # Record Everything
        $g_log->level(5);
    }
    else {

        # Record Everything, except debug logs
        $g_log->level(4);
    }

    $g_log->info("-- Start ----------------------------------------");
    my $file = 'storable_style_for_spot_price_change';
my $sqlx = <<ENDSQL1;
select
d.ADD_INFO_KEY_1_DATA as "STYLE_ID"
from add_info_property p, add_info_data d, styles s
where p.business_unit_id = 30
and p.business_unit_id = d.business_unit_id
and d.add_info_key_1_data = s.style_id
and p.add_info_id = d.add_info_id
and d.add_info_data is not null
and p.add_info_id  in ('1')
ENDSQL1

#MINUS
#select
#d.ADD_INFO_KEY_1_DATA as "STYLE_ID"
#from add_info_property p, add_info_data d, styles s
#where p.business_unit_id = 30
#and p.business_unit_id = d.business_unit_id
#and d.add_info_key_1_data = s.style_id
#and p.add_info_id = d.add_info_id
#and d.add_info_data is not null
#and p.add_info_id  in ('1')
    my $sql = <<ENDSQL;
select style_id from styles where business_unit_id = 30 and for_resale_ind <> 'N'
ENDSQL
    my $dbname = 'rms_p';
    my $styles = MCCS::Storable::Table->new( dbname=>$dbname, sql=>$sql);

    $g_log->summary("$dbname - file: $file");
    $g_log->summary("$sql");

    $styles->store_file($file);

    $g_log->info("-- End ------------------------------------------");
}

#---------------------------------------------------------------------
# MAIN PROGRAM - Do not modify main below.
# Use the main above aka my_main
#---------------------------------------------------------------------

# Want to catch warning
$SIG{__WARN__} = sub { $g_log->warn("@_") };

# Execute the main
eval { my_main() };
if ($@) {
    send_mail( "ERROR on " . __FILE__ . ' ' . $g_long_date,
        "Untrapped Error:\n\n", " $@" );
    $g_log->info($@);
}

#---------------------------------------------------------------------
# End program
#---------------------------------------------------------------------
