--------------------------------------------------------
--  DDL for Procedure P_GEN_ROLL
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "MAXDATA"."P_GEN_ROLL" (current_period_id IN integer, current_cycle_id IN integer,
				period_id_to_roll_from IN  integer, cycle_id_to_roll_from IN integer)
AS

x integer;
t_seq_id number(10,0);
t_max_roll_id number(10, 0);
t_min_roll_id number(10, 0);
roll_count number(10, 0);

begin
select periods_to_roll into x from maxapp.mmax_config ;

/* Populate lv10roll from lv10finc */


	insert into maxdata.temp_lv10roll
	(last_update,
	 changed_by_batch,
	 version_id,
	 cycle,
	 live_lv7loc_id,
	 lv10loc_id,
	 used_cubic_meters,
	 used_dsp_sqmeters,
	 used_flr_sqmeters,
	 used_linear_meters,
	 loss_sales,
	 loss_gp,
	 proj_sales,
	 proj_gp,
	 gm_roii,
	 days_in_period,
	 days_supply,
	 dpp_dollar,
	 dpp_item,
	 cost_of_invent,
	 dir_cost_of_sales,
	 indir_cost_of_sale,
	 posit_sales,
	 posit_mvmt,
	 posit_norm_mvmt,
	 include_in_avg,
	 total_caps,
	 total_units,
	 total_items,
	 vat,
	 supp_total_sales,
	 supp_cost_of_sales,
	 supp_posit_mvmt,
	 supplier_norm_mvmt,
	 num_user1,
	 num_user2,
	 num_user3,
	 num_user4,
	 num_user5,
	 num_user6,
	 oh_qty,
	 oh_cost,
	 oh_retail,
	 pog_retail,
	 concat_id,
/* Added columns on 06/22/1999  Suresh */
	 ALLOC_CUBIC_METERS,
	 ALLOC_DSP_SQMETERS,
	 ALLOC_FLR_SQMETERS,
	 ALLOC_LINEAR_METER,
	 POSIT_MVMT_REG ,
	 POSIT_SALES_REG,
	 POSIT_COST_REG ,
	 POSIT_MVMT_PROMO ,
	 POSIT_SALES_PROMO,
	 POSIT_COST_PROMO ,
	 POSIT_MVMT_CLRNC ,
	 POSIT_SALES_CLRNC,
	 POSIT_COST_CLRNC ,
	 POSIT_MVMT_RETN,
	 POSIT_SALES_RETN ,
	 POSIT_COST_RETN,
	 Inventory_items,
	 inventory_retail,
	 inventory_cost,
	 received_items,
	 received_retail,
	 received_cost,
	 total_items_retail,
	 total_items_cost,
	 min_pres_items,
	 min_pres_retail,
	 min_pres_cost)
	select sysdate,
	 1,
	 1,
	 max(lv10finc.cycle),
	 lv10finc.live_lv7loc_id,
	 lv10finc.lv10loc_id,
	 sum(lv10finc.used_cubic_meters),
	 sum(lv10finc.used_dsp_sqmeters),
	 sum(lv10finc.used_flr_sqmeters),
	 sum(lv10finc.used_linear_meters),
	 sum(lv10finc.loss_sales),
	 sum(lv10finc.loss_gp),
	 sum(lv10finc.proj_sales),
	 sum(lv10finc.proj_gp),
	 1,
	 sum(lv10finc.days_in_period),
	 1,
	 sum(lv10finc.dpp_dollar),
	 sum(lv10finc.dpp_item),
	 sum(lv10finc.item_direct_cost*lv10finc.total_items),
	 sum(lv10finc.item_direct_cost*lv10finc.posit_mvmt),
	 sum(lv10finc.item_indirect_cost*lv10finc.posit_mvmt),
	 sum(lv10finc.posit_sales),
	 sum(lv10finc.posit_mvmt),
	 sum(lv10finc.posit_norm_mvmt),
	 sum(lv10finc.include_in_avg),
	 sum(lv10finc.total_caps),
	 sum(lv10finc.total_units),
	 sum(lv10finc.total_items),
	 sum(lv10finc.vat),
	 sum(lv10finc.supplier_avg_price*lv10finc.supp_posit_mvmt),
	 sum(lv10finc.supplier_item_cost*lv10finc.supp_posit_mvmt),
	 sum(lv10finc.supp_posit_mvmt),
	 sum(lv10finc.supplier_norm_mvmt),
	 sum(lv10finc.num_user1),
	 sum(lv10finc.num_user2),
	 sum(lv10finc.num_user3),
	 sum(lv10finc.num_user4),
	 avg(lv10finc.num_user5),
	 avg(lv10finc.num_user6),
	 sum(lv10finc.oh_qty),
	 sum(lv10finc.oh_cost),
	 sum(lv10finc.oh_qty * lv10finc.item_average_price),
	 sum(lv10finc.total_items * lv10finc.item_average_price),
	 lv10finc.lv10loc_id||'-'||lv10finc.live_lv7loc_id,
	 SUM(lv10finc.ALLOC_CUBIC_METERS),
	 SUM(lv10finc.ALLOC_DSP_SQMETERS),
	 Sum(lv10finc.ALLOC_FLR_SQMETERS) ,
	 Sum(lv10finc.ALLOC_LINEAR_METER),
	 sum(lv10finc.posit_mvmt_reg)  ,
	 sum(lv10finc.posit_sales_reg),
	 sum(lv10finc.item_direct_cost * lv10finc.posit_mvmt_reg ),
	 sum(lv10finc.posit_mvmt_promo),
	 sum(lv10finc.posit_sales_promo),
	 sum(lv10finc.item_direct_cost * lv10finc.posit_mvmt_promo ),
	 sum(lv10finc.posit_mvmt_clrnc ),
	 sum(lv10finc.posit_sales_clrnc ),
	 sum(lv10finc.item_direct_cost * lv10finc.posit_mvmt_clrnc ),
	 sum(lv10finc.posit_mvmt_retn ),
	 sum(lv10finc.posit_sales_retn ),
	 sum(lv10finc.item_direct_cost *  lv10finc.posit_mvmt_retn ),
	 sum((lv10finc.begin_inv_items + lv10finc.end_inv_items) / 2),
	 sum(((lv10finc.begin_inv_items + lv10finc.end_inv_items) / 2) * lv10finc.item_average_price),
	 sum(((lv10finc.begin_inv_items + lv10finc.end_inv_items) / 2) * lv10finc.item_direct_cost),
	 Sum(lv10finc.received_items),
	 sum(lv10finc.received_items * lv10finc.item_average_price),
	 sum(lv10finc.received_items * lv10finc.item_direct_cost),
	 sum(lv10finc.total_items * lv10finc.item_average_price),
	 sum(lv10finc.total_items * lv10finc.item_direct_cost),
	 sum(lv10finc.min_pres_items),
	 sum(lv10finc.min_pres_items * lv10finc.item_average_price),
	 sum(lv10finc.min_pres_items * item_direct_cost)
	from maxdata.lv10finc
	where(lv10finc.cycle||lpad(lv10finc.period,7,0))
		<=(current_cycle_id||lpad(current_period_id,7,0))
		and(lv10finc.cycle||lpad(lv10finc.period,7,0))
		>=(cycle_id_to_roll_from||lpad(period_id_to_roll_from,7,0))
	group by lv10finc.live_lv7loc_id,lv10finc.lv10loc_id;

	commit;

-- As the sequence number can not be insert in temp table it is always higher than necessary and may out of synch with
-- Sequence entry for the original table. So if you take id - min(id) + 1 from temp table it gives a counter from 1
-- for the records so id - min(id) + 1 + seq_num from sequence table for the original table always gets right id next to seq_num.

	Select seq_num into t_seq_id from maxapp.sequence where level_type = 10 and entity_type = 6;

	Select max(lv10roll_id) into t_max_roll_id from maxdata.temp_lv10roll;

	Select min(lv10roll_id) into t_min_roll_id from maxdata.temp_lv10roll;

	roll_count := t_max_roll_id - t_min_roll_id;

	Insert into maxdata.lv10roll
	(lv10roll_id,
	 last_update,
	 changed_by_batch,
	 version_id,
	 cycle,
	 live_lv7loc_id,
	 lv10loc_id,
	 used_cubic_meters,
	 used_dsp_sqmeters,
	 used_flr_sqmeters,
	 used_linear_meters,
	 loss_sales,
	 loss_gp,
	 proj_sales,
	 proj_gp,
	 gm_roii,
	 days_in_period,
	 days_supply,
	 dpp_dollar,
	 dpp_item,
	 cost_of_invent,
	 dir_cost_of_sales,
	 indir_cost_of_sale,
	 posit_sales,
	 posit_mvmt,
	 posit_norm_mvmt,
	 include_in_avg,
	 total_caps,
	 total_units,
	 total_items,
	 vat,
	 supp_total_sales,
	 supp_cost_of_sales,
	 supp_posit_mvmt,
	 supplier_norm_mvmt,
	 num_user1,
	 num_user2,
	 num_user3,
	 num_user4,
	 num_user5,
	 num_user6,
	 oh_qty,
	 oh_cost,
	 oh_retail,
	 pog_retail,
	 concat_id,
/* Added columns on 06/22/1999  Suresh */
	 ALLOC_CUBIC_METERS,
	 ALLOC_DSP_SQMETERS,
	 ALLOC_FLR_SQMETERS,
	 ALLOC_LINEAR_METER,
	 POSIT_MVMT_REG ,
	 POSIT_SALES_REG,
	 POSIT_COST_REG ,
	 POSIT_MVMT_PROMO ,
	 POSIT_SALES_PROMO,
	 POSIT_COST_PROMO ,
	 POSIT_MVMT_CLRNC ,
	 POSIT_SALES_CLRNC,
	 POSIT_COST_CLRNC ,
	 POSIT_MVMT_RETN,
	 POSIT_SALES_RETN ,
	 POSIT_COST_RETN,
	 Inventory_items,
	 inventory_retail,
	 inventory_cost,
	 received_items,
	 received_retail,
	 received_cost,
	 total_items_retail,
	 total_items_cost,
	 min_pres_items,
	 min_pres_retail,
	 min_pres_cost)
	Select lv10roll_id + t_seq_id + 1 - t_min_roll_id,
	 last_update,
	 changed_by_batch,
	 version_id,
	 cycle,
	 live_lv7loc_id,
	 lv10loc_id,
	 used_cubic_meters,
	 used_dsp_sqmeters,
	 used_flr_sqmeters,
	 used_linear_meters,
	 loss_sales,
	 loss_gp,
	 proj_sales,
	 proj_gp,
	 gm_roii,
	 days_in_period,
	 days_supply,
	 dpp_dollar,
	 dpp_item,
	 cost_of_invent,
	 dir_cost_of_sales,
	 indir_cost_of_sale,
	 posit_sales,
	 posit_mvmt,
	 posit_norm_mvmt,
	 include_in_avg,
	 total_caps,
	 total_units,
	 total_items,
	 vat,
	 supp_total_sales,
	 supp_cost_of_sales,
	 supp_posit_mvmt,
	 supplier_norm_mvmt,
	 num_user1,
	 num_user2,
	 num_user3,
	 num_user4,
	 num_user5,
	 num_user6,
	 oh_qty,
	 oh_cost,
	 oh_retail,
	 pog_retail,
	 concat_id,
/* Added columns on 06/22/1999  Suresh */
	 ALLOC_CUBIC_METERS,
	 ALLOC_DSP_SQMETERS,
	 ALLOC_FLR_SQMETERS,
	 ALLOC_LINEAR_METER,
	 POSIT_MVMT_REG ,
	 POSIT_SALES_REG,
	 POSIT_COST_REG ,
	 POSIT_MVMT_PROMO ,
	 POSIT_SALES_PROMO,
	 POSIT_COST_PROMO ,
	 POSIT_MVMT_CLRNC ,
	 POSIT_SALES_CLRNC,
	 POSIT_COST_CLRNC ,
	 POSIT_MVMT_RETN,
	 POSIT_SALES_RETN ,
	 POSIT_COST_RETN,
	 Inventory_items,
	 inventory_retail,
	 inventory_cost,
	 received_items,
	 received_retail,
	 received_cost,
	 total_items_retail,
	 total_items_cost,
	 min_pres_items,
	 min_pres_retail,
	 min_pres_cost
	from maxdata.temp_lv10roll;
	commit;

-- seq_num is the old one so actual next id is seq_num + 1 and the final id in the bulk insert is old seq_num + 1 + count

	update maxapp.sequence
	set seq_num = t_seq_id + roll_count + 1
	where level_type = 10 and entity_type = 6;

	commit;

	delete from maxdata.temp_lv10roll;

	/* Populate lv9roll from lv9finc */

	insert into maxdata.lv9roll(last_update,
    changed_by_batch,
    version_id,
    cycle,
    live_lv7loc_id,
    lv9loc_id,
    cubic_meters,
    dsp_sqmeters,
    flr_sqmeters,
    linear_meters,
    used_cubic_meters,
    used_dsp_sqmeters,
    used_linear_meters,
    loss_sales,
    loss_gp,
    proj_sales,
    proj_gp,
    gm_roii,
    days_in_period,
    days_supply,
    dpp_dollar,
    dpp_item,
    cost_of_invent,
    dir_cost_of_sales,
    indir_cost_of_sale,
    posit_sales,
    posit_mvmt,
    posit_norm_mvmt,
    count_inc_in_avg,
    total_caps,
    total_units,
    total_items,
    vat,
    supp_total_sales,
    supp_cost_of_sales,
    supp_posit_mvmt,
    supplier_norm_mvmt,
    num_user1,
    num_user2,
    num_user3,
    num_user4,
    num_user5,
    num_user6,
    oh_qty,
    oh_cost,
    oh_retail,
    pog_retail,
    periods_rolled,
    concat_id)
    select sysdate,
      1,
      1,
      max(lv9finc.cycle),
      lv9finc.live_lv7loc_id,
      lv9finc.lv9loc_id,
      sum(lv9finc.cubic_meters),
      sum(lv9finc.dsp_sqmeters),
      sum(lv9finc.flr_sqmeters),
      sum(lv9finc.linear_meters),
      sum(lv9finc.used_cubic_meters),
      sum(lv9finc.used_dsp_sqmeters),
      sum(lv9finc.used_linear_meters),
      sum(lv9finc.loss_sales),
      sum(lv9finc.loss_gp),
      sum(lv9finc.proj_sales),
      sum(lv9finc.proj_gp),
      1,
      sum(lv9finc.days_in_period),
      1,
      sum(lv9finc.dpp_dollar),
      sum(lv9finc.dpp_item),
      sum(lv9finc.cost_of_invent),
      sum(lv9finc.dir_cost_of_sales),
      sum(lv9finc.indir_cost_of_sale),
      sum(lv9finc.posit_sales),
      sum(lv9finc.posit_mvmt),
      sum(lv9finc.posit_norm_mvmt),
      sum(lv9finc.count_inc_in_avg),
      sum(lv9finc.total_caps),
      sum(lv9finc.total_units),
      sum(lv9finc.total_items),
      sum(lv9finc.vat),
      sum(lv9finc.supp_total_sales),
      sum(lv9finc.supp_cost_of_sales),
      sum(lv9finc.supp_posit_mvmt),
      sum(lv9finc.supplier_norm_mvmt),
      sum(lv9finc.num_user1),
      sum(lv9finc.num_user2),
      sum(lv9finc.num_user3),
      sum(lv9finc.num_user4),
      avg(lv9finc.num_user5),
      avg(lv9finc.num_user6),
      sum(lv9finc.oh_qty),
      sum(lv9finc.oh_cost),
      sum(lv9finc.oh_retail),
      sum(lv9finc.pog_retail),
      x,
      lv9finc.lv9loc_id||'-'||lv9finc.live_lv7loc_id
      from maxdata.lv9finc
            where(lv9finc.cycle||lpad(lv9finc.period,7,0))
                 <=(current_cycle_id||lpad(current_period_id,7,0))
            and (lv9finc.cycle||lpad(lv9finc.period,7,0))
                 >=(cycle_id_to_roll_from||lpad(period_id_to_roll_from,7,0))
      group by lv9finc.live_lv7loc_id,lv9finc.lv9loc_id;
    update maxdata.lv9roll set
    lv9roll.count_num_prodloc
    =(select count(lv10loc_id) from maxdata.lv10loc
      where lv10loc.lv9loc_id=lv9roll.lv9loc_id);


/* Populate lv8roll from lv8finc */
  insert into maxdata.lv8roll(last_update,
    changed_by_batch,
    version_id,
    cycle,
    live_lv7loc_id,
    lv8loc_id,
    cubic_meters,
    dsp_sqmeters,
    flr_sqmeters,
    linear_meters,
    used_cubic_meters,
    used_dsp_sqmeters,
    used_linear_meters,
    loss_sales,
    loss_gp,
    proj_sales,
    proj_gp,
    gm_roii,
    days_in_period,
    days_supply,
    dpp_dollar,
    dpp_item,
    cost_of_invent,
    dir_cost_of_sales,
    indir_cost_of_sale,
    posit_sales,
    posit_mvmt,
    posit_norm_mvmt,
    count_inc_in_avg,
    total_caps,
    total_units,
    total_items,
    vat,
    supp_total_sales,
    supp_cost_of_sales,
    supp_posit_mvmt,
    supplier_norm_mvmt,
    num_user1,
    num_user2,
    num_user3,
    num_user4,
    num_user5,
    num_user6,
    oh_qty,
    oh_cost,
    oh_retail,
    pog_retail,
    periods_rolled,
    concat_id)
    select sysdate,
      1,
      1,
      max(lv8finc.cycle),
      lv8finc.live_lv7loc_id,
      lv8finc.lv8loc_id,
      sum(lv8finc.cubic_meters),
      sum(lv8finc.dsp_sqmeters),
      sum(lv8finc.flr_sqmeters),
      sum(lv8finc.linear_meters),
      sum(lv8finc.used_cubic_meters),
      sum(lv8finc.used_dsp_sqmeters),
      sum(lv8finc.used_linear_meters),
      sum(lv8finc.loss_sales),
      sum(lv8finc.loss_gp),
      sum(lv8finc.proj_sales),
      sum(lv8finc.proj_gp),
      1,
      sum(lv8finc.days_in_period),
      1,
      sum(lv8finc.dpp_dollar),
      sum(lv8finc.dpp_item),
      sum(lv8finc.cost_of_invent),
      sum(lv8finc.dir_cost_of_sales),
      sum(lv8finc.indir_cost_of_sale),
      sum(lv8finc.posit_sales),
      sum(lv8finc.posit_mvmt),
      sum(lv8finc.posit_norm_mvmt),
      sum(lv8finc.count_inc_in_avg),
      sum(lv8finc.total_caps),
      sum(lv8finc.total_units),
      sum(lv8finc.total_items),
      sum(lv8finc.vat),
      sum(lv8finc.supp_total_sales),
      sum(lv8finc.supp_cost_of_sales),
      sum(lv8finc.supp_posit_mvmt),
      sum(lv8finc.supplier_norm_mvmt),
      sum(lv8finc.num_user1),
      sum(lv8finc.num_user2),
      sum(lv8finc.num_user3),
      sum(lv8finc.num_user4),
      avg(lv8finc.num_user5),
      avg(lv8finc.num_user6),
      sum(lv8finc.oh_qty),
      sum(lv8finc.oh_cost),
      sum(lv8finc.oh_retail),
      sum(lv8finc.pog_retail),
      x,
      lv8finc.lv8loc_id||'-'||lv8finc.live_lv7loc_id
      from maxdata.lv8finc
            where(lv8finc.cycle||lpad(lv8finc.period,7,0))
                 <=(current_cycle_id||lpad(current_period_id,7,0))
            and(lv8finc.cycle||lpad(lv8finc.period,7,0))
                 >=(cycle_id_to_roll_from||lpad(period_id_to_roll_from,7,0))
      group by lv8finc.live_lv7loc_id,lv8finc.lv8loc_id;
    update maxdata.lv8roll set
    lv8roll.count_num_prodloc
    =(select count(lv10loc_id) from maxdata.lv10loc
      where lv10loc.lv8loc_id
      =lv8roll.lv8loc_id);

/* Populate lv7roll from lv7finc */
  insert into maxdata.lv7roll(last_update,
    changed_by_batch,
    version_id,
    cycle,
    lv7loc_id,
    cubic_meters,
    dsp_sqmeters,
    flr_sqmeters,
    linear_meters,
    used_cubic_meters,
    used_dsp_sqmeters,
    used_linear_meters,
    loss_sales,
    loss_gp,
    proj_sales,
    proj_gp,
    gm_roii,
    days_in_period,
    days_supply,
    dpp_dollar,
    dpp_item,
    cost_of_invent,
    dir_cost_of_sales,
    indir_cost_of_sale,
    posit_sales,
    posit_mvmt,
    posit_norm_mvmt,
    count_inc_in_avg,
    total_caps,
    total_units,
    total_items,
    vat,
    supp_total_sales,
    supp_cost_of_sales,
    supp_posit_mvmt,
    supplier_norm_mvmt,
    num_user1,
    num_user2,
    num_user3,
    num_user4,
    num_user5,
    num_user6,
    oh_qty,
    oh_cost,
    oh_retail,
    pog_retail,
    periods_rolled,
/* Added columns on 06/22/1999  Suresh */
	 ALLOC_CUBIC_METERS,
		ALLOC_DSP_SQMETERS,
		ALLOC_FLR_SQMETERS,
		ALLOC_LINEAR_METER,
		POSIT_MVMT_REG ,
		POSIT_SALES_REG,
		POSIT_COST_REG ,
		POSIT_MVMT_PROMO ,
		POSIT_SALES_PROMO,
		POSIT_COST_PROMO ,
		POSIT_MVMT_CLRNC ,
		POSIT_SALES_CLRNC,
		POSIT_COST_CLRNC ,
		POSIT_MVMT_RETN,
		POSIT_SALES_RETN ,
		POSIT_COST_RETN,
		INVENTORY_ITEMS,
		INVENTORY_RETAIL ,
		INVENTORY_COST ,
		RECEIVED_ITEMS ,
		RECEIVED_RETAIL,
		RECEIVED_COST,
		TOTAL_ITEMS_RETAIL ,
		TOTAL_ITEMS_COST ,
		MIN_PRES_ITEMS ,
		MIN_PRES_RETAIL,
		MIN_PRES_COST)
    select sysdate,
      1,
      1,
      max(lv7finc.cycle),
      lv7finc.lv7loc_id,
      sum(lv7finc.cubic_meters),
      sum(lv7finc.dsp_sqmeters),
      sum(lv7finc.flr_sqmeters),
      sum(lv7finc.linear_meters),
      sum(lv7finc.used_cubic_meters),
      sum(lv7finc.used_dsp_sqmeters),
      sum(lv7finc.used_linear_meters),
      sum(lv7finc.loss_sales),
      sum(lv7finc.loss_gp),
      sum(lv7finc.proj_sales),
      sum(lv7finc.proj_gp),
      1,
      sum(lv7finc.days_in_period),
      1,
      sum(lv7finc.dpp_dollar),
      sum(lv7finc.dpp_item),
      sum(lv7finc.cost_of_invent),
      sum(lv7finc.dir_cost_of_sales),
      sum(lv7finc.indir_cost_of_sale),
      sum(lv7finc.posit_sales),
      sum(lv7finc.posit_mvmt),
      sum(lv7finc.posit_norm_mvmt),
      sum(lv7finc.count_inc_in_avg),
      sum(lv7finc.total_caps),
      sum(lv7finc.total_units),
      sum(lv7finc.total_items),
      sum(lv7finc.vat),
      sum(lv7finc.supp_total_sales),
      sum(lv7finc.supp_cost_of_sales),
      sum(lv7finc.supp_posit_mvmt),
      sum(lv7finc.supplier_norm_mvmt),
      sum(lv7finc.num_user1),
      sum(lv7finc.num_user2),
      sum(lv7finc.num_user3),
      sum(lv7finc.num_user4),
      avg(lv7finc.num_user5),
      avg(lv7finc.num_user6),
      sum(lv7finc.oh_qty),
      sum(lv7finc.oh_cost),
      sum(lv7finc.oh_retail),
      sum(lv7finc.pog_retail),
      x,
		sum(lv7finc.ALLOC_CUBIC_METERS),
		sum(lv7finc.ALLOC_DSP_SQMETERS),
		sum(lv7finc.ALLOC_FLR_SQMETERS),
		sum(lv7finc.ALLOC_LINEAR_METER),
		sum(lv7finc.POSIT_MVMT_REG ),
		sum(lv7finc.POSIT_SALES_REG),
		sum(lv7finc.POSIT_COST_REG ),
		sum(lv7finc.POSIT_MVMT_PROMO ),
		sum(lv7finc.POSIT_SALES_PROMO),
		sum(lv7finc.POSIT_COST_PROMO ),
		sum(lv7finc.POSIT_MVMT_CLRNC ),
		sum(lv7finc.POSIT_SALES_CLRNC),
		sum(lv7finc.POSIT_COST_CLRNC) ,
		sum(lv7finc.POSIT_MVMT_RETN),
		sum(lv7finc.POSIT_SALES_RETN) ,
		sum(lv7finc.POSIT_COST_RETN),
		sum(lv7finc.INVENTORY_ITEMS),
		sum(lv7finc.INVENTORY_RETAIL) ,
		sum(lv7finc.INVENTORY_COST) ,
		sum(lv7finc.RECEIVED_ITEMS) ,
		sum(lv7finc.RECEIVED_RETAIL),
		sum(lv7finc.RECEIVED_COST),
		sum(lv7finc.TOTAL_ITEMS_RETAIL) ,
		sum(lv7finc.TOTAL_ITEMS_COST) ,
		sum(lv7finc.MIN_PRES_ITEMS ),
		sum(lv7finc.MIN_PRES_RETAIL),
		sum(lv7finc.MIN_PRES_COST)

      from maxdata.lv7finc
            where(lv7finc.cycle||lpad(lv7finc.period,7,0))
                 <=(current_cycle_id||lpad(current_period_id,7,0))
            and(lv7finc.cycle||lpad(lv7finc.period,7,0))
                 >=(cycle_id_to_roll_from||lpad(period_id_to_roll_from,7,0))
      group by lv7finc.lv7loc_id;
    update maxdata.lv7roll set
    lv7roll.count_num_prodloc
    =(select count(lv10loc_id) from maxdata.lv10loc
      where lv10loc.lv7loc_id
      =lv7roll.lv7loc_id);

/* Populate lv6roll from lv6finC  */
  insert into maxdata.lv6roll(last_update,
    changed_by_batch,
    version_id,
    cycle,
    lv6loc_id,
    cubic_meters,
    dsp_sqmeters,
    flr_sqmeters,
    linear_meters,
    used_cubic_meters,
    used_dsp_sqmeters,
    used_linear_meters,
    loss_sales,
    loss_gp,
    proj_sales,
    proj_gp,
    gm_roii,
    days_in_period,
    days_supply,
    dpp_dollar,
    dpp_item,
    cost_of_invent,
    dir_cost_of_sales,
    indir_cost_of_sale,
    posit_sales,
    posit_mvmt,
    posit_norm_mvmt,
    count_inc_in_avg,
    total_caps,
    total_units,
    total_items,
    vat,
    supp_total_sales,
    supp_cost_of_sales,
    supp_posit_mvmt,
    supplier_norm_mvmt,
    num_user1,
    num_user2,
    num_user3,
    num_user4,
    num_user5,
    num_user6,
    oh_qty,
    oh_cost,
    oh_retail,
    pog_retail,
    periods_rolled,
/* Added columns on 06/22/1999  Suresh */
		ALLOC_CUBIC_METERS,
		ALLOC_DSP_SQMETERS,
		ALLOC_FLR_SQMETERS,
		ALLOC_LINEAR_METER,
		POSIT_MVMT_REG ,
		POSIT_SALES_REG,
		POSIT_COST_REG ,
		POSIT_MVMT_PROMO ,
		POSIT_SALES_PROMO,
		POSIT_COST_PROMO ,
		POSIT_MVMT_CLRNC ,
		POSIT_SALES_CLRNC,
		POSIT_COST_CLRNC ,
		POSIT_MVMT_RETN,
		POSIT_SALES_RETN ,
		POSIT_COST_RETN,
		INVENTORY_ITEMS,
		INVENTORY_RETAIL ,
		INVENTORY_COST ,
		RECEIVED_ITEMS ,
		RECEIVED_RETAIL,
		RECEIVED_COST,
		TOTAL_ITEMS_RETAIL ,
		TOTAL_ITEMS_COST ,
		MIN_PRES_ITEMS ,
		MIN_PRES_RETAIL,
		MIN_PRES_COST)
    select sysdate,
      1,
      1,
      max(lv6finc.cycle),
      lv6finc.lv6loc_id,
      sum(lv6finc.cubic_meters),
      sum(lv6finc.dsp_sqmeters),
      sum(lv6finc.flr_sqmeters),
      sum(lv6finc.linear_meters),
      sum(lv6finc.used_cubic_meters),
      sum(lv6finc.used_dsp_sqmeters),
      sum(lv6finc.used_linear_meters),
      sum(lv6finc.loss_sales),
      sum(lv6finc.loss_gp),
      sum(lv6finc.proj_sales),
      sum(lv6finc.proj_gp),
      1,
      sum(lv6finc.days_in_period),
      1,
      sum(lv6finc.dpp_dollar),
      sum(lv6finc.dpp_item),
      sum(lv6finc.cost_of_invent),
      sum(lv6finc.dir_cost_of_sales),
      sum(lv6finc.indir_cost_of_sale),
      sum(lv6finc.posit_sales),
      sum(lv6finc.posit_mvmt),
      sum(lv6finc.posit_norm_mvmt),
      sum(lv6finc.count_inc_in_avg),
      sum(lv6finc.total_caps),
      sum(lv6finc.total_units),
      sum(lv6finc.total_items),
      sum(lv6finc.vat),
      sum(lv6finc.supp_total_sales),
      sum(lv6finc.supp_cost_of_sales),
      sum(lv6finc.supp_posit_mvmt),
      sum(lv6finc.supplier_norm_mvmt),
      sum(lv6finc.num_user1),
      sum(lv6finc.num_user2),
      sum(lv6finc.num_user3),
      sum(lv6finc.num_user4),
      avg(lv6finc.num_user5),
      avg(lv6finc.num_user6),
      sum(lv6finc.oh_qty),
      sum(lv6finc.oh_cost),
      sum(lv6finc.oh_retail),
      sum(lv6finc.pog_retail),
      x,
		sum(lv6finc.ALLOC_CUBIC_METERS),
		sum(lv6finc.ALLOC_DSP_SQMETERS),
		sum(lv6finc.ALLOC_FLR_SQMETERS),
		sum(lv6finc.ALLOC_LINEAR_METER),
		sum(lv6finc.POSIT_MVMT_REG ),
		sum(lv6finc.POSIT_SALES_REG),
		sum(lv6finc.POSIT_COST_REG ),
		sum(lv6finc.POSIT_MVMT_PROMO ),
		sum(lv6finc.POSIT_SALES_PROMO),
		sum(lv6finc.POSIT_COST_PROMO ),
		sum(lv6finc.POSIT_MVMT_CLRNC ),
		sum(lv6finc.POSIT_SALES_CLRNC),
		sum(lv6finc.POSIT_COST_CLRNC) ,
		sum(lv6finc.POSIT_MVMT_RETN),
		sum(lv6finc.POSIT_SALES_RETN) ,
		sum(lv6finc.POSIT_COST_RETN),
		sum(lv6finc.INVENTORY_ITEMS),
		sum(lv6finc.INVENTORY_RETAIL) ,
		sum(lv6finc.INVENTORY_COST) ,
		sum(lv6finc.RECEIVED_ITEMS) ,
		sum(lv6finc.RECEIVED_RETAIL),
		sum(lv6finc.RECEIVED_COST),
		sum(lv6finc.TOTAL_ITEMS_RETAIL) ,
		sum(lv6finc.TOTAL_ITEMS_COST) ,
		sum(lv6finc.MIN_PRES_ITEMS ),
		sum(lv6finc.MIN_PRES_RETAIL),
		sum(lv6finc.MIN_PRES_COST)
      from maxdata.lv6finc
            where(lv6finc.cycle||lpad(lv6finc.period,7,0))
                  <=(current_cycle_id||lpad(current_period_id,7,0))
            and(lv6finc.cycle||lpad(lv6finc.period,7,0))
                  >=(cycle_id_to_roll_from||lpad(period_id_to_roll_from,7,0))
      group by lv6finc.lv6loc_id;
    update maxdata.lv6roll set
    lv6roll.count_num_prodloc
    =(select count(lv10loc_id) from maxdata.lv10loc
      where lv10loc.lv6loc_id
      =lv6roll.lv6loc_id);

/* Populate lv5roll from lv5finc */
  insert into maxdata.lv5roll(last_update,
    changed_by_batch,
    version_id,
    cycle,
    lv5loc_id,
    cubic_meters,
    dsp_sqmeters,
    flr_sqmeters,
    linear_meters,
    used_cubic_meters,
    used_dsp_sqmeters,
    used_linear_meters,
    loss_sales,
    loss_gp,
    proj_sales,
    proj_gp,
    gm_roii,
    days_in_period,
    days_supply,
    dpp_dollar,
    dpp_item,
    cost_of_invent,
    dir_cost_of_sales,
    indir_cost_of_sale,
    posit_sales,
    posit_mvmt,
    posit_norm_mvmt,
    count_inc_in_avg,
    total_caps,
    total_units,
    total_items,
    vat,
    supp_total_sales,
    supp_cost_of_sales,
    supp_posit_mvmt,
    supplier_norm_mvmt,
    num_user1,
    num_user2,
    num_user3,
    num_user4,
    num_user5,
    num_user6,
    oh_qty,
    oh_cost,
    oh_retail,
    pog_retail,
    periods_rolled,
/* Added columns on 06/22/1999  Suresh */
		ALLOC_CUBIC_METERS,
		ALLOC_DSP_SQMETERS,
		ALLOC_FLR_SQMETERS,
		ALLOC_LINEAR_METER,
		POSIT_MVMT_REG ,
		POSIT_SALES_REG,
		POSIT_COST_REG ,
		POSIT_MVMT_PROMO ,
		POSIT_SALES_PROMO,
		POSIT_COST_PROMO ,
		POSIT_MVMT_CLRNC ,
		POSIT_SALES_CLRNC,
		POSIT_COST_CLRNC ,
		POSIT_MVMT_RETN,
		POSIT_SALES_RETN ,
		POSIT_COST_RETN,
		INVENTORY_ITEMS,
		INVENTORY_RETAIL ,
		INVENTORY_COST ,
		RECEIVED_ITEMS ,
		RECEIVED_RETAIL,
		RECEIVED_COST,
		TOTAL_ITEMS_RETAIL ,
		TOTAL_ITEMS_COST ,
		MIN_PRES_ITEMS ,
		MIN_PRES_RETAIL,
		MIN_PRES_COST)
    select sysdate,
      1,
      1,
      max(lv5finc.cycle),
      lv5finc.lv5loc_id,
      sum(lv5finc.cubic_meters),
      sum(lv5finc.dsp_sqmeters),
      sum(lv5finc.flr_sqmeters),
      sum(lv5finc.linear_meters),
      sum(lv5finc.used_cubic_meters),
      sum(lv5finc.used_dsp_sqmeters),
      sum(lv5finc.used_linear_meters),
      sum(lv5finc.loss_sales),
      sum(lv5finc.loss_gp),
      sum(lv5finc.proj_sales),
      sum(lv5finc.proj_gp),
      1,
      sum(lv5finc.days_in_period),
      1,
      sum(lv5finc.dpp_dollar),
      sum(lv5finc.dpp_item),
      sum(lv5finc.cost_of_invent),
      sum(lv5finc.dir_cost_of_sales),
      sum(lv5finc.indir_cost_of_sale),
      sum(lv5finc.posit_sales),
      sum(lv5finc.posit_mvmt),
      sum(lv5finc.posit_norm_mvmt),
      sum(lv5finc.count_inc_in_avg),
      sum(lv5finc.total_caps),
      sum(lv5finc.total_units),
      sum(lv5finc.total_items),
      sum(lv5finc.vat),
      sum(lv5finc.supp_total_sales),
      sum(lv5finc.supp_cost_of_sales),
      sum(lv5finc.supp_posit_mvmt),
      sum(lv5finc.supplier_norm_mvmt),
      sum(lv5finc.num_user1),
      sum(lv5finc.num_user2),
      sum(lv5finc.num_user3),
      sum(lv5finc.num_user4),
      avg(lv5finc.num_user5),
      avg(lv5finc.num_user6),
      sum(lv5finc.oh_qty),
      sum(lv5finc.oh_cost),
      sum(lv5finc.oh_retail),
      sum(lv5finc.pog_retail),
      x,
		sum(lv5finc.ALLOC_CUBIC_METERS),
		sum(lv5finc.ALLOC_DSP_SQMETERS),
		sum(lv5finc.ALLOC_FLR_SQMETERS),
		sum(lv5finc.ALLOC_LINEAR_METER),
		sum(lv5finc.POSIT_MVMT_REG ),
		sum(lv5finc.POSIT_SALES_REG),
		sum(lv5finc.POSIT_COST_REG ),
		sum(lv5finc.POSIT_MVMT_PROMO ),
		sum(lv5finc.POSIT_SALES_PROMO),
		sum(lv5finc.POSIT_COST_PROMO ),
		sum(lv5finc.POSIT_MVMT_CLRNC ),
		sum(lv5finc.POSIT_SALES_CLRNC),
		sum(lv5finc.POSIT_COST_CLRNC) ,
		sum(lv5finc.POSIT_MVMT_RETN),
		sum(lv5finc.POSIT_SALES_RETN) ,
		sum(lv5finc.POSIT_COST_RETN),
		sum(lv5finc.INVENTORY_ITEMS),
		sum(lv5finc.INVENTORY_RETAIL) ,
		sum(lv5finc.INVENTORY_COST) ,
		sum(lv5finc.RECEIVED_ITEMS) ,
		sum(lv5finc.RECEIVED_RETAIL),
		sum(lv5finc.RECEIVED_COST),
		sum(lv5finc.TOTAL_ITEMS_RETAIL) ,
		sum(lv5finc.TOTAL_ITEMS_COST) ,
		sum(lv5finc.MIN_PRES_ITEMS ),
		sum(lv5finc.MIN_PRES_RETAIL),
		sum(lv5finc.MIN_PRES_COST)
      from maxdata.lv5finc
            where(lv5finc.cycle||lpad(lv5finc.period,7,0))
                  <=(current_cycle_id||lpad(current_period_id,7,0))
            and(lv5finc.cycle||lpad(lv5finc.period,7,0))
                  >=(cycle_id_to_roll_from||lpad(period_id_to_roll_from,7,0))
      group by lv5finc.lv5loc_id;
    update maxdata.lv5roll set
    lv5roll.count_num_prodloc
    =(select count(lv10loc_id) from maxdata.lv10loc
      where lv10loc.lv5loc_id
      =lv5roll.lv5loc_id);


/* Populate table lv4roll from lv4finc */
  insert into maxdata.lv4roll(last_update,
    changed_by_batch,
    version_id,
    cycle,
    lv4loc_id,
    cubic_meters,
    dsp_sqmeters,
    flr_sqmeters,
    linear_meters,
    used_cubic_meters,
    used_dsp_sqmeters,
    used_linear_meters,
    loss_sales,
    loss_gp,
    proj_sales,
    proj_gp,
    gm_roii,
    days_in_period,
    days_supply,
    dpp_dollar,
    dpp_item,
    cost_of_invent,
    dir_cost_of_sales,
    indir_cost_of_sale,
    posit_sales,
    posit_mvmt,
    posit_norm_mvmt,
    count_inc_in_avg,
    total_caps,
    total_units,
    total_items,
    vat,
    supp_total_sales,
    supp_cost_of_sales,
    supp_posit_mvmt,
    supplier_norm_mvmt,
    num_user1,
    num_user2,
    num_user3,
    num_user4,
    num_user5,
    num_user6,
    oh_qty,
    oh_cost,
    oh_retail,
    pog_retail,
    periods_rolled,
/* Added columns on 06/22/1999  Suresh */
		ALLOC_CUBIC_METERS,
		ALLOC_DSP_SQMETERS,
		ALLOC_FLR_SQMETERS,
		ALLOC_LINEAR_METER,
		POSIT_MVMT_REG ,
		POSIT_SALES_REG,
		POSIT_COST_REG ,
		POSIT_MVMT_PROMO ,
		POSIT_SALES_PROMO,
		POSIT_COST_PROMO ,
		POSIT_MVMT_CLRNC ,
		POSIT_SALES_CLRNC,
		POSIT_COST_CLRNC ,
		POSIT_MVMT_RETN,
		POSIT_SALES_RETN ,
		POSIT_COST_RETN,
		INVENTORY_ITEMS,
		INVENTORY_RETAIL ,
		INVENTORY_COST ,
		RECEIVED_ITEMS ,
		RECEIVED_RETAIL,
		RECEIVED_COST,
		TOTAL_ITEMS_RETAIL ,
		TOTAL_ITEMS_COST ,
		MIN_PRES_ITEMS ,
		MIN_PRES_RETAIL,
		MIN_PRES_COST)
    select sysdate,
      1,
      1,
      max(lv4finc.cycle),
      lv4finc.lv4loc_id,
      sum(lv4finc.cubic_meters),
      sum(lv4finc.dsp_sqmeters),
      sum(lv4finc.flr_sqmeters),
      sum(lv4finc.linear_meters),
      sum(lv4finc.used_cubic_meters),
      sum(lv4finc.used_dsp_sqmeters),
      sum(lv4finc.used_linear_meters),
      sum(lv4finc.loss_sales),
      sum(lv4finc.loss_gp),
      sum(lv4finc.proj_sales),
      sum(lv4finc.proj_gp),
      1,
      sum(lv4finc.days_in_period),
      1,
      sum(lv4finc.dpp_dollar),
      sum(lv4finc.dpp_item),
      sum(lv4finc.cost_of_invent),
      sum(lv4finc.dir_cost_of_sales),
      sum(lv4finc.indir_cost_of_sale),
      sum(lv4finc.posit_sales),
      sum(lv4finc.posit_mvmt),
      sum(lv4finc.posit_norm_mvmt),
      sum(lv4finc.count_inc_in_avg),
      sum(lv4finc.total_caps),
      sum(lv4finc.total_units),
      sum(lv4finc.total_items),
      sum(lv4finc.vat),
      sum(lv4finc.supp_total_sales),
      sum(lv4finc.supp_cost_of_sales),
      sum(lv4finc.supp_posit_mvmt),
      sum(lv4finc.supplier_norm_mvmt),
      sum(lv4finc.num_user1),
      sum(lv4finc.num_user2),
      sum(lv4finc.num_user3),
      sum(lv4finc.num_user4),
      avg(lv4finc.num_user5),
      avg(lv4finc.num_user6),
      sum(lv4finc.oh_qty),
      sum(lv4finc.oh_cost),
      sum(lv4finc.oh_retail),
      sum(lv4finc.pog_retail),
      x,
		sum(lv4finc.ALLOC_CUBIC_METERS),
		sum(lv4finc.ALLOC_DSP_SQMETERS),
		sum(lv4finc.ALLOC_FLR_SQMETERS),
		sum(lv4finc.ALLOC_LINEAR_METER),
		sum(lv4finc.POSIT_MVMT_REG ),
		sum(lv4finc.POSIT_SALES_REG),
		sum(lv4finc.POSIT_COST_REG ),
		sum(lv4finc.POSIT_MVMT_PROMO ),
		sum(lv4finc.POSIT_SALES_PROMO),
		sum(lv4finc.POSIT_COST_PROMO ),
		sum(lv4finc.POSIT_MVMT_CLRNC ),
		sum(lv4finc.POSIT_SALES_CLRNC),
		sum(lv4finc.POSIT_COST_CLRNC) ,
		sum(lv4finc.POSIT_MVMT_RETN),
		sum(lv4finc.POSIT_SALES_RETN) ,
		sum(lv4finc.POSIT_COST_RETN),
		sum(lv4finc.INVENTORY_ITEMS),
		sum(lv4finc.INVENTORY_RETAIL) ,
		sum(lv4finc.INVENTORY_COST) ,
		sum(lv4finc.RECEIVED_ITEMS) ,
		sum(lv4finc.RECEIVED_RETAIL),
		sum(lv4finc.RECEIVED_COST),
		sum(lv4finc.TOTAL_ITEMS_RETAIL) ,
		sum(lv4finc.TOTAL_ITEMS_COST) ,
		sum(lv4finc.MIN_PRES_ITEMS ),
		sum(lv4finc.MIN_PRES_RETAIL),
		sum(lv4finc.MIN_PRES_COST)
      from maxdata.lv4finc
            where(lv4finc.cycle||lpad(lv4finc.period,7,0))
                  <=(current_cycle_id||lpad(current_period_id,7,0))
            and(lv4finc.cycle||lpad(lv4finc.period,7,0))
                  >=(cycle_id_to_roll_from||lpad(period_id_to_roll_from,7,0))
      group by lv4finc.lv4loc_id;
    update maxdata.lv4roll set
    lv4roll.count_num_prodloc
    =(select count(lv10loc_id) from maxdata.lv10loc
      where lv10loc.lv4loc_id
      =lv4roll.lv4loc_id);


/* Populating lv3roll from lv3finc */
  insert into maxdata.lv3roll(last_update,
    changed_by_batch,
    version_id,
    cycle,
    lv3loc_id,
    cubic_meters,
    dsp_sqmeters,
    flr_sqmeters,
    linear_meters,
    used_cubic_meters,
    used_dsp_sqmeters,
    used_linear_meters,
    loss_sales,
    loss_gp,
    proj_sales,
    proj_gp,
    gm_roii,
    days_in_period,
    days_supply,
    dpp_dollar,
    dpp_item,
    cost_of_invent,
    dir_cost_of_sales,
    indir_cost_of_sale,
    posit_sales,
    posit_mvmt,
    posit_norm_mvmt,
    count_inc_in_avg,
    total_caps,
    total_units,
    total_items,
    vat,
    supp_total_sales,
    supp_cost_of_sales,
    supp_posit_mvmt,
    supplier_norm_mvmt,
    num_user1,
    num_user2,
    num_user3,
    num_user4,
    num_user5,
    num_user6,
    oh_qty,
    oh_cost,
    oh_retail,
    pog_retail,
    periods_rolled,
/* Added columns on 06/22/1999  Suresh */
		ALLOC_CUBIC_METERS,
		ALLOC_DSP_SQMETERS,
		ALLOC_FLR_SQMETERS,
		ALLOC_LINEAR_METER,
		POSIT_MVMT_REG ,
		POSIT_SALES_REG,
		POSIT_COST_REG ,
		POSIT_MVMT_PROMO ,
		POSIT_SALES_PROMO,
		POSIT_COST_PROMO ,
		POSIT_MVMT_CLRNC ,
		POSIT_SALES_CLRNC,
		POSIT_COST_CLRNC ,
		POSIT_MVMT_RETN,
		POSIT_SALES_RETN ,
		POSIT_COST_RETN,
		INVENTORY_ITEMS,
		INVENTORY_RETAIL ,
		INVENTORY_COST ,
		RECEIVED_ITEMS ,
		RECEIVED_RETAIL,
		RECEIVED_COST,
		TOTAL_ITEMS_RETAIL ,
		TOTAL_ITEMS_COST ,
		MIN_PRES_ITEMS ,
		MIN_PRES_RETAIL,
		MIN_PRES_COST)
    select sysdate,
      1,
      1,
      max(lv3finc.cycle),
      lv3finc.lv3loc_id,
      sum(lv3finc.cubic_meters),
      sum(lv3finc.dsp_sqmeters),
      sum(lv3finc.flr_sqmeters),
      sum(lv3finc.linear_meters),
      sum(lv3finc.used_cubic_meters),
      sum(lv3finc.used_dsp_sqmeters),
      sum(lv3finc.used_linear_meters),
      sum(lv3finc.loss_sales),
      sum(lv3finc.loss_gp),
      sum(lv3finc.proj_sales),
      sum(lv3finc.proj_gp),
      1,
      sum(lv3finc.days_in_period),
      1,
      sum(lv3finc.dpp_dollar),
      sum(lv3finc.dpp_item),
      sum(lv3finc.cost_of_invent),
      sum(lv3finc.dir_cost_of_sales),
      sum(lv3finc.indir_cost_of_sale),
      sum(lv3finc.posit_sales),
      sum(lv3finc.posit_mvmt),
      sum(lv3finc.posit_norm_mvmt),
      sum(lv3finc.count_inc_in_avg),
      sum(lv3finc.total_caps),
      sum(lv3finc.total_units),
      sum(lv3finc.total_items),
      sum(lv3finc.vat),
      sum(lv3finc.supp_total_sales),
      sum(lv3finc.supp_cost_of_sales),
      sum(lv3finc.supp_posit_mvmt),
      sum(lv3finc.supplier_norm_mvmt),
      sum(lv3finc.num_user1),
      sum(lv3finc.num_user2),
      sum(lv3finc.num_user3),
      sum(lv3finc.num_user4),
      avg(lv3finc.num_user5),
      avg(lv3finc.num_user6),
      sum(lv3finc.oh_qty),
      sum(lv3finc.oh_cost),
      sum(lv3finc.oh_retail),
      sum(lv3finc.pog_retail),
      x,
		sum(lv3finc.ALLOC_CUBIC_METERS),
		sum(lv3finc.ALLOC_DSP_SQMETERS),
		sum(lv3finc.ALLOC_FLR_SQMETERS),
		sum(lv3finc.ALLOC_LINEAR_METER),
		sum(lv3finc.POSIT_MVMT_REG ),
		sum(lv3finc.POSIT_SALES_REG),
		sum(lv3finc.POSIT_COST_REG ),
		sum(lv3finc.POSIT_MVMT_PROMO ),
		sum(lv3finc.POSIT_SALES_PROMO),
		sum(lv3finc.POSIT_COST_PROMO ),
		sum(lv3finc.POSIT_MVMT_CLRNC ),
		sum(lv3finc.POSIT_SALES_CLRNC),
		sum(lv3finc.POSIT_COST_CLRNC) ,
		sum(lv3finc.POSIT_MVMT_RETN),
		sum(lv3finc.POSIT_SALES_RETN) ,
		sum(lv3finc.POSIT_COST_RETN),
		sum(lv3finc.INVENTORY_ITEMS),
		sum(lv3finc.INVENTORY_RETAIL) ,
		sum(lv3finc.INVENTORY_COST) ,
		sum(lv3finc.RECEIVED_ITEMS) ,
		sum(lv3finc.RECEIVED_RETAIL),
		sum(lv3finc.RECEIVED_COST),
		sum(lv3finc.TOTAL_ITEMS_RETAIL) ,
		sum(lv3finc.TOTAL_ITEMS_COST) ,
		sum(lv3finc.MIN_PRES_ITEMS ),
		sum(lv3finc.MIN_PRES_RETAIL),
		sum(lv3finc.MIN_PRES_COST)
      from maxdata.lv3finc
            where(lv3finc.cycle||lpad(lv3finc.period,7,0))
                  <=(current_cycle_id||lpad(current_period_id,7,0))
            and(lv3finc.cycle||lpad(lv3finc.period,7,0))
                  >=(cycle_id_to_roll_from||lpad(period_id_to_roll_from,7,0))
      group by lv3finc.lv3loc_id;
    update maxdata.lv3roll set
    lv3roll.count_num_prodloc
    =(select count(lv10loc_id) from maxdata.lv10loc
      where lv10loc.lv3loc_id
      =lv3roll.lv3loc_id);

/* Populating lv2roll from lv2finc */
  insert into maxdata.lv2roll(last_update,
    changed_by_batch,
    version_id,
    cycle,
    lv2loc_id,
    cubic_meters,
    dsp_sqmeters,
    flr_sqmeters,
    linear_meters,
    used_cubic_meters,
    used_dsp_sqmeters,
    used_linear_meters,
    loss_sales,
    loss_gp,
    proj_sales,
    proj_gp,
    gm_roii,
    days_in_period,
    days_supply,
    dpp_dollar,
    dpp_item,
    cost_of_invent,
    dir_cost_of_sales,
    indir_cost_of_sale,
    posit_sales,
    posit_mvmt,
    posit_norm_mvmt,
    count_inc_in_avg,
    total_caps,
    total_units,
    total_items,
    vat,
    supp_total_sales,
    supp_cost_of_sales,
    supp_posit_mvmt,
    supplier_norm_mvmt,
    num_user1,
    num_user2,
    num_user3,
    num_user4,
    num_user5,
    num_user6,
    oh_qty,
    oh_cost,
    oh_retail,
    pog_retail,
    periods_rolled,
/* Added columns on 06/22/1999  Suresh */
		ALLOC_CUBIC_METERS,
		ALLOC_DSP_SQMETERS,
		ALLOC_FLR_SQMETERS,
		ALLOC_LINEAR_METER,
		POSIT_MVMT_REG ,
		POSIT_SALES_REG,
		POSIT_COST_REG ,
		POSIT_MVMT_PROMO ,
		POSIT_SALES_PROMO,
		POSIT_COST_PROMO ,
		POSIT_MVMT_CLRNC ,
		POSIT_SALES_CLRNC,
		POSIT_COST_CLRNC ,
		POSIT_MVMT_RETN,
		POSIT_SALES_RETN ,
		POSIT_COST_RETN,
		INVENTORY_ITEMS,
		INVENTORY_RETAIL ,
		INVENTORY_COST ,
		RECEIVED_ITEMS ,
		RECEIVED_RETAIL,
		RECEIVED_COST,
		TOTAL_ITEMS_RETAIL ,
		TOTAL_ITEMS_COST ,
		MIN_PRES_ITEMS ,
		MIN_PRES_RETAIL,
		MIN_PRES_COST)
    select sysdate,
      1,
      1,
      max(lv2finc.cycle),
      lv2finc.lv2loc_id,
      sum(lv2finc.cubic_meters),
      sum(lv2finc.dsp_sqmeters),
      sum(lv2finc.flr_sqmeters),
      sum(lv2finc.linear_meters),
      sum(lv2finc.used_cubic_meters),
      sum(lv2finc.used_dsp_sqmeters),
      sum(lv2finc.used_linear_meters),
      sum(lv2finc.loss_sales),
      sum(lv2finc.loss_gp),
      sum(lv2finc.proj_sales),
      sum(lv2finc.proj_gp),
      1,
      sum(lv2finc.days_in_period),
      1,
      sum(lv2finc.dpp_dollar),
      sum(lv2finc.dpp_item),
      sum(lv2finc.cost_of_invent),
      sum(lv2finc.dir_cost_of_sales),
      sum(lv2finc.indir_cost_of_sale),
      sum(lv2finc.posit_sales),
      sum(lv2finc.posit_mvmt),
      sum(lv2finc.posit_norm_mvmt),
      sum(lv2finc.count_inc_in_avg),
      sum(lv2finc.total_caps),
      sum(lv2finc.total_units),
      sum(lv2finc.total_items),
      sum(lv2finc.vat),
      sum(lv2finc.supp_total_sales),
      sum(lv2finc.supp_cost_of_sales),
      sum(lv2finc.supp_posit_mvmt),
      sum(lv2finc.supplier_norm_mvmt),
      sum(lv2finc.num_user1),
      sum(lv2finc.num_user2),
      sum(lv2finc.num_user3),
      sum(lv2finc.num_user4),
      avg(lv2finc.num_user5),
      avg(lv2finc.num_user6),
      sum(lv2finc.oh_qty),
      sum(lv2finc.oh_cost),
      sum(lv2finc.oh_retail),
      sum(lv2finc.pog_retail),
      x,
		sum(lv2finc.ALLOC_CUBIC_METERS),
		sum(lv2finc.ALLOC_DSP_SQMETERS),
		sum(lv2finc.ALLOC_FLR_SQMETERS),
		sum(lv2finc.ALLOC_LINEAR_METER),
		sum(lv2finc.POSIT_MVMT_REG ),
		sum(lv2finc.POSIT_SALES_REG),
		sum(lv2finc.POSIT_COST_REG ),
		sum(lv2finc.POSIT_MVMT_PROMO ),
		sum(lv2finc.POSIT_SALES_PROMO),
		sum(lv2finc.POSIT_COST_PROMO ),
		sum(lv2finc.POSIT_MVMT_CLRNC ),
		sum(lv2finc.POSIT_SALES_CLRNC),
		sum(lv2finc.POSIT_COST_CLRNC) ,
		sum(lv2finc.POSIT_MVMT_RETN),
		sum(lv2finc.POSIT_SALES_RETN) ,
		sum(lv2finc.POSIT_COST_RETN),
		sum(lv2finc.INVENTORY_ITEMS),
		sum(lv2finc.INVENTORY_RETAIL) ,
		sum(lv2finc.INVENTORY_COST) ,
		sum(lv2finc.RECEIVED_ITEMS) ,
		sum(lv2finc.RECEIVED_RETAIL),
		sum(lv2finc.RECEIVED_COST),
		sum(lv2finc.TOTAL_ITEMS_RETAIL) ,
		sum(lv2finc.TOTAL_ITEMS_COST) ,
		sum(lv2finc.MIN_PRES_ITEMS ),
		sum(lv2finc.MIN_PRES_RETAIL),
		sum(lv2finc.MIN_PRES_COST)
      from maxdata.lv2finc
            where(lv2finc.cycle||lpad(lv2finc.period,7,0))
                  <=(current_cycle_id||lpad(current_period_id,7,0))
            and(lv2finc.cycle||lpad(lv2finc.period,7,0))
                  >=(cycle_id_to_roll_from||lpad(period_id_to_roll_from,7,0))
      group by lv2finc.lv2loc_id;
    update maxdata.lv2roll set
    lv2roll.count_num_prodloc
    =(select count(lv10loc_id) from maxdata.lv10loc
      where lv10loc.lv2loc_id
      =lv2roll.lv2loc_id);

/* Populating lv1roll from lv1finc */
  insert into maxdata.lv1roll(last_update,
    changed_by_batch,
    version_id,
    cycle,
    lv1loc_id,
    cubic_meters,
    dsp_sqmeters,
    flr_sqmeters,
    linear_meters,
    used_cubic_meters,
    used_dsp_sqmeters,
    used_linear_meters,
    loss_sales,
    loss_gp,
    proj_sales,
    proj_gp,
    gm_roii,
    days_in_period,
    days_supply,
    dpp_dollar,
    dpp_item,
    cost_of_invent,
    dir_cost_of_sales,
    indir_cost_of_sale,
    posit_sales,
    posit_mvmt,
    posit_norm_mvmt,
    count_inc_in_avg,
    total_caps,
    total_units,
    total_items,
    vat,
    supp_total_sales,
    supp_cost_of_sales,
    supp_posit_mvmt,
    supplier_norm_mvmt,
    num_user1,
    num_user2,
    num_user3,
    num_user4,
    num_user5,
    num_user6,
    oh_qty,
    oh_cost,
    oh_retail,
    pog_retail,
    periods_rolled,
/* Added columns on 06/22/1999  Suresh */
		ALLOC_CUBIC_METERS,
		ALLOC_DSP_SQMETERS,
		ALLOC_FLR_SQMETERS,
		ALLOC_LINEAR_METER,
		POSIT_MVMT_REG ,
		POSIT_SALES_REG,
		POSIT_COST_REG ,
		POSIT_MVMT_PROMO ,
		POSIT_SALES_PROMO,
		POSIT_COST_PROMO ,
		POSIT_MVMT_CLRNC ,
		POSIT_SALES_CLRNC,
		POSIT_COST_CLRNC ,
		POSIT_MVMT_RETN,
		POSIT_SALES_RETN ,
		POSIT_COST_RETN,
		INVENTORY_ITEMS,
		INVENTORY_RETAIL ,
		INVENTORY_COST ,
		RECEIVED_ITEMS ,
		RECEIVED_RETAIL,
		RECEIVED_COST,
		TOTAL_ITEMS_RETAIL ,
		TOTAL_ITEMS_COST ,
		MIN_PRES_ITEMS ,
		MIN_PRES_RETAIL,
		MIN_PRES_COST)
    select sysdate,
      1,
      1,
      max(lv1finc.cycle),
      lv1finc.lv1loc_id,
      sum(lv1finc.cubic_meters),
      sum(lv1finc.dsp_sqmeters),
      sum(lv1finc.flr_sqmeters),
      sum(lv1finc.linear_meters),
      sum(lv1finc.used_cubic_meters),
      sum(lv1finc.used_dsp_sqmeters),
      sum(lv1finc.used_linear_meters),
      sum(lv1finc.loss_sales),
      sum(lv1finc.loss_gp),
      sum(lv1finc.proj_sales),
      sum(lv1finc.proj_gp),
      1,
      sum(lv1finc.days_in_period),
      1,
      sum(lv1finc.dpp_dollar),
      sum(lv1finc.dpp_item),
      sum(lv1finc.cost_of_invent),
      sum(lv1finc.dir_cost_of_sales),
      sum(lv1finc.indir_cost_of_sale),
      sum(lv1finc.posit_sales),
      sum(lv1finc.posit_mvmt),
      sum(lv1finc.posit_norm_mvmt),
      sum(lv1finc.count_inc_in_avg),
      sum(lv1finc.total_caps),
      sum(lv1finc.total_units),
      sum(lv1finc.total_items),
      sum(lv1finc.vat),
      sum(lv1finc.supp_total_sales),
      sum(lv1finc.supp_cost_of_sales),
      sum(lv1finc.supp_posit_mvmt),
      sum(lv1finc.supplier_norm_mvmt),
      sum(lv1finc.num_user1),
      sum(lv1finc.num_user2),
      sum(lv1finc.num_user3),
      sum(lv1finc.num_user4),
      avg(lv1finc.num_user5),
      avg(lv1finc.num_user6),
      sum(lv1finc.oh_qty),
      sum(lv1finc.oh_cost),
      sum(lv1finc.oh_retail),
      sum(lv1finc.pog_retail),
      x,
		sum(lv1finc.ALLOC_CUBIC_METERS),
		sum(lv1finc.ALLOC_DSP_SQMETERS),
		sum(lv1finc.ALLOC_FLR_SQMETERS),
		sum(lv1finc.ALLOC_LINEAR_METER),
		sum(lv1finc.POSIT_MVMT_REG ),
		sum(lv1finc.POSIT_SALES_REG),
		sum(lv1finc.POSIT_COST_REG ),
		sum(lv1finc.POSIT_MVMT_PROMO ),
		sum(lv1finc.POSIT_SALES_PROMO),
		sum(lv1finc.POSIT_COST_PROMO ),
		sum(lv1finc.POSIT_MVMT_CLRNC ),
		sum(lv1finc.POSIT_SALES_CLRNC),
		sum(lv1finc.POSIT_COST_CLRNC) ,
		sum(lv1finc.POSIT_MVMT_RETN),
		sum(lv1finc.POSIT_SALES_RETN) ,
		sum(lv1finc.POSIT_COST_RETN),
		sum(lv1finc.INVENTORY_ITEMS),
		sum(lv1finc.INVENTORY_RETAIL) ,
		sum(lv1finc.INVENTORY_COST) ,
		sum(lv1finc.RECEIVED_ITEMS) ,
		sum(lv1finc.RECEIVED_RETAIL),
		sum(lv1finc.RECEIVED_COST),
		sum(lv1finc.TOTAL_ITEMS_RETAIL) ,
		sum(lv1finc.TOTAL_ITEMS_COST) ,
		sum(lv1finc.MIN_PRES_ITEMS ),
		sum(lv1finc.MIN_PRES_RETAIL),
		sum(lv1finc.MIN_PRES_COST)
      from maxdata.lv1finc
            where(lv1finc.cycle||lpad(lv1finc.period,7,0))
			<=(current_cycle_id||lpad(current_period_id,7,0))
      	and(lv1finc.cycle||lpad(lv1finc.period,7,0))
			>=(cycle_id_to_roll_from||lpad(period_id_to_roll_from,7,0))
      group by lv1finc.lv1loc_id;
    update maxdata.lv1roll set
    lv1roll.count_num_prodloc
    =(select count(lv10loc_id) from maxdata.lv10loc
      where lv10loc.lv1loc_id
      =lv1roll.lv1loc_id);
end;

/

  GRANT EXECUTE ON "MAXDATA"."P_GEN_ROLL" TO "MADMAX";
  GRANT EXECUTE ON "MAXDATA"."P_GEN_ROLL" TO "MAXUSER";
