--------------------------------------------------------
--  DDL for Procedure P_GEN_LV3MROLL
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "MAXDATA"."P_GEN_LV3MROLL" 
AS

x integer;
begin
select periods_to_roll into x from maxapp.mmax_config;
insert into maxdata.lv3mrll
     (last_update,
      changed_by_batch,
      category_level,
      ctree_or_loc_id,
      version_id,
      cycle,
      lv3loc_id,
      cubic_meters,
      dsp_sqmeters,
      flr_sqmeters,
      linear_meters,
      used_cubic_meters,
      used_dsp_sqmeters,
      used_linear_meters,
      gm_roii,
      proj_sales,
      proj_gp,
      loss_sales,
      loss_gp,
      cost_of_invent,
      dir_cost_of_sales,
      indir_cost_of_sale,
      days_in_period,
      days_supply,
      dpp_dollar,
      dpp_item,
      posit_sales,
      posit_mvmt,
      posit_norm_mvmt,
      count_num_prodloc,
      count_inc_in_avg,
      total_caps,
      total_items,
      total_units,
      vat,
      supp_total_sales,
      supp_cost_of_sales,
      supp_posit_mvmt,
      supplier_norm_mvmt,
      num_user1,
      num_user2,
      num_user3,
      num_user4,
      num_user5,
      num_user6,
      oh_qty,
      oh_cost,
      oh_retail,
      pog_retail,
      periods_rolled,
/* Added columns on 06/22/1999  Suresh */
		ALLOC_CUBIC_METERS,
		ALLOC_DSP_SQMETERS,
		ALLOC_FLR_SQMETERS,
		ALLOC_LINEAR_METER,
		POSIT_MVMT_REG ,
		POSIT_SALES_REG,
		POSIT_COST_REG ,
		POSIT_MVMT_PROMO ,
		POSIT_SALES_PROMO,
		POSIT_COST_PROMO ,
		POSIT_MVMT_CLRNC ,
		POSIT_SALES_CLRNC,
		POSIT_COST_CLRNC ,
		POSIT_MVMT_RETN,
		POSIT_SALES_RETN ,
		POSIT_COST_RETN,
		INVENTORY_ITEMS,
		INVENTORY_RETAIL ,
		INVENTORY_COST ,
		RECEIVED_ITEMS ,
		RECEIVED_RETAIL,
		RECEIVED_COST,
		TOTAL_ITEMS_RETAIL ,
		TOTAL_ITEMS_COST ,
		MIN_PRES_ITEMS ,
		MIN_PRES_RETAIL,
		MIN_PRES_COST)
 select
      sysdate,
      1,
      category_level,
      lv7mrll.ctree_or_loc_id,
      1,
      max(lv7mrll.cycle),
      lv7loc.lv3loc_id,
      sum(lv7mrll.cubic_meters),
      sum(lv7mrll.dsp_sqmeters),
      sum(lv7mrll.flr_sqmeters),
      sum(lv7mrll.linear_meters),
      sum(lv7mrll.used_cubic_meters),
      sum(lv7mrll.used_dsp_sqmeters),
      sum(lv7mrll.used_linear_meters),
      1,
      sum(lv7mrll.proj_sales),
      sum(lv7mrll.proj_gp),
      sum(lv7mrll.loss_sales),
      sum(lv7mrll.loss_gp),
      sum(lv7mrll.cost_of_invent),
      sum(lv7mrll.dir_cost_of_sales),
      sum(lv7mrll.indir_cost_of_sale),
      sum(lv7mrll.days_in_period),
      1,
      sum(lv7mrll.dpp_dollar),
      sum(lv7mrll.dpp_item),
      sum(lv7mrll.posit_sales),
      sum(lv7mrll.posit_mvmt),
      sum(lv7mrll.posit_norm_mvmt),
      sum(lv7mrll.count_num_prodloc),
      sum(lv7mrll.count_inc_in_avg),
      sum(lv7mrll.total_caps),
      sum(lv7mrll.total_items),
      sum(lv7mrll.total_units),
      sum(lv7mrll.vat),
      sum(lv7mrll.supp_total_sales),
      sum(lv7mrll.supp_cost_of_sales),
      sum(lv7mrll.supp_posit_mvmt),
      sum(lv7mrll.supplier_norm_mvmt),
      sum(lv7mrll.num_user1),
      sum(lv7mrll.num_user2),
      sum(lv7mrll.num_user3),
      sum(lv7mrll.num_user4),
      avg(lv7mrll.num_user5),
      avg(lv7mrll.num_user6),
      sum(lv7mrll.oh_qty),
      sum(lv7mrll.oh_cost),
      sum(lv7mrll.oh_retail),
      sum(lv7mrll.pog_retail),
      x,
		sum(lv7mrll.ALLOC_CUBIC_METERS),
		sum(lv7mrll.ALLOC_DSP_SQMETERS),
		sum(lv7mrll.ALLOC_FLR_SQMETERS),
		sum(lv7mrll.ALLOC_LINEAR_METER),
		sum(lv7mrll.POSIT_MVMT_REG ),
		sum(lv7mrll.POSIT_SALES_REG),
		sum(lv7mrll.POSIT_COST_REG ),
		sum(lv7mrll.POSIT_MVMT_PROMO ),
		sum(lv7mrll.POSIT_SALES_PROMO),
		sum(lv7mrll.POSIT_COST_PROMO ),
		sum(lv7mrll.POSIT_MVMT_CLRNC ),
		sum(lv7mrll.POSIT_SALES_CLRNC),
		sum(lv7mrll.POSIT_COST_CLRNC) ,
		sum(lv7mrll.POSIT_MVMT_RETN),
		sum(lv7mrll.POSIT_SALES_RETN) ,
		sum(lv7mrll.POSIT_COST_RETN),
		sum(lv7mrll.INVENTORY_ITEMS),
		sum(lv7mrll.INVENTORY_RETAIL) ,
		sum(lv7mrll.INVENTORY_COST) ,
		sum(lv7mrll.RECEIVED_ITEMS) ,
		sum(lv7mrll.RECEIVED_RETAIL),
		sum(lv7mrll.RECEIVED_COST),
		sum(lv7mrll.TOTAL_ITEMS_RETAIL) ,
		sum(lv7mrll.TOTAL_ITEMS_COST) ,
		sum(lv7mrll.MIN_PRES_ITEMS ),
		sum(lv7mrll.MIN_PRES_RETAIL),
		sum(lv7mrll.MIN_PRES_COST)
      from  maxdata.lv7mrll,
      maxdata.lv7loc
where lv7mrll.lv7loc_id = lv7loc.lv7loc_id and lv7loc.lv3loc_id IS NOT NULL
group by lv7mrll.ctree_or_loc_id, lv7loc.lv3loc_id, lv7mrll.category_level;
end ;

/

  GRANT EXECUTE ON "MAXDATA"."P_GEN_LV3MROLL" TO "MADMAX";
  GRANT EXECUTE ON "MAXDATA"."P_GEN_LV3MROLL" TO "MAXUSER";
