--------------------------------------------------------
--  DDL for Procedure P_GEN_LV7MROLL
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "MAXDATA"."P_GEN_LV7MROLL" 
AS

x integer;
begin
--%% category level 1
select periods_to_roll into x from maxapp.mmax_config;
insert into maxdata.lv7mrll(last_update,
    changed_by_batch,
    category_level,
    ctree_or_loc_id,
    version_id,
    cycle,
    lv7loc_id,
    cubic_meters,
    dsp_sqmeters,
    flr_sqmeters,
    linear_meters,
    used_cubic_meters,
    used_dsp_sqmeters,
    used_linear_meters,
    gm_roii,
    proj_sales,
    proj_gp,
    loss_sales,
    loss_gp,
    cost_of_invent,
    dir_cost_of_sales,
    indir_cost_of_sale,
    days_in_period,
    days_supply,
    dpp_dollar,
    dpp_item,
    posit_sales,
    posit_mvmt,
    posit_norm_mvmt,
    count_num_prodloc,
    count_inc_in_avg,
    total_caps,
    total_items,
    total_units,
    vat,
    supp_total_sales,
    supp_cost_of_sales,
    supp_posit_mvmt,
    supplier_norm_mvmt,
    num_user1,
    num_user2,
    num_user3,
    num_user4,
    num_user5,num_user6,
    oh_qty,
    oh_cost,
    oh_retail,
    pog_retail,
    periods_rolled,
/* Added columns on 06/22/1999  Suresh */
		ALLOC_CUBIC_METERS,
		ALLOC_DSP_SQMETERS,
		ALLOC_FLR_SQMETERS,
		ALLOC_LINEAR_METER,
		POSIT_MVMT_REG ,
		POSIT_SALES_REG,
		POSIT_COST_REG ,
		POSIT_MVMT_PROMO ,
		POSIT_SALES_PROMO,
		POSIT_COST_PROMO ,
		POSIT_MVMT_CLRNC ,
		POSIT_SALES_CLRNC,
		POSIT_COST_CLRNC ,
		POSIT_MVMT_RETN,
		POSIT_SALES_RETN ,
		POSIT_COST_RETN,
		INVENTORY_ITEMS,
		INVENTORY_RETAIL ,
		INVENTORY_COST ,
		RECEIVED_ITEMS ,
		RECEIVED_RETAIL,
		RECEIVED_COST,
		TOTAL_ITEMS_RETAIL ,
		TOTAL_ITEMS_COST ,
		MIN_PRES_ITEMS ,
		MIN_PRES_RETAIL,
		MIN_PRES_COST)
    select sysdate,
      1,
      1,
      lv10mast.lv1cmast_id,
      1,
      max(lv10roll.cycle),
      lv10roll.live_lv7loc_id,
      sum(lv7loc.height*lv7loc.width*lv7loc.depth),
      sum(lv7loc.height*lv7loc.width),
      sum(lv7loc.depth*lv7loc.width),
      sum(lv7loc.width),
      sum(lv10roll.used_cubic_meters),
      sum(lv10roll.used_dsp_sqmeters),
      sum(lv10roll.used_linear_meters),
      1,
      sum(lv10roll.proj_sales),
      sum(lv10roll.proj_gp),
      sum(lv10roll.loss_sales),
      sum(lv10roll.loss_gp),
      sum(lv10roll.cost_of_invent),
      sum(lv10roll.dir_cost_of_sales),
      sum(lv10roll.indir_cost_of_sale),
      sum(lv10roll.days_in_period),
      1,
      sum(lv10roll.dpp_dollar),
      sum(lv10roll.dpp_item),
      sum(lv10roll.posit_sales),
      sum(lv10roll.posit_mvmt),
      sum(lv10roll.posit_norm_mvmt),
      count(lv10loc.lv10loc_id),
      sum(lv10roll.include_in_avg),
      sum(lv10roll.total_caps),
      sum(lv10roll.total_items),
      sum(lv10roll.total_units),
      sum(lv10roll.vat),
      sum(lv10roll.supp_total_sales),
      sum(lv10roll.supp_cost_of_sales),
      sum(lv10roll.supp_posit_mvmt),
      sum(lv10roll.supplier_norm_mvmt),
      sum(lv10roll.num_user1),
      sum(lv10roll.num_user2),
      sum(lv10roll.num_user3),
      sum(lv10roll.num_user4),
      avg(lv10roll.num_user5),
      avg(lv10roll.num_user6),
      sum(lv10roll.oh_qty),
      sum(lv10roll.oh_cost),
      sum(lv10roll.oh_retail),
      sum(lv10roll.pog_retail),
      x,
		sum(lv10roll.ALLOC_CUBIC_METERS),
		sum(lv10roll.ALLOC_DSP_SQMETERS),
		sum(lv10roll.ALLOC_FLR_SQMETERS),
		sum(lv10roll.ALLOC_LINEAR_METER),
		sum(lv10roll.POSIT_MVMT_REG ),
		sum(lv10roll.POSIT_SALES_REG),
		sum(lv10roll.POSIT_COST_REG ),
		sum(lv10roll.POSIT_MVMT_PROMO ),
		sum(lv10roll.POSIT_SALES_PROMO),
		sum(lv10roll.POSIT_COST_PROMO ),
		sum(lv10roll.POSIT_MVMT_CLRNC ),
		sum(lv10roll.POSIT_SALES_CLRNC),
		sum(lv10roll.POSIT_COST_CLRNC) ,
		sum(lv10roll.POSIT_MVMT_RETN),
		sum(lv10roll.POSIT_SALES_RETN) ,
		sum(lv10roll.POSIT_COST_RETN),
		sum(lv10roll.INVENTORY_ITEMS),
		sum(lv10roll.INVENTORY_RETAIL) ,
		sum(lv10roll.INVENTORY_COST) ,
		sum(lv10roll.RECEIVED_ITEMS) ,
		sum(lv10roll.RECEIVED_RETAIL),
		sum(lv10roll.RECEIVED_COST),
		sum(lv10roll.TOTAL_ITEMS_RETAIL) ,
		sum(lv10roll.TOTAL_ITEMS_COST) ,
		sum(lv10roll.MIN_PRES_ITEMS ),
		sum(lv10roll.MIN_PRES_RETAIL),
		sum(lv10roll.MIN_PRES_COST)
 from maxdata.lv10loc
      ,maxdata.lv10roll
      ,maxdata.lv7loc,maxdata.lv10mast
 where(lv10loc.lv10loc_id=lv10roll.lv10loc_id)
      and(lv7loc.lv7loc_id=lv10roll.live_lv7loc_id)
      and(lv10mast.lv1cmast_id is not null)
      and lv10mast.lv10mast_id = lv10loc.lv10mast_id
group by lv10roll.live_lv7loc_id,
      lv10mast.lv1cmast_id;
--%% category level 2
insert into maxdata.lv7mrll(last_update,
    changed_by_batch,
    category_level,
    ctree_or_loc_id,
    version_id,
    cycle,
    lv7loc_id,
    cubic_meters,
    dsp_sqmeters,
    flr_sqmeters,
    linear_meters,
    used_cubic_meters,
    used_dsp_sqmeters,
    used_linear_meters,
    gm_roii,
    proj_sales,
    proj_gp,
    loss_sales,
    loss_gp,
    cost_of_invent,
    dir_cost_of_sales,
    indir_cost_of_sale,
    days_in_period,
    days_supply,
    dpp_dollar,
    dpp_item,
    posit_sales,
    posit_mvmt,
    posit_norm_mvmt,
    count_num_prodloc,
    count_inc_in_avg,
    total_caps,
    total_items,
    total_units,
    vat,
    supp_total_sales,
    supp_cost_of_sales,
    supp_posit_mvmt,
    supplier_norm_mvmt,
    num_user1,
    num_user2,
    num_user3,
    num_user4,
    num_user5,num_user6,
    oh_qty,
    oh_cost,
    oh_retail,
    pog_retail,
    periods_rolled,
/* Added columns on 06/22/1999  Suresh */
		ALLOC_CUBIC_METERS,
		ALLOC_DSP_SQMETERS,
		ALLOC_FLR_SQMETERS,
		ALLOC_LINEAR_METER,
		POSIT_MVMT_REG ,
		POSIT_SALES_REG,
		POSIT_COST_REG ,
		POSIT_MVMT_PROMO ,
		POSIT_SALES_PROMO,
		POSIT_COST_PROMO ,
		POSIT_MVMT_CLRNC ,
		POSIT_SALES_CLRNC,
		POSIT_COST_CLRNC ,
		POSIT_MVMT_RETN,
		POSIT_SALES_RETN ,
		POSIT_COST_RETN,
		INVENTORY_ITEMS,
		INVENTORY_RETAIL ,
		INVENTORY_COST ,
		RECEIVED_ITEMS ,
		RECEIVED_RETAIL,
		RECEIVED_COST,
		TOTAL_ITEMS_RETAIL ,
		TOTAL_ITEMS_COST ,
		MIN_PRES_ITEMS ,
		MIN_PRES_RETAIL,
		MIN_PRES_COST)
    select sysdate,
      1,
      2,
      lv10mast.lv2ctree_id,
      1,
      max(lv10roll.cycle),
      lv10roll.live_lv7loc_id,
      sum(lv7loc.height*lv7loc.width*lv7loc.depth),
      sum(lv7loc.height*lv7loc.width),
      sum(lv7loc.depth*lv7loc.width),
      sum(lv7loc.width),
      sum(lv10roll.used_cubic_meters),
      sum(lv10roll.used_dsp_sqmeters),
      sum(lv10roll.used_linear_meters),
      1,
      sum(lv10roll.proj_sales),
      sum(lv10roll.proj_gp),
      sum(lv10roll.loss_sales),
      sum(lv10roll.loss_gp),
      sum(lv10roll.cost_of_invent),
      sum(lv10roll.dir_cost_of_sales),
      sum(lv10roll.indir_cost_of_sale),
      sum(lv10roll.days_in_period),
      1,
      sum(lv10roll.dpp_dollar),
      sum(lv10roll.dpp_item),
      sum(lv10roll.posit_sales),
      sum(lv10roll.posit_mvmt),
      sum(lv10roll.posit_norm_mvmt),
      count(lv10loc.lv10loc_id),
      sum(lv10roll.include_in_avg),
      sum(lv10roll.total_caps),
      sum(lv10roll.total_items),
      sum(lv10roll.total_units),
      sum(lv10roll.vat),
      sum(lv10roll.supp_total_sales),
      sum(lv10roll.supp_cost_of_sales),
      sum(lv10roll.supp_posit_mvmt),
      sum(lv10roll.supplier_norm_mvmt),
      sum(lv10roll.num_user1),
      sum(lv10roll.num_user2),
      sum(lv10roll.num_user3),
      sum(lv10roll.num_user4),
      avg(lv10roll.num_user5),
      avg(lv10roll.num_user6),
      sum(lv10roll.oh_qty),
      sum(lv10roll.oh_cost),
      sum(lv10roll.oh_retail),
      sum(lv10roll.pog_retail),
      x,
		sum(lv10roll.ALLOC_CUBIC_METERS),
		sum(lv10roll.ALLOC_DSP_SQMETERS),
		sum(lv10roll.ALLOC_FLR_SQMETERS),
		sum(lv10roll.ALLOC_LINEAR_METER),
		sum(lv10roll.POSIT_MVMT_REG ),
		sum(lv10roll.POSIT_SALES_REG),
		sum(lv10roll.POSIT_COST_REG ),
		sum(lv10roll.POSIT_MVMT_PROMO ),
		sum(lv10roll.POSIT_SALES_PROMO),
		sum(lv10roll.POSIT_COST_PROMO ),
		sum(lv10roll.POSIT_MVMT_CLRNC ),
		sum(lv10roll.POSIT_SALES_CLRNC),
		sum(lv10roll.POSIT_COST_CLRNC) ,
		sum(lv10roll.POSIT_MVMT_RETN),
		sum(lv10roll.POSIT_SALES_RETN) ,
		sum(lv10roll.POSIT_COST_RETN),
		sum(lv10roll.INVENTORY_ITEMS),
		sum(lv10roll.INVENTORY_RETAIL) ,
		sum(lv10roll.INVENTORY_COST) ,
		sum(lv10roll.RECEIVED_ITEMS) ,
		sum(lv10roll.RECEIVED_RETAIL),
		sum(lv10roll.RECEIVED_COST),
		sum(lv10roll.TOTAL_ITEMS_RETAIL) ,
		sum(lv10roll.TOTAL_ITEMS_COST) ,
		sum(lv10roll.MIN_PRES_ITEMS ),
		sum(lv10roll.MIN_PRES_RETAIL),
		sum(lv10roll.MIN_PRES_COST)
 from maxdata.lv10loc
      ,maxdata.lv10roll
      ,maxdata.lv7loc,maxdata.lv10mast
 where(lv10loc.lv10loc_id=lv10roll.lv10loc_id)
      and(lv7loc.lv7loc_id=lv10roll.live_lv7loc_id)
      and(lv10mast.lv2ctree_id is not null)
      and lv10mast.lv10mast_id = lv10loc.lv10mast_id
group by lv10roll.live_lv7loc_id,
      lv10mast.lv2ctree_id;
--%% category level 3
insert into maxdata.lv7mrll(last_update,
    changed_by_batch,
    category_level,
    ctree_or_loc_id,
    version_id,
    cycle,
    lv7loc_id,
    cubic_meters,
    dsp_sqmeters,
    flr_sqmeters,
    linear_meters,
    used_cubic_meters,
    used_dsp_sqmeters,
    used_linear_meters,
    gm_roii,
    proj_sales,
    proj_gp,
    loss_sales,
    loss_gp,
    cost_of_invent,
    dir_cost_of_sales,
    indir_cost_of_sale,
    days_in_period,
    days_supply,
    dpp_dollar,
    dpp_item,
    posit_sales,
    posit_mvmt,
    posit_norm_mvmt,
    count_num_prodloc,
    count_inc_in_avg,
    total_caps,
    total_items,
    total_units,
    vat,
    supp_total_sales,
    supp_cost_of_sales,
    supp_posit_mvmt,
    supplier_norm_mvmt,
    num_user1,
    num_user2,
    num_user3,
    num_user4,
    num_user5,num_user6,
    oh_qty,
    oh_cost,
    oh_retail,
    pog_retail,
    periods_rolled,
/* Added columns on 06/22/1999  Suresh */
		ALLOC_CUBIC_METERS,
		ALLOC_DSP_SQMETERS,
		ALLOC_FLR_SQMETERS,
		ALLOC_LINEAR_METER,
		POSIT_MVMT_REG ,
		POSIT_SALES_REG,
		POSIT_COST_REG ,
		POSIT_MVMT_PROMO ,
		POSIT_SALES_PROMO,
		POSIT_COST_PROMO ,
		POSIT_MVMT_CLRNC ,
		POSIT_SALES_CLRNC,
		POSIT_COST_CLRNC ,
		POSIT_MVMT_RETN,
		POSIT_SALES_RETN ,
		POSIT_COST_RETN,
		INVENTORY_ITEMS,
		INVENTORY_RETAIL ,
		INVENTORY_COST ,
		RECEIVED_ITEMS ,
		RECEIVED_RETAIL,
		RECEIVED_COST,
		TOTAL_ITEMS_RETAIL ,
		TOTAL_ITEMS_COST ,
		MIN_PRES_ITEMS ,
		MIN_PRES_RETAIL,
		MIN_PRES_COST)
    select sysdate,
      1,
      3,
      lv10mast.lv3ctree_id,
      1,
      max(lv10roll.cycle),
      lv10roll.live_lv7loc_id,
      sum(lv7loc.height*lv7loc.width*lv7loc.depth),
      sum(lv7loc.height*lv7loc.width),
      sum(lv7loc.depth*lv7loc.width),
      sum(lv7loc.width),
      sum(lv10roll.used_cubic_meters),
      sum(lv10roll.used_dsp_sqmeters),
      sum(lv10roll.used_linear_meters),
      1,
      sum(lv10roll.proj_sales),
      sum(lv10roll.proj_gp),
      sum(lv10roll.loss_sales),
      sum(lv10roll.loss_gp),
      sum(lv10roll.cost_of_invent),
      sum(lv10roll.dir_cost_of_sales),
      sum(lv10roll.indir_cost_of_sale),
      sum(lv10roll.days_in_period),
      1,
      sum(lv10roll.dpp_dollar),
      sum(lv10roll.dpp_item),
      sum(lv10roll.posit_sales),
      sum(lv10roll.posit_mvmt),
      sum(lv10roll.posit_norm_mvmt),
      count(lv10loc.lv10loc_id),
      sum(lv10roll.include_in_avg),
      sum(lv10roll.total_caps),
      sum(lv10roll.total_items),
      sum(lv10roll.total_units),
      sum(lv10roll.vat),
      sum(lv10roll.supp_total_sales),
      sum(lv10roll.supp_cost_of_sales),
      sum(lv10roll.supp_posit_mvmt),
      sum(lv10roll.supplier_norm_mvmt),
      sum(lv10roll.num_user1),
      sum(lv10roll.num_user2),
      sum(lv10roll.num_user3),
      sum(lv10roll.num_user4),
      avg(lv10roll.num_user5),
      avg(lv10roll.num_user6),
      sum(lv10roll.oh_qty),
      sum(lv10roll.oh_cost),
      sum(lv10roll.oh_retail),
      sum(lv10roll.pog_retail),
      x,
		sum(lv10roll.ALLOC_CUBIC_METERS),
		sum(lv10roll.ALLOC_DSP_SQMETERS),
		sum(lv10roll.ALLOC_FLR_SQMETERS),
		sum(lv10roll.ALLOC_LINEAR_METER),
		sum(lv10roll.POSIT_MVMT_REG ),
		sum(lv10roll.POSIT_SALES_REG),
		sum(lv10roll.POSIT_COST_REG ),
		sum(lv10roll.POSIT_MVMT_PROMO ),
		sum(lv10roll.POSIT_SALES_PROMO),
		sum(lv10roll.POSIT_COST_PROMO ),
		sum(lv10roll.POSIT_MVMT_CLRNC ),
		sum(lv10roll.POSIT_SALES_CLRNC),
		sum(lv10roll.POSIT_COST_CLRNC) ,
		sum(lv10roll.POSIT_MVMT_RETN),
		sum(lv10roll.POSIT_SALES_RETN) ,
		sum(lv10roll.POSIT_COST_RETN),
		sum(lv10roll.INVENTORY_ITEMS),
		sum(lv10roll.INVENTORY_RETAIL) ,
		sum(lv10roll.INVENTORY_COST) ,
		sum(lv10roll.RECEIVED_ITEMS) ,
		sum(lv10roll.RECEIVED_RETAIL),
		sum(lv10roll.RECEIVED_COST),
		sum(lv10roll.TOTAL_ITEMS_RETAIL) ,
		sum(lv10roll.TOTAL_ITEMS_COST) ,
		sum(lv10roll.MIN_PRES_ITEMS ),
		sum(lv10roll.MIN_PRES_RETAIL),
		sum(lv10roll.MIN_PRES_COST)
 from maxdata.lv10loc
      ,maxdata.lv10roll
      ,maxdata.lv7loc,maxdata.lv10mast
 where(lv10loc.lv10loc_id=lv10roll.lv10loc_id)
      and(lv7loc.lv7loc_id=lv10roll.live_lv7loc_id)
      and(lv10mast.lv3ctree_id is not null)
      and lv10mast.lv10mast_id = lv10loc.lv10mast_id
group by lv10roll.live_lv7loc_id,
      lv10mast.lv3ctree_id;
--%% category level 4
insert into maxdata.lv7mrll(last_update,
    changed_by_batch,
    category_level,
    ctree_or_loc_id,
    version_id,
    cycle,
    lv7loc_id,
    cubic_meters,
    dsp_sqmeters,
    flr_sqmeters,
    linear_meters,
    used_cubic_meters,
    used_dsp_sqmeters,
    used_linear_meters,
    gm_roii,
    proj_sales,
    proj_gp,
    loss_sales,
    loss_gp,
    cost_of_invent,
    dir_cost_of_sales,
    indir_cost_of_sale,
    days_in_period,
    days_supply,
    dpp_dollar,
    dpp_item,
    posit_sales,
    posit_mvmt,
    posit_norm_mvmt,
    count_num_prodloc,
    count_inc_in_avg,
    total_caps,
    total_items,
    total_units,
    vat,
    supp_total_sales,
    supp_cost_of_sales,
    supp_posit_mvmt,
    supplier_norm_mvmt,
    num_user1,
    num_user2,
    num_user3,
    num_user4,
    num_user5,num_user6,
    oh_qty,
    oh_cost,
    oh_retail,
    pog_retail,
    periods_rolled,
/* Added columns on 06/22/1999  Suresh */
		ALLOC_CUBIC_METERS,
		ALLOC_DSP_SQMETERS,
		ALLOC_FLR_SQMETERS,
		ALLOC_LINEAR_METER,
		POSIT_MVMT_REG ,
		POSIT_SALES_REG,
		POSIT_COST_REG ,
		POSIT_MVMT_PROMO ,
		POSIT_SALES_PROMO,
		POSIT_COST_PROMO ,
		POSIT_MVMT_CLRNC ,
		POSIT_SALES_CLRNC,
		POSIT_COST_CLRNC ,
		POSIT_MVMT_RETN,
		POSIT_SALES_RETN ,
		POSIT_COST_RETN,
		INVENTORY_ITEMS,
		INVENTORY_RETAIL ,
		INVENTORY_COST ,
		RECEIVED_ITEMS ,
		RECEIVED_RETAIL,
		RECEIVED_COST,
		TOTAL_ITEMS_RETAIL ,
		TOTAL_ITEMS_COST ,
		MIN_PRES_ITEMS ,
		MIN_PRES_RETAIL,
		MIN_PRES_COST)
    select sysdate,
      1,
      4,
      lv10mast.lv4ctree_id,
      1,
      max(lv10roll.cycle),
      lv10roll.live_lv7loc_id,
      sum(lv7loc.height*lv7loc.width*lv7loc.depth),
      sum(lv7loc.height*lv7loc.width),
      sum(lv7loc.depth*lv7loc.width),
      sum(lv7loc.width),
      sum(lv10roll.used_cubic_meters),
      sum(lv10roll.used_dsp_sqmeters),
      sum(lv10roll.used_linear_meters),
      1,
      sum(lv10roll.proj_sales),
      sum(lv10roll.proj_gp),
      sum(lv10roll.loss_sales),
      sum(lv10roll.loss_gp),
      sum(lv10roll.cost_of_invent),
      sum(lv10roll.dir_cost_of_sales),
      sum(lv10roll.indir_cost_of_sale),
      sum(lv10roll.days_in_period),
      1,
      sum(lv10roll.dpp_dollar),
      sum(lv10roll.dpp_item),
      sum(lv10roll.posit_sales),
      sum(lv10roll.posit_mvmt),
      sum(lv10roll.posit_norm_mvmt),
      count(lv10loc.lv10loc_id),
      sum(lv10roll.include_in_avg),
      sum(lv10roll.total_caps),
      sum(lv10roll.total_items),
      sum(lv10roll.total_units),
      sum(lv10roll.vat),
      sum(lv10roll.supp_total_sales),
      sum(lv10roll.supp_cost_of_sales),
      sum(lv10roll.supp_posit_mvmt),
      sum(lv10roll.supplier_norm_mvmt),
      sum(lv10roll.num_user1),
      sum(lv10roll.num_user2),
      sum(lv10roll.num_user3),
      sum(lv10roll.num_user4),
      avg(lv10roll.num_user5),
      avg(lv10roll.num_user6),
      sum(lv10roll.oh_qty),
      sum(lv10roll.oh_cost),
      sum(lv10roll.oh_retail),
      sum(lv10roll.pog_retail),
      x,
		sum(lv10roll.ALLOC_CUBIC_METERS),
		sum(lv10roll.ALLOC_DSP_SQMETERS),
		sum(lv10roll.ALLOC_FLR_SQMETERS),
		sum(lv10roll.ALLOC_LINEAR_METER),
		sum(lv10roll.POSIT_MVMT_REG ),
		sum(lv10roll.POSIT_SALES_REG),
		sum(lv10roll.POSIT_COST_REG ),
		sum(lv10roll.POSIT_MVMT_PROMO ),
		sum(lv10roll.POSIT_SALES_PROMO),
		sum(lv10roll.POSIT_COST_PROMO ),
		sum(lv10roll.POSIT_MVMT_CLRNC ),
		sum(lv10roll.POSIT_SALES_CLRNC),
		sum(lv10roll.POSIT_COST_CLRNC) ,
		sum(lv10roll.POSIT_MVMT_RETN),
		sum(lv10roll.POSIT_SALES_RETN) ,
		sum(lv10roll.POSIT_COST_RETN),
		sum(lv10roll.INVENTORY_ITEMS),
		sum(lv10roll.INVENTORY_RETAIL) ,
		sum(lv10roll.INVENTORY_COST) ,
		sum(lv10roll.RECEIVED_ITEMS) ,
		sum(lv10roll.RECEIVED_RETAIL),
		sum(lv10roll.RECEIVED_COST),
		sum(lv10roll.TOTAL_ITEMS_RETAIL) ,
		sum(lv10roll.TOTAL_ITEMS_COST) ,
		sum(lv10roll.MIN_PRES_ITEMS ),
		sum(lv10roll.MIN_PRES_RETAIL),
		sum(lv10roll.MIN_PRES_COST)
 from maxdata.lv10loc
      ,maxdata.lv10roll
      ,maxdata.lv7loc,maxdata.lv10mast
 where(lv10loc.lv10loc_id=lv10roll.lv10loc_id)
      and(lv7loc.lv7loc_id=lv10roll.live_lv7loc_id)
      and(lv10mast.lv4ctree_id is not null)
      and lv10mast.lv10mast_id = lv10loc.lv10mast_id
group by lv10roll.live_lv7loc_id,
      lv10mast.lv4ctree_id;
--%% category level 5
insert into maxdata.lv7mrll(last_update,
    changed_by_batch,
    category_level,
    ctree_or_loc_id,
    version_id,
    cycle,
    lv7loc_id,
    cubic_meters,
    dsp_sqmeters,
    flr_sqmeters,
    linear_meters,
    used_cubic_meters,
    used_dsp_sqmeters,
    used_linear_meters,
    gm_roii,
    proj_sales,
    proj_gp,
    loss_sales,
    loss_gp,
    cost_of_invent,
    dir_cost_of_sales,
    indir_cost_of_sale,
    days_in_period,
    days_supply,
    dpp_dollar,
    dpp_item,
    posit_sales,
    posit_mvmt,
    posit_norm_mvmt,
    count_num_prodloc,
    count_inc_in_avg,
    total_caps,
    total_items,
    total_units,
    vat,
    supp_total_sales,
    supp_cost_of_sales,
    supp_posit_mvmt,
    supplier_norm_mvmt,
    num_user1,
    num_user2,
    num_user3,
    num_user4,
    num_user5,num_user6,
    oh_qty,
    oh_cost,
    oh_retail,
    pog_retail,
    periods_rolled,
/* Added columns on 06/22/1999  Suresh */
		ALLOC_CUBIC_METERS,
		ALLOC_DSP_SQMETERS,
		ALLOC_FLR_SQMETERS,
		ALLOC_LINEAR_METER,
		POSIT_MVMT_REG ,
		POSIT_SALES_REG,
		POSIT_COST_REG ,
		POSIT_MVMT_PROMO ,
		POSIT_SALES_PROMO,
		POSIT_COST_PROMO ,
		POSIT_MVMT_CLRNC ,
		POSIT_SALES_CLRNC,
		POSIT_COST_CLRNC ,
		POSIT_MVMT_RETN,
		POSIT_SALES_RETN ,
		POSIT_COST_RETN,
		INVENTORY_ITEMS,
		INVENTORY_RETAIL ,
		INVENTORY_COST ,
		RECEIVED_ITEMS ,
		RECEIVED_RETAIL,
		RECEIVED_COST,
		TOTAL_ITEMS_RETAIL ,
		TOTAL_ITEMS_COST ,
		MIN_PRES_ITEMS ,
		MIN_PRES_RETAIL,
		MIN_PRES_COST)
    select sysdate,
      1,
      5,
      lv10mast.lv5ctree_id,
      1,
      max(lv10roll.cycle),
      lv10roll.live_lv7loc_id,
      sum(lv7loc.height*lv7loc.width*lv7loc.depth),
      sum(lv7loc.height*lv7loc.width),
      sum(lv7loc.depth*lv7loc.width),
      sum(lv7loc.width),
      sum(lv10roll.used_cubic_meters),
      sum(lv10roll.used_dsp_sqmeters),
      sum(lv10roll.used_linear_meters),
      1,
      sum(lv10roll.proj_sales),
      sum(lv10roll.proj_gp),
      sum(lv10roll.loss_sales),
      sum(lv10roll.loss_gp),
      sum(lv10roll.cost_of_invent),
      sum(lv10roll.dir_cost_of_sales),
      sum(lv10roll.indir_cost_of_sale),
      sum(lv10roll.days_in_period),
      1,
      sum(lv10roll.dpp_dollar),
      sum(lv10roll.dpp_item),
      sum(lv10roll.posit_sales),
      sum(lv10roll.posit_mvmt),
      sum(lv10roll.posit_norm_mvmt),
      count(lv10loc.lv10loc_id),
      sum(lv10roll.include_in_avg),
      sum(lv10roll.total_caps),
      sum(lv10roll.total_items),
      sum(lv10roll.total_units),
      sum(lv10roll.vat),
      sum(lv10roll.supp_total_sales),
      sum(lv10roll.supp_cost_of_sales),
      sum(lv10roll.supp_posit_mvmt),
      sum(lv10roll.supplier_norm_mvmt),
      sum(lv10roll.num_user1),
      sum(lv10roll.num_user2),
      sum(lv10roll.num_user3),
      sum(lv10roll.num_user4),
      avg(lv10roll.num_user5),
      avg(lv10roll.num_user6),
      sum(lv10roll.oh_qty),
      sum(lv10roll.oh_cost),
      sum(lv10roll.oh_retail),
      sum(lv10roll.pog_retail),
      x,
		sum(lv10roll.ALLOC_CUBIC_METERS),
		sum(lv10roll.ALLOC_DSP_SQMETERS),
		sum(lv10roll.ALLOC_FLR_SQMETERS),
		sum(lv10roll.ALLOC_LINEAR_METER),
		sum(lv10roll.POSIT_MVMT_REG ),
		sum(lv10roll.POSIT_SALES_REG),
		sum(lv10roll.POSIT_COST_REG ),
		sum(lv10roll.POSIT_MVMT_PROMO ),
		sum(lv10roll.POSIT_SALES_PROMO),
		sum(lv10roll.POSIT_COST_PROMO ),
		sum(lv10roll.POSIT_MVMT_CLRNC ),
		sum(lv10roll.POSIT_SALES_CLRNC),
		sum(lv10roll.POSIT_COST_CLRNC) ,
		sum(lv10roll.POSIT_MVMT_RETN),
		sum(lv10roll.POSIT_SALES_RETN) ,
		sum(lv10roll.POSIT_COST_RETN),
		sum(lv10roll.INVENTORY_ITEMS),
		sum(lv10roll.INVENTORY_RETAIL) ,
		sum(lv10roll.INVENTORY_COST) ,
		sum(lv10roll.RECEIVED_ITEMS) ,
		sum(lv10roll.RECEIVED_RETAIL),
		sum(lv10roll.RECEIVED_COST),
		sum(lv10roll.TOTAL_ITEMS_RETAIL) ,
		sum(lv10roll.TOTAL_ITEMS_COST) ,
		sum(lv10roll.MIN_PRES_ITEMS ),
		sum(lv10roll.MIN_PRES_RETAIL),
		sum(lv10roll.MIN_PRES_COST)
 from maxdata.lv10loc
      ,maxdata.lv10roll
      ,maxdata.lv7loc,maxdata.lv10mast
 where(lv10loc.lv10loc_id=lv10roll.lv10loc_id)
      and(lv7loc.lv7loc_id=lv10roll.live_lv7loc_id)
      and(lv10mast.lv5ctree_id is not null)
      and lv10mast.lv10mast_id = lv10loc.lv10mast_id
group by lv10roll.live_lv7loc_id,
      lv10mast.lv5ctree_id;
--%% category level 6
insert into maxdata.lv7mrll(last_update,
    changed_by_batch,
    category_level,
    ctree_or_loc_id,
    version_id,
    cycle,
    lv7loc_id,
    cubic_meters,
    dsp_sqmeters,
    flr_sqmeters,
    linear_meters,
    used_cubic_meters,
    used_dsp_sqmeters,
    used_linear_meters,
    gm_roii,
    proj_sales,
    proj_gp,
    loss_sales,
    loss_gp,
    cost_of_invent,
    dir_cost_of_sales,
    indir_cost_of_sale,
    days_in_period,
    days_supply,
    dpp_dollar,
    dpp_item,
    posit_sales,
    posit_mvmt,
    posit_norm_mvmt,
    count_num_prodloc,
    count_inc_in_avg,
    total_caps,
    total_items,
    total_units,
    vat,
    supp_total_sales,
    supp_cost_of_sales,
    supp_posit_mvmt,
    supplier_norm_mvmt,
    num_user1,
    num_user2,
    num_user3,
    num_user4,
    num_user5,num_user6,
    oh_qty,
    oh_cost,
    oh_retail,
    pog_retail,
    periods_rolled,
/* Added columns on 06/22/1999  Suresh */
		ALLOC_CUBIC_METERS,
		ALLOC_DSP_SQMETERS,
		ALLOC_FLR_SQMETERS,
		ALLOC_LINEAR_METER,
		POSIT_MVMT_REG ,
		POSIT_SALES_REG,
		POSIT_COST_REG ,
		POSIT_MVMT_PROMO ,
		POSIT_SALES_PROMO,
		POSIT_COST_PROMO ,
		POSIT_MVMT_CLRNC ,
		POSIT_SALES_CLRNC,
		POSIT_COST_CLRNC ,
		POSIT_MVMT_RETN,
		POSIT_SALES_RETN ,
		POSIT_COST_RETN,
		INVENTORY_ITEMS,
		INVENTORY_RETAIL ,
		INVENTORY_COST ,
		RECEIVED_ITEMS ,
		RECEIVED_RETAIL,
		RECEIVED_COST,
		TOTAL_ITEMS_RETAIL ,
		TOTAL_ITEMS_COST ,
		MIN_PRES_ITEMS ,
		MIN_PRES_RETAIL,
		MIN_PRES_COST)
    select sysdate,
      1,
      6,
      lv10mast.lv6ctree_id,
      1,
      max(lv10roll.cycle),
      lv10roll.live_lv7loc_id,
      sum(lv7loc.height*lv7loc.width*lv7loc.depth),
      sum(lv7loc.height*lv7loc.width),
      sum(lv7loc.depth*lv7loc.width),
      sum(lv7loc.width),
      sum(lv10roll.used_cubic_meters),
      sum(lv10roll.used_dsp_sqmeters),
      sum(lv10roll.used_linear_meters),
      1,
      sum(lv10roll.proj_sales),
      sum(lv10roll.proj_gp),
      sum(lv10roll.loss_sales),
      sum(lv10roll.loss_gp),
      sum(lv10roll.cost_of_invent),
      sum(lv10roll.dir_cost_of_sales),
      sum(lv10roll.indir_cost_of_sale),
      sum(lv10roll.days_in_period),
      1,
      sum(lv10roll.dpp_dollar),
      sum(lv10roll.dpp_item),
      sum(lv10roll.posit_sales),
      sum(lv10roll.posit_mvmt),
      sum(lv10roll.posit_norm_mvmt),
      count(lv10loc.lv10loc_id),
      sum(lv10roll.include_in_avg),
      sum(lv10roll.total_caps),
      sum(lv10roll.total_items),
      sum(lv10roll.total_units),
      sum(lv10roll.vat),
      sum(lv10roll.supp_total_sales),
      sum(lv10roll.supp_cost_of_sales),
      sum(lv10roll.supp_posit_mvmt),
      sum(lv10roll.supplier_norm_mvmt),
      sum(lv10roll.num_user1),
      sum(lv10roll.num_user2),
      sum(lv10roll.num_user3),
      sum(lv10roll.num_user4),
      avg(lv10roll.num_user5),
      avg(lv10roll.num_user6),
      sum(lv10roll.oh_qty),
      sum(lv10roll.oh_cost),
      sum(lv10roll.oh_retail),
      sum(lv10roll.pog_retail),
      x,
		sum(lv10roll.ALLOC_CUBIC_METERS),
		sum(lv10roll.ALLOC_DSP_SQMETERS),
		sum(lv10roll.ALLOC_FLR_SQMETERS),
		sum(lv10roll.ALLOC_LINEAR_METER),
		sum(lv10roll.POSIT_MVMT_REG ),
		sum(lv10roll.POSIT_SALES_REG),
		sum(lv10roll.POSIT_COST_REG ),
		sum(lv10roll.POSIT_MVMT_PROMO ),
		sum(lv10roll.POSIT_SALES_PROMO),
		sum(lv10roll.POSIT_COST_PROMO ),
		sum(lv10roll.POSIT_MVMT_CLRNC ),
		sum(lv10roll.POSIT_SALES_CLRNC),
		sum(lv10roll.POSIT_COST_CLRNC) ,
		sum(lv10roll.POSIT_MVMT_RETN),
		sum(lv10roll.POSIT_SALES_RETN) ,
		sum(lv10roll.POSIT_COST_RETN),
		sum(lv10roll.INVENTORY_ITEMS),
		sum(lv10roll.INVENTORY_RETAIL) ,
		sum(lv10roll.INVENTORY_COST) ,
		sum(lv10roll.RECEIVED_ITEMS) ,
		sum(lv10roll.RECEIVED_RETAIL),
		sum(lv10roll.RECEIVED_COST),
		sum(lv10roll.TOTAL_ITEMS_RETAIL) ,
		sum(lv10roll.TOTAL_ITEMS_COST) ,
		sum(lv10roll.MIN_PRES_ITEMS ),
		sum(lv10roll.MIN_PRES_RETAIL),
		sum(lv10roll.MIN_PRES_COST)
 from maxdata.lv10loc
      ,maxdata.lv10roll
      ,maxdata.lv7loc,maxdata.lv10mast
 where(lv10loc.lv10loc_id=lv10roll.lv10loc_id)
      and(lv7loc.lv7loc_id=lv10roll.live_lv7loc_id)
      and(lv10mast.lv6ctree_id is not null)
       and lv10mast.lv10mast_id = lv10loc.lv10mast_id
group by lv10roll.live_lv7loc_id,
      lv10mast.lv6ctree_id;

/* Alloc_xxxx columns and addtional columns are added  - 08/09/1999 Suresh*/

--%% category level 7
insert into maxdata.lv7mrll(last_update,
    changed_by_batch,
    category_level,
    ctree_or_loc_id,
    version_id,
    cycle,
    lv7loc_id,
    cubic_meters,
    dsp_sqmeters,
    flr_sqmeters,
    linear_meters,
    used_cubic_meters,
    used_dsp_sqmeters,
    used_linear_meters,
    gm_roii,
    proj_sales,
    proj_gp,
    loss_sales,
    loss_gp,
    cost_of_invent,
    dir_cost_of_sales,
    indir_cost_of_sale,
    days_in_period,
    days_supply,
    dpp_dollar,
    dpp_item,
    posit_sales,
    posit_mvmt,
    posit_norm_mvmt,
    count_num_prodloc,
    count_inc_in_avg,
    total_caps,
    total_items,
    total_units,
    vat,
    supp_total_sales,
    supp_cost_of_sales,
    supp_posit_mvmt,
    supplier_norm_mvmt,
    num_user1,
    num_user2,
    num_user3,
    num_user4,
    num_user5,num_user6,
    oh_qty,
    oh_cost,
    oh_retail,
    pog_retail,
    periods_rolled,
	/* Added columns on 06/22/1999  Suresh */
		ALLOC_CUBIC_METERS,
		ALLOC_DSP_SQMETERS,
		ALLOC_FLR_SQMETERS,
		ALLOC_LINEAR_METER,
		POSIT_MVMT_REG ,
		POSIT_SALES_REG,
		POSIT_COST_REG ,
		POSIT_MVMT_PROMO ,
		POSIT_SALES_PROMO,
		POSIT_COST_PROMO ,
		POSIT_MVMT_CLRNC ,
		POSIT_SALES_CLRNC,
		POSIT_COST_CLRNC ,
		POSIT_MVMT_RETN,
		POSIT_SALES_RETN ,
		POSIT_COST_RETN,
		INVENTORY_ITEMS,
		INVENTORY_RETAIL ,
		INVENTORY_COST ,
		RECEIVED_ITEMS ,
		RECEIVED_RETAIL,
		RECEIVED_COST,
		TOTAL_ITEMS_RETAIL ,
		TOTAL_ITEMS_COST ,
		MIN_PRES_ITEMS ,
		MIN_PRES_RETAIL,
		MIN_PRES_COST)
    select sysdate,
      1,
      7,
      lv10mast.lv7ctree_id,
      1,
      max(lv10roll.cycle),
      lv10roll.live_lv7loc_id,
      sum(lv7loc.height*lv7loc.width*lv7loc.depth),
      sum(lv7loc.height*lv7loc.width),
      sum(lv7loc.depth*lv7loc.width),
      sum(lv7loc.width),
      sum(lv10roll.used_cubic_meters),
      sum(lv10roll.used_dsp_sqmeters),
      sum(lv10roll.used_linear_meters),
      1,
      sum(lv10roll.proj_sales),
      sum(lv10roll.proj_gp),
      sum(lv10roll.loss_sales),
      sum(lv10roll.loss_gp),
      sum(lv10roll.cost_of_invent),
      sum(lv10roll.dir_cost_of_sales),
      sum(lv10roll.indir_cost_of_sale),
      sum(lv10roll.days_in_period),
      1,
      sum(lv10roll.dpp_dollar),
      sum(lv10roll.dpp_item),
      sum(lv10roll.posit_sales),
      sum(lv10roll.posit_mvmt),
      sum(lv10roll.posit_norm_mvmt),
      count(lv10loc.lv10loc_id),
      sum(lv10roll.include_in_avg),
      sum(lv10roll.total_caps),
      sum(lv10roll.total_items),
      sum(lv10roll.total_units),
      sum(lv10roll.vat),
      sum(lv10roll.supp_total_sales),
      sum(lv10roll.supp_cost_of_sales),
      sum(lv10roll.supp_posit_mvmt),
      sum(lv10roll.supplier_norm_mvmt),
      sum(lv10roll.num_user1),
      sum(lv10roll.num_user2),
      sum(lv10roll.num_user3),
      sum(lv10roll.num_user4),
      avg(lv10roll.num_user5),
      avg(lv10roll.num_user6),
      sum(lv10roll.oh_qty),
      sum(lv10roll.oh_cost),
      sum(lv10roll.oh_retail),
      sum(lv10roll.pog_retail),
      x,
		sum(lv10roll.ALLOC_CUBIC_METERS),
		sum(lv10roll.ALLOC_DSP_SQMETERS),
		sum(lv10roll.ALLOC_FLR_SQMETERS),
		sum(lv10roll.ALLOC_LINEAR_METER),
		sum(lv10roll.POSIT_MVMT_REG ),
		sum(lv10roll.POSIT_SALES_REG),
		sum(lv10roll.POSIT_COST_REG ),
		sum(lv10roll.POSIT_MVMT_PROMO ),
		sum(lv10roll.POSIT_SALES_PROMO),
		sum(lv10roll.POSIT_COST_PROMO ),
		sum(lv10roll.POSIT_MVMT_CLRNC ),
		sum(lv10roll.POSIT_SALES_CLRNC),
		sum(lv10roll.POSIT_COST_CLRNC) ,
		sum(lv10roll.POSIT_MVMT_RETN),
		sum(lv10roll.POSIT_SALES_RETN) ,
		sum(lv10roll.POSIT_COST_RETN),
		sum(lv10roll.INVENTORY_ITEMS),
		sum(lv10roll.INVENTORY_RETAIL) ,
		sum(lv10roll.INVENTORY_COST) ,
		sum(lv10roll.RECEIVED_ITEMS) ,
		sum(lv10roll.RECEIVED_RETAIL),
		sum(lv10roll.RECEIVED_COST),
		sum(lv10roll.TOTAL_ITEMS_RETAIL) ,
		sum(lv10roll.TOTAL_ITEMS_COST) ,
		sum(lv10roll.MIN_PRES_ITEMS ),
		sum(lv10roll.MIN_PRES_RETAIL),
		sum(lv10roll.MIN_PRES_COST)
 from maxdata.lv10loc
      ,maxdata.lv10roll
      ,maxdata.lv7loc,maxdata.lv10mast
 where(lv10loc.lv10loc_id=lv10roll.lv10loc_id)
      and(lv7loc.lv7loc_id=lv10roll.live_lv7loc_id)
      and(lv10mast.lv7ctree_id is not null)
       and lv10mast.lv10mast_id = lv10loc.lv10mast_id
group by lv10roll.live_lv7loc_id,
      lv10mast.lv7ctree_id;

--%% category level 8
insert into maxdata.lv7mrll(last_update,
    changed_by_batch,
    category_level,
    ctree_or_loc_id,
    version_id,
    cycle,
    lv7loc_id,
    cubic_meters,
    dsp_sqmeters,
    flr_sqmeters,
    linear_meters,
    used_cubic_meters,
    used_dsp_sqmeters,
    used_linear_meters,
    gm_roii,
    proj_sales,
    proj_gp,
    loss_sales,
    loss_gp,
    cost_of_invent,
    dir_cost_of_sales,
    indir_cost_of_sale,
    days_in_period,
    days_supply,
    dpp_dollar,
    dpp_item,
    posit_sales,
    posit_mvmt,
    posit_norm_mvmt,
    count_num_prodloc,
    count_inc_in_avg,
    total_caps,
    total_items,
    total_units,
    vat,
    supp_total_sales,
    supp_cost_of_sales,
    supp_posit_mvmt,
    supplier_norm_mvmt,
    num_user1,
    num_user2,
    num_user3,
    num_user4,
    num_user5,num_user6,
    oh_qty,
    oh_cost,
    oh_retail,
    pog_retail,
    periods_rolled,
/* Added columns on 06/22/1999  Suresh */
		ALLOC_CUBIC_METERS,
		ALLOC_DSP_SQMETERS,
		ALLOC_FLR_SQMETERS,
		ALLOC_LINEAR_METER,
		POSIT_MVMT_REG ,
		POSIT_SALES_REG,
		POSIT_COST_REG ,
		POSIT_MVMT_PROMO ,
		POSIT_SALES_PROMO,
		POSIT_COST_PROMO ,
		POSIT_MVMT_CLRNC ,
		POSIT_SALES_CLRNC,
		POSIT_COST_CLRNC ,
		POSIT_MVMT_RETN,
		POSIT_SALES_RETN ,
		POSIT_COST_RETN,
		INVENTORY_ITEMS,
		INVENTORY_RETAIL ,
		INVENTORY_COST ,
		RECEIVED_ITEMS ,
		RECEIVED_RETAIL,
		RECEIVED_COST,
		TOTAL_ITEMS_RETAIL ,
		TOTAL_ITEMS_COST ,
		MIN_PRES_ITEMS ,
		MIN_PRES_RETAIL,
		MIN_PRES_COST)
    select sysdate,
      1,
      8,
      lv10mast.lv8ctree_id,
      1,
      max(lv10roll.cycle),
      lv10roll.live_lv7loc_id,
      sum(lv7loc.height*lv7loc.width*lv7loc.depth),
      sum(lv7loc.height*lv7loc.width),
      sum(lv7loc.depth*lv7loc.width),
      sum(lv7loc.width),
      sum(lv10roll.used_cubic_meters),
      sum(lv10roll.used_dsp_sqmeters),
      sum(lv10roll.used_linear_meters),
      1,
      sum(lv10roll.proj_sales),
      sum(lv10roll.proj_gp),
      sum(lv10roll.loss_sales),
      sum(lv10roll.loss_gp),
      sum(lv10roll.cost_of_invent),
      sum(lv10roll.dir_cost_of_sales),
      sum(lv10roll.indir_cost_of_sale),
      sum(lv10roll.days_in_period),
      1,
      sum(lv10roll.dpp_dollar),
      sum(lv10roll.dpp_item),
      sum(lv10roll.posit_sales),
      sum(lv10roll.posit_mvmt),
      sum(lv10roll.posit_norm_mvmt),
      count(lv10loc.lv10loc_id),
      sum(lv10roll.include_in_avg),
      sum(lv10roll.total_caps),
      sum(lv10roll.total_items),
      sum(lv10roll.total_units),
      sum(lv10roll.vat),
      sum(lv10roll.supp_total_sales),
      sum(lv10roll.supp_cost_of_sales),
      sum(lv10roll.supp_posit_mvmt),
      sum(lv10roll.supplier_norm_mvmt),
      sum(lv10roll.num_user1),
      sum(lv10roll.num_user2),
      sum(lv10roll.num_user3),
      sum(lv10roll.num_user4),
      avg(lv10roll.num_user5),
      avg(lv10roll.num_user6),
      sum(lv10roll.oh_qty),
      sum(lv10roll.oh_cost),
      sum(lv10roll.oh_retail),
      sum(lv10roll.pog_retail),
      x,
		sum(lv10roll.ALLOC_CUBIC_METERS),
		sum(lv10roll.ALLOC_DSP_SQMETERS),
		sum(lv10roll.ALLOC_FLR_SQMETERS),
		sum(lv10roll.ALLOC_LINEAR_METER),
		sum(lv10roll.POSIT_MVMT_REG ),
		sum(lv10roll.POSIT_SALES_REG),
		sum(lv10roll.POSIT_COST_REG ),
		sum(lv10roll.POSIT_MVMT_PROMO ),
		sum(lv10roll.POSIT_SALES_PROMO),
		sum(lv10roll.POSIT_COST_PROMO ),
		sum(lv10roll.POSIT_MVMT_CLRNC ),
		sum(lv10roll.POSIT_SALES_CLRNC),
		sum(lv10roll.POSIT_COST_CLRNC) ,
		sum(lv10roll.POSIT_MVMT_RETN),
		sum(lv10roll.POSIT_SALES_RETN) ,
		sum(lv10roll.POSIT_COST_RETN),
		sum(lv10roll.INVENTORY_ITEMS),
		sum(lv10roll.INVENTORY_RETAIL) ,
		sum(lv10roll.INVENTORY_COST) ,
		sum(lv10roll.RECEIVED_ITEMS) ,
		sum(lv10roll.RECEIVED_RETAIL),
		sum(lv10roll.RECEIVED_COST),
		sum(lv10roll.TOTAL_ITEMS_RETAIL) ,
		sum(lv10roll.TOTAL_ITEMS_COST) ,
		sum(lv10roll.MIN_PRES_ITEMS ),
		sum(lv10roll.MIN_PRES_RETAIL),
		sum(lv10roll.MIN_PRES_COST)
 from maxdata.lv10loc
      ,maxdata.lv10roll
      ,maxdata.lv7loc,maxdata.lv10mast
 where(lv10loc.lv10loc_id=lv10roll.lv10loc_id)
      and(lv7loc.lv7loc_id=lv10roll.live_lv7loc_id)
      and(lv10mast.lv8ctree_id is not null)
       and lv10mast.lv10mast_id = lv10loc.lv10mast_id
group by lv10roll.live_lv7loc_id,
      lv10mast.lv8ctree_id;

--%% category level 9
insert into maxdata.lv7mrll(last_update,
    changed_by_batch,
    category_level,
    ctree_or_loc_id,
    version_id,
    cycle,
    lv7loc_id,
    cubic_meters,
    dsp_sqmeters,
    flr_sqmeters,
    linear_meters,
    used_cubic_meters,
    used_dsp_sqmeters,
    used_linear_meters,
    gm_roii,
    proj_sales,
    proj_gp,
    loss_sales,
    loss_gp,
    cost_of_invent,
    dir_cost_of_sales,
    indir_cost_of_sale,
    days_in_period,
    days_supply,
    dpp_dollar,
    dpp_item,
    posit_sales,
    posit_mvmt,
    posit_norm_mvmt,
    count_num_prodloc,
    count_inc_in_avg,
    total_caps,
    total_items,
    total_units,
    vat,
    supp_total_sales,
    supp_cost_of_sales,
    supp_posit_mvmt,
    supplier_norm_mvmt,
    num_user1,
    num_user2,
    num_user3,
    num_user4,
    num_user5,num_user6,
    oh_qty,
    oh_cost,
    oh_retail,
    pog_retail,
    periods_rolled,
/* Added columns on 06/22/1999  Suresh */
		ALLOC_CUBIC_METERS,
		ALLOC_DSP_SQMETERS,
		ALLOC_FLR_SQMETERS,
		ALLOC_LINEAR_METER,
		POSIT_MVMT_REG ,
		POSIT_SALES_REG,
		POSIT_COST_REG ,
		POSIT_MVMT_PROMO ,
		POSIT_SALES_PROMO,
		POSIT_COST_PROMO ,
		POSIT_MVMT_CLRNC ,
		POSIT_SALES_CLRNC,
		POSIT_COST_CLRNC ,
		POSIT_MVMT_RETN,
		POSIT_SALES_RETN ,
		POSIT_COST_RETN,
		INVENTORY_ITEMS,
		INVENTORY_RETAIL ,
		INVENTORY_COST ,
		RECEIVED_ITEMS ,
		RECEIVED_RETAIL,
		RECEIVED_COST,
		TOTAL_ITEMS_RETAIL ,
		TOTAL_ITEMS_COST ,
		MIN_PRES_ITEMS ,
		MIN_PRES_RETAIL,
		MIN_PRES_COST)
    select sysdate,
      1,
      9,
      lv10mast.lv9ctree_id,
      1,
      max(lv10roll.cycle),
      lv10roll.live_lv7loc_id,
      sum(lv7loc.height*lv7loc.width*lv7loc.depth),
      sum(lv7loc.height*lv7loc.width),
      sum(lv7loc.depth*lv7loc.width),
      sum(lv7loc.width),
      sum(lv10roll.used_cubic_meters),
      sum(lv10roll.used_dsp_sqmeters),
      sum(lv10roll.used_linear_meters),
      1,
      sum(lv10roll.proj_sales),
      sum(lv10roll.proj_gp),
      sum(lv10roll.loss_sales),
      sum(lv10roll.loss_gp),
      sum(lv10roll.cost_of_invent),
      sum(lv10roll.dir_cost_of_sales),
      sum(lv10roll.indir_cost_of_sale),
      sum(lv10roll.days_in_period),
      1,
      sum(lv10roll.dpp_dollar),
      sum(lv10roll.dpp_item),
      sum(lv10roll.posit_sales),
      sum(lv10roll.posit_mvmt),
      sum(lv10roll.posit_norm_mvmt),
      count(lv10loc.lv10loc_id),
      sum(lv10roll.include_in_avg),
      sum(lv10roll.total_caps),
      sum(lv10roll.total_items),
      sum(lv10roll.total_units),
      sum(lv10roll.vat),
      sum(lv10roll.supp_total_sales),
      sum(lv10roll.supp_cost_of_sales),
      sum(lv10roll.supp_posit_mvmt),
      sum(lv10roll.supplier_norm_mvmt),
      sum(lv10roll.num_user1),
      sum(lv10roll.num_user2),
      sum(lv10roll.num_user3),
      sum(lv10roll.num_user4),
      avg(lv10roll.num_user5),
      avg(lv10roll.num_user6),
      sum(lv10roll.oh_qty),
      sum(lv10roll.oh_cost),
      sum(lv10roll.oh_retail),
      sum(lv10roll.pog_retail),
      x,
		sum(lv10roll.ALLOC_CUBIC_METERS),
		sum(lv10roll.ALLOC_DSP_SQMETERS),
		sum(lv10roll.ALLOC_FLR_SQMETERS),
		sum(lv10roll.ALLOC_LINEAR_METER),
		sum(lv10roll.POSIT_MVMT_REG ),
		sum(lv10roll.POSIT_SALES_REG),
		sum(lv10roll.POSIT_COST_REG ),
		sum(lv10roll.POSIT_MVMT_PROMO ),
		sum(lv10roll.POSIT_SALES_PROMO),
		sum(lv10roll.POSIT_COST_PROMO ),
		sum(lv10roll.POSIT_MVMT_CLRNC ),
		sum(lv10roll.POSIT_SALES_CLRNC),
		sum(lv10roll.POSIT_COST_CLRNC) ,
		sum(lv10roll.POSIT_MVMT_RETN),
		sum(lv10roll.POSIT_SALES_RETN) ,
		sum(lv10roll.POSIT_COST_RETN),
		sum(lv10roll.INVENTORY_ITEMS),
		sum(lv10roll.INVENTORY_RETAIL) ,
		sum(lv10roll.INVENTORY_COST) ,
		sum(lv10roll.RECEIVED_ITEMS) ,
		sum(lv10roll.RECEIVED_RETAIL),
		sum(lv10roll.RECEIVED_COST),
		sum(lv10roll.TOTAL_ITEMS_RETAIL) ,
		sum(lv10roll.TOTAL_ITEMS_COST) ,
		sum(lv10roll.MIN_PRES_ITEMS ),
		sum(lv10roll.MIN_PRES_RETAIL),
		sum(lv10roll.MIN_PRES_COST)
 from maxdata.lv10loc
      ,maxdata.lv10roll
      ,maxdata.lv7loc,maxdata.lv10mast
 where(lv10loc.lv10loc_id=lv10roll.lv10loc_id)
      and(lv7loc.lv7loc_id=lv10roll.live_lv7loc_id)
      and(lv10mast.lv9ctree_id is not null)
       and lv10mast.lv10mast_id = lv10loc.lv10mast_id
group by lv10roll.live_lv7loc_id,
      lv10mast.lv9ctree_id;

--%% category level 10
insert into maxdata.lv7mrll(last_update,
    changed_by_batch,
    category_level,
    ctree_or_loc_id,
    version_id,
    cycle,
    lv7loc_id,
    cubic_meters,
    dsp_sqmeters,
    flr_sqmeters,
    linear_meters,
    used_cubic_meters,
    used_dsp_sqmeters,
    used_linear_meters,
    gm_roii,
    proj_sales,
    proj_gp,
    loss_sales,
    loss_gp,
    cost_of_invent,
    dir_cost_of_sales,
    indir_cost_of_sale,
    days_in_period,
    days_supply,
    dpp_dollar,
    dpp_item,
    posit_sales,
    posit_mvmt,
    posit_norm_mvmt,
    count_num_prodloc,
    count_inc_in_avg,
    total_caps,
    total_items,
    total_units,
    vat,
    supp_total_sales,
    supp_cost_of_sales,
    supp_posit_mvmt,
    supplier_norm_mvmt,
    num_user1,
    num_user2,
    num_user3,
    num_user4,
    num_user5,num_user6,
    oh_qty,
    oh_cost,
    oh_retail,
    pog_retail,
    periods_rolled,
/* Added columns on 06/22/1999  Suresh */
		ALLOC_CUBIC_METERS,
		ALLOC_DSP_SQMETERS,
		ALLOC_FLR_SQMETERS,
		ALLOC_LINEAR_METER,
		POSIT_MVMT_REG ,
		POSIT_SALES_REG,
		POSIT_COST_REG ,
		POSIT_MVMT_PROMO ,
		POSIT_SALES_PROMO,
		POSIT_COST_PROMO ,
		POSIT_MVMT_CLRNC ,
		POSIT_SALES_CLRNC,
		POSIT_COST_CLRNC ,
		POSIT_MVMT_RETN,
		POSIT_SALES_RETN ,
		POSIT_COST_RETN,
		INVENTORY_ITEMS,
		INVENTORY_RETAIL ,
		INVENTORY_COST ,
		RECEIVED_ITEMS ,
		RECEIVED_RETAIL,
		RECEIVED_COST,
		TOTAL_ITEMS_RETAIL ,
		TOTAL_ITEMS_COST ,
		MIN_PRES_ITEMS ,
		MIN_PRES_RETAIL,
		MIN_PRES_COST)
    select sysdate,
      1,
      10,
      lv10mast.lv10mast_id,
      1,
      max(lv10roll.cycle),
      lv10roll.live_lv7loc_id,
      sum(lv7loc.height*lv7loc.width*lv7loc.depth),
      sum(lv7loc.height*lv7loc.width),
      sum(lv7loc.depth*lv7loc.width),
      sum(lv7loc.width),
      sum(lv10roll.used_cubic_meters),
      sum(lv10roll.used_dsp_sqmeters),
      sum(lv10roll.used_linear_meters),
      1,
      sum(lv10roll.proj_sales),
      sum(lv10roll.proj_gp),
      sum(lv10roll.loss_sales),
      sum(lv10roll.loss_gp),
      sum(lv10roll.cost_of_invent),
      sum(lv10roll.dir_cost_of_sales),
      sum(lv10roll.indir_cost_of_sale),
      sum(lv10roll.days_in_period),
      1,
      sum(lv10roll.dpp_dollar),
      sum(lv10roll.dpp_item),
      sum(lv10roll.posit_sales),
      sum(lv10roll.posit_mvmt),
      sum(lv10roll.posit_norm_mvmt),
      count(lv10loc.lv10loc_id),
      sum(lv10roll.include_in_avg),
      sum(lv10roll.total_caps),
      sum(lv10roll.total_items),
      sum(lv10roll.total_units),
      sum(lv10roll.vat),
      sum(lv10roll.supp_total_sales),
      sum(lv10roll.supp_cost_of_sales),
      sum(lv10roll.supp_posit_mvmt),
      sum(lv10roll.supplier_norm_mvmt),
      sum(lv10roll.num_user1),
      sum(lv10roll.num_user2),
      sum(lv10roll.num_user3),
      sum(lv10roll.num_user4),
      avg(lv10roll.num_user5),
      avg(lv10roll.num_user6),
      sum(lv10roll.oh_qty),
      sum(lv10roll.oh_cost),
      sum(lv10roll.oh_retail),
      sum(lv10roll.pog_retail),
      x,
		sum(lv10roll.ALLOC_CUBIC_METERS),
		sum(lv10roll.ALLOC_DSP_SQMETERS),
		sum(lv10roll.ALLOC_FLR_SQMETERS),
		sum(lv10roll.ALLOC_LINEAR_METER),
		sum(lv10roll.POSIT_MVMT_REG ),
		sum(lv10roll.POSIT_SALES_REG),
		sum(lv10roll.POSIT_COST_REG ),
		sum(lv10roll.POSIT_MVMT_PROMO ),
		sum(lv10roll.POSIT_SALES_PROMO),
		sum(lv10roll.POSIT_COST_PROMO ),
		sum(lv10roll.POSIT_MVMT_CLRNC ),
		sum(lv10roll.POSIT_SALES_CLRNC),
		sum(lv10roll.POSIT_COST_CLRNC) ,
		sum(lv10roll.POSIT_MVMT_RETN),
		sum(lv10roll.POSIT_SALES_RETN) ,
		sum(lv10roll.POSIT_COST_RETN),
		sum(lv10roll.INVENTORY_ITEMS),
		sum(lv10roll.INVENTORY_RETAIL) ,
		sum(lv10roll.INVENTORY_COST) ,
		sum(lv10roll.RECEIVED_ITEMS) ,
		sum(lv10roll.RECEIVED_RETAIL),
		sum(lv10roll.RECEIVED_COST),
		sum(lv10roll.TOTAL_ITEMS_RETAIL) ,
		sum(lv10roll.TOTAL_ITEMS_COST) ,
		sum(lv10roll.MIN_PRES_ITEMS ),
		sum(lv10roll.MIN_PRES_RETAIL),
		sum(lv10roll.MIN_PRES_COST)
 from maxdata.lv10loc
      ,maxdata.lv10roll
      ,maxdata.lv7loc,maxdata.lv10mast
 where(lv10loc.lv10loc_id=lv10roll.lv10loc_id)
      and(lv7loc.lv7loc_id=lv10roll.live_lv7loc_id)
--      and(lv10mast.lv9ctree_id is not null)
       and lv10mast.lv10mast_id = lv10loc.lv10mast_id
group by lv10roll.live_lv7loc_id,
      lv10mast.lv10mast_id;

end ;

/

  GRANT EXECUTE ON "MAXDATA"."P_GEN_LV7MROLL" TO "MADMAX";
  GRANT EXECUTE ON "MAXDATA"."P_GEN_LV7MROLL" TO "MAXUSER";
