--------------------------------------------------------
--  DDL for Procedure P_LV9_7FINC_PERIOD
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "MAXDATA"."P_LV9_7FINC_PERIOD" 
( period_id IN integer, cycle_id IN integer)
AS
begin
/* Populate LV9Finc from LV10Finc */
insert into maxdata.lv9finc(last_update,
    changed_by_batch,
    period,
    days_in_period,
    cycle,
    version_id,
    live_lv7loc_id,
    lv9loc_id,
    cubic_meters,
    dsp_sqmeters,
    flr_sqmeters,
    linear_meters,
    used_cubic_meters,
    used_dsp_sqmeters,
    used_linear_meters,
    proj_sales,
    proj_gp,
    loss_sales,
    loss_gp,
    days_supply,
    dpp_dollar,
    dpp_item,
    cost_of_invent,
    dir_cost_of_sales,
    indir_cost_of_sale,
    gm_roii,
    posit_sales,
    posit_mvmt,
    posit_norm_mvmt,
    count_inc_in_avg,
    total_caps,
    total_items,
    total_units,
    vat,
    supp_total_sales,
    supp_cost_of_sales,
    supp_posit_mvmt,
    supplier_norm_mvmt,
    num_user1,
    num_user2,
    num_user3,
    num_user4,
    num_user5,
    num_user6,
    oh_qty,
    oh_cost,
    oh_retail,
    pog_retail )
    select sysdate,
      1,
      lv10finc.period,
      sum(lv10finc.days_in_period),
      lv10finc.cycle,
      1,
      lv10finc.live_lv7loc_id,
      lv10loc.lv9loc_id,
      (lv9mast.height*lv9mast.width*lv9mast.depth),
      (lv9mast.height*lv9mast.width),
      (lv9mast.width*lv9mast.depth),
      lv9mast.width,
      sum(lv10finc.used_cubic_meters),
      sum(lv10finc.used_dsp_sqmeters),
      sum(lv10finc.used_linear_meters),
      sum(lv10finc.proj_sales),
      sum(lv10finc.proj_gp),
      sum(lv10finc.loss_sales),
      sum(lv10finc.loss_gp),
      1,
      sum(lv10finc.dpp_dollar),
      sum(lv10finc.dpp_item),
      sum(lv10finc.item_direct_cost*lv10finc.total_items),
      sum(lv10finc.item_direct_cost*lv10finc.posit_mvmt),
      sum(lv10finc.item_indirect_cost*lv10finc.posit_mvmt),
      1,
      sum(lv10finc.posit_sales),
      sum(lv10finc.posit_mvmt),
      sum(lv10finc.posit_norm_mvmt),
      sum(lv10finc.include_in_avg),
      sum(lv10finc.total_caps),
      sum(lv10finc.total_items),
      sum(lv10finc.total_units),
      sum(lv10finc.vat),
      sum(lv10finc.supplier_avg_price*lv10finc.supp_posit_mvmt),
      sum(lv10finc.supplier_item_cost*lv10finc.supp_posit_mvmt),
      sum(lv10finc.supp_posit_mvmt),
      sum(lv10finc.supplier_norm_mvmt),
      sum(lv10finc.num_user1),
      sum(lv10finc.num_user2),
      sum(lv10finc.num_user3),
      sum(lv10finc.num_user4),
      avg(lv10finc.num_user5),
      avg(lv10finc.num_user6),
      sum(lv10finc.oh_qty),
      sum(lv10finc.oh_cost),
      sum(lv10finc.oh_qty*lv10finc.item_average_price),
      sum(lv10finc.total_items*lv10finc.item_average_price)
 from maxdata.lv10finc
      ,maxdata.lv10loc
      ,maxdata.lv9loc
      ,maxdata.lv9mast
 where(lv10loc.lv10loc_id=lv10finc.lv10loc_id)
      and(lv9loc.lv9loc_id=lv10loc.lv9loc_id)
      and(lv9mast.lv9mast_id=lv9loc.lv9mast_id)
      and(lv10finc.period=period_id) and(lv10finc.cycle=cycle_id)
 group by lv10finc.live_lv7loc_id, lv10loc.lv9loc_id,
      lv10finc.period,
      lv10finc.cycle,
      lv9mast.height,
      lv9mast.width,
      lv9mast.depth;

/* Populate LV8Finc from LV10Finc */
insert into maxdata.lv8finc(last_update,
    changed_by_batch,
    period,
    days_in_period,
    cycle,
    version_id,
    live_lv7loc_id,
    lv8loc_id,
    cubic_meters,
    dsp_sqmeters,
    flr_sqmeters,
    linear_meters,
    used_cubic_meters,
    used_dsp_sqmeters,
    used_linear_meters,
    proj_sales,
    proj_gp,
    loss_sales,
    loss_gp,
    days_supply,
    dpp_dollar,
    dpp_item,
    cost_of_invent,
    dir_cost_of_sales,
    indir_cost_of_sale,
    gm_roii,
    posit_sales,
    posit_mvmt,
    posit_norm_mvmt,
    count_inc_in_avg,
    total_caps,
    total_items,
    total_units,
    vat,
    supp_total_sales,
    supp_cost_of_sales,
    supp_posit_mvmt,
    supplier_norm_mvmt,
    num_user1,
    num_user2,
    num_user3,
    num_user4,
    num_user5,
    num_user6,
    oh_qty,
    oh_cost,
    oh_retail,
    pog_retail )
    select sysdate,
      1,
      lv10finc.period,
      sum(lv10finc.days_in_period),
      lv10finc.cycle,
      1,
      lv10finc.live_lv7loc_id,
      lv10loc.lv8loc_id,
      (lv8mast.height*lv8mast.width*lv8mast.depth),
      (lv8mast.height*lv8mast.width),
      (lv8mast.width*lv8mast.depth),
      lv8mast.width,
      sum(lv10finc.used_cubic_meters),
      sum(lv10finc.used_dsp_sqmeters),
      sum(lv10finc.used_linear_meters),
      sum(lv10finc.proj_sales),
      sum(lv10finc.proj_gp),
      sum(lv10finc.loss_sales),
      sum(lv10finc.loss_gp),
      1,
      sum(lv10finc.dpp_dollar),
      sum(lv10finc.dpp_item),
      sum(lv10finc.item_direct_cost*lv10finc.total_items),
      sum(lv10finc.item_direct_cost*lv10finc.posit_mvmt),
      sum(lv10finc.item_indirect_cost*lv10finc.posit_mvmt),
      1,
      sum(lv10finc.posit_sales),
      sum(lv10finc.posit_mvmt),
      sum(lv10finc.posit_norm_mvmt),
      sum(lv10finc.include_in_avg),
      sum(lv10finc.total_caps),
      sum(lv10finc.total_items),
      sum(lv10finc.total_units),
      sum(lv10finc.vat),
      sum(lv10finc.supplier_avg_price*lv10finc.supp_posit_mvmt),
      sum(lv10finc.supplier_item_cost*lv10finc.supp_posit_mvmt),
      sum(lv10finc.supp_posit_mvmt),
      sum(lv10finc.supplier_norm_mvmt),
      sum(lv10finc.num_user1),
      sum(lv10finc.num_user2),
      sum(lv10finc.num_user3),
      sum(lv10finc.num_user4),
      avg(lv10finc.num_user5),
      avg(lv10finc.num_user6),
      sum(lv10finc.oh_qty),
      sum(lv10finc.oh_cost),
      sum(lv10finc.oh_qty*lv10finc.item_average_price),
      sum(lv10finc.total_items*lv10finc.item_average_price)
 from maxdata.lv10finc
      ,maxdata.lv10loc
      ,maxdata.lv8loc
      ,maxdata.lv8mast
--      ,maxdata.pogmaster
 where(lv10loc.lv10loc_id=lv10finc.lv10loc_id)
      and(lv8loc.lv8loc_id=lv10loc.lv8loc_id)
      and(lv8mast.lv8mast_id=lv8loc.lv8mast_id)
      and(lv10finc.period=period_id) and(lv10finc.cycle=cycle_id)
--      and(pogmaster.live_lv7loc_id=lv10finc.live_lv7loc_id)
group by lv10finc.live_lv7loc_id, lv10loc.lv8loc_id,
      lv10finc.period,
      lv10finc.cycle,
      lv8mast.height,
      lv8mast.width,
      lv8mast.depth;

/* Populate LV7Finc from LV10Finc */
insert into maxdata.lv7finc(last_update,
    changed_by_batch,
    period,
    days_in_period,
    cycle,
    version_id,
    lv7loc_id,
    cubic_meters,
    dsp_sqmeters,
    flr_sqmeters,
    linear_meters,
    used_cubic_meters,
    used_dsp_sqmeters,
    used_linear_meters,
    proj_sales,
    proj_gp,
    loss_sales,
    loss_gp,
    days_supply,
    dpp_dollar,
    dpp_item,
    cost_of_invent,
    dir_cost_of_sales,
    indir_cost_of_sale,
    gm_roii,
    posit_sales,
    posit_mvmt,
    posit_norm_mvmt,
    count_inc_in_avg,
    total_caps,
    total_items,
    total_units,
    vat,
    supp_total_sales,
    supp_cost_of_sales,
    supp_posit_mvmt,
    supplier_norm_mvmt,
    num_user1,
    num_user2,
    num_user3,
    num_user4,
    num_user5,
    num_user6,
    oh_qty,
    oh_cost,
    oh_retail,
    pog_retail,
/* Added columns on 06/22/1999  Suresh */
    ALLOC_CUBIC_METERS,
    ALLOC_DSP_SQMETERS,
    ALLOC_FLR_SQMETERS,
    ALLOC_LINEAR_METER,
    POSIT_MVMT_REG ,
    POSIT_SALES_REG,
    POSIT_COST_REG ,
    POSIT_MVMT_PROMO ,
    POSIT_SALES_PROMO,
    POSIT_COST_PROMO ,
    POSIT_MVMT_CLRNC ,
    POSIT_SALES_CLRNC,
    POSIT_COST_CLRNC ,
    POSIT_MVMT_RETN,
    POSIT_SALES_RETN ,
    POSIT_COST_RETN,
    Inventory_items,
    inventory_retail,
    inventory_cost,
    received_items,
    received_retail,
    received_cost,
    total_items_retail,
    total_items_cost,
    min_pres_items,
    min_pres_retail,
    min_pres_cost)
    select sysdate,
      1,
      lv10finc.period,
      sum(lv10finc.days_in_period),
      lv10finc.cycle,
      1,
      lv10finc.live_lv7loc_id,
      (lv7loc.height*lv7loc.width*lv7loc.depth),
      (lv7loc.height*lv7loc.width),
      (lv7loc.width*lv7loc.depth),
      lv7loc.width,
      sum(lv10finc.used_cubic_meters),
      sum(lv10finc.used_dsp_sqmeters),
      sum(lv10finc.used_linear_meters),
      sum(lv10finc.proj_sales),
      sum(lv10finc.proj_gp),
      sum(lv10finc.loss_sales),
      sum(lv10finc.loss_gp),
      1,
      sum(lv10finc.dpp_dollar),
      sum(lv10finc.dpp_item),
      sum(lv10finc.item_direct_cost*lv10finc.total_items),
      sum(lv10finc.item_direct_cost*lv10finc.posit_mvmt),
      sum(lv10finc.item_indirect_cost*lv10finc.posit_mvmt),
      1,
      sum(lv10finc.posit_sales),
      sum(lv10finc.posit_mvmt),
      sum(lv10finc.posit_norm_mvmt),
      sum(lv10finc.include_in_avg),
      sum(lv10finc.total_caps),
      sum(lv10finc.total_items),
      sum(lv10finc.total_units),
      sum(lv10finc.vat),
      sum(lv10finc.supplier_avg_price*lv10finc.supp_posit_mvmt),
      sum(lv10finc.supplier_item_cost*lv10finc.supp_posit_mvmt),
      sum(lv10finc.supp_posit_mvmt),
      sum(lv10finc.supplier_norm_mvmt),
      sum(lv10finc.num_user1),
      sum(lv10finc.num_user2),
      sum(lv10finc.num_user3),
      sum(lv10finc.num_user4),
      avg(lv10finc.num_user5),
      avg(lv10finc.num_user6),
      sum(lv10finc.oh_qty),
      sum(lv10finc.oh_cost),
      sum(lv10finc.oh_qty*lv10finc.item_average_price),
      sum(lv10finc.total_items*lv10finc.item_average_price),
	SUM(lv10finc.ALLOC_CUBIC_METERS),
	SUM(lv10finc.ALLOC_DSP_SQMETERS),
	Sum(lv10finc.ALLOC_FLR_SQMETERS) ,
	Sum(lv10finc.ALLOC_LINEAR_METER),
	sum(lv10finc.posit_mvmt_reg)  ,
	sum(lv10finc.posit_sales_reg),
	sum(lv10finc.item_direct_cost * lv10finc.posit_mvmt_reg ),
	sum(lv10finc.posit_mvmt_promo),
	sum(lv10finc.posit_sales_promo),
	sum(lv10finc.item_direct_cost * lv10finc.posit_mvmt_promo ),
	sum(lv10finc.posit_mvmt_clrnc ),
	sum(lv10finc.posit_sales_clrnc ),
	sum(lv10finc.item_direct_cost * lv10finc.posit_mvmt_clrnc ),
	sum(lv10finc.posit_mvmt_retn ),
	sum(lv10finc.posit_sales_retn ),
	sum(lv10finc.item_direct_cost *  lv10finc.posit_mvmt_retn ),
	sum((lv10finc.begin_inv_items + lv10finc.end_inv_items) / 2),
	sum(((lv10finc.begin_inv_items + lv10finc.end_inv_items) / 2) * lv10finc.item_average_price),
	sum(((lv10finc.begin_inv_items + lv10finc.end_inv_items) / 2) * lv10finc.item_direct_cost),
	Sum(lv10finc.received_items),
	sum(lv10finc.received_items * lv10finc.item_average_price),
	sum(lv10finc.received_items * item_direct_cost),
	sum(lv10finc.total_items * item_average_price),
	sum(lv10finc.total_items * item_direct_cost),
	sum(lv10finc.min_pres_items),
	sum(lv10finc.min_pres_items * lv10finc.item_average_price),
	sum(lv10finc.min_pres_items * item_direct_cost)
 from maxdata.lv10finc
      ,maxdata.lv10loc
      ,maxdata.lv7loc
      ,maxdata.lv7mast
--    ,maxdata.pogmaster
where(lv10loc.lv10loc_id=lv10finc.lv10loc_id)
      and(lv7loc.lv7loc_id=lv10loc.lv7loc_id)
      and(lv7mast.lv7mast_id=lv7loc.lv7mast_id)
      and(lv10finc.period=period_id) and(lv10finc.cycle=cycle_id)
--        and(pogmaster.live_lv7loc_id=lv10finc.live_lv7loc_id)
group by lv10finc.live_lv7loc_id,
      lv10finc.period,
      lv10finc.cycle,
      lv7loc.height,
      lv7loc.width,
      lv7loc.depth ;
end ;

/

  GRANT EXECUTE ON "MAXDATA"."P_LV9_7FINC_PERIOD" TO "MADMAX";
  GRANT EXECUTE ON "MAXDATA"."P_LV9_7FINC_PERIOD" TO "MAXUSER";
