--------------------------------------------------------
--  DDL for Procedure P_LV6_1FINC_PERIOD
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "MAXDATA"."P_LV6_1FINC_PERIOD" ( period_id IN integer, cycle_id IN integer)
AS
begin
/* Populate LV6Finc from LV7Finc */
insert into maxdata.lv6finc(last_update,
    changed_by_batch,
    period,
    days_in_period,
    cycle,
    version_id,
    lv6loc_id,
    cubic_meters,
    dsp_sqmeters,
    flr_sqmeters,
    linear_meters,
    used_cubic_meters,
    used_dsp_sqmeters,
    used_linear_meters,
    proj_sales,
    proj_gp,
    loss_sales,
    loss_gp,
    days_supply,
    dpp_dollar,
    dpp_item,
    cost_of_invent,
    dir_cost_of_sales,
    indir_cost_of_sale,
    gm_roii,
    posit_sales,
    posit_mvmt,
    posit_norm_mvmt,
    count_inc_in_avg,
    total_caps,
    total_items,
    total_units,
    vat,
    supp_total_sales,
    supp_cost_of_sales,
    supp_posit_mvmt,
    supplier_norm_mvmt,
    num_user1,
    num_user2,
    num_user3,
    num_user4,
    num_user5,num_user6,
    oh_qty,
    oh_cost,
    oh_retail,
    pog_retail,
/* Added columns on 06/22/1999  Suresh */
    ALLOC_CUBIC_METERS,
    ALLOC_DSP_SQMETERS,
    ALLOC_FLR_SQMETERS,
    ALLOC_LINEAR_METER,
    POSIT_MVMT_REG ,
    POSIT_SALES_REG,
    POSIT_COST_REG ,
    POSIT_MVMT_PROMO ,
    POSIT_SALES_PROMO,
    POSIT_COST_PROMO ,
    POSIT_MVMT_CLRNC ,
    POSIT_SALES_CLRNC,
    POSIT_COST_CLRNC ,
	POSIT_MVMT_RETN,
	POSIT_SALES_RETN ,
	POSIT_COST_RETN,
	INVENTORY_ITEMS,
	INVENTORY_RETAIL ,
	INVENTORY_COST ,
	RECEIVED_ITEMS ,
	RECEIVED_RETAIL,
	RECEIVED_COST,
	TOTAL_ITEMS_RETAIL ,
	TOTAL_ITEMS_COST ,
	MIN_PRES_ITEMS ,
	MIN_PRES_RETAIL,
      MIN_PRES_COST )
    select SYSDATE,
      1,
      lv7finc.period,
      sum(lv7finc.days_in_period),
      lv7finc.cycle,
      1,
      lv7loc.lv6loc_id,
      (lv6loc.height*lv6loc.width*lv6loc.depth),
      (lv6loc.height*lv6loc.width),
      (lv6loc.width*lv6loc.depth),
      lv6loc.width,
      sum(lv7finc.used_cubic_meters),
      sum(lv7finc.used_dsp_sqmeters),
      sum(lv7finc.used_linear_meters),
      sum(lv7finc.proj_sales),
      sum(lv7finc.proj_gp),
      sum(lv7finc.loss_sales),
      sum(lv7finc.loss_gp),
      1,
      sum(lv7finc.dpp_dollar),
      sum(lv7finc.dpp_item),
      sum(cost_of_invent),
      sum(dir_cost_of_sales),
      sum(indir_cost_of_sale),
      sum(gm_roii),
      sum(lv7finc.posit_sales),
      sum(lv7finc.posit_mvmt),
      sum(lv7finc.posit_norm_mvmt),
      sum(lv7finc.count_inc_in_avg),
      sum(lv7finc.total_caps),
      sum(lv7finc.total_items),
      sum(lv7finc.total_units),
      sum(lv7finc.vat),
      sum(supp_total_sales),
      sum(supp_cost_of_sales),
      sum(lv7finc.supp_posit_mvmt),
      sum(lv7finc.supplier_norm_mvmt),
      sum(lv7finc.num_user1),
      sum(lv7finc.num_user2),
      sum(lv7finc.num_user3),
      sum(lv7finc.num_user4),
      avg(lv7finc.num_user5),
      avg(lv7finc.num_user6),
      sum(lv7finc.oh_qty),
      sum(lv7finc.oh_cost),
      sum(lv7finc.oh_retail),
      sum(lv7finc.pog_retail),
		sum(lv7finc.ALLOC_CUBIC_METERS),
		sum(lv7finc.ALLOC_DSP_SQMETERS),
		sum(lv7finc.ALLOC_FLR_SQMETERS),
		sum(lv7finc.ALLOC_LINEAR_METER),
		sum(lv7finc.POSIT_MVMT_REG ),
		sum(lv7finc.POSIT_SALES_REG),
		sum(lv7finc.POSIT_COST_REG ),
		sum(lv7finc.POSIT_MVMT_PROMO ),
		sum(lv7finc.POSIT_SALES_PROMO),
		sum(lv7finc.POSIT_COST_PROMO ),
		sum(lv7finc.POSIT_MVMT_CLRNC ),
		sum(lv7finc.POSIT_SALES_CLRNC),
		sum(lv7finc.POSIT_COST_CLRNC) ,
		sum(lv7finc.POSIT_MVMT_RETN),
		sum(lv7finc.POSIT_SALES_RETN) ,
		sum(lv7finc.POSIT_COST_RETN),
		sum(lv7finc.INVENTORY_ITEMS),
		sum(lv7finc.INVENTORY_RETAIL) ,
		sum(lv7finc.INVENTORY_COST) ,
		sum(lv7finc.RECEIVED_ITEMS) ,
		sum(lv7finc.RECEIVED_RETAIL),
		sum(lv7finc.RECEIVED_COST),
		sum(lv7finc.TOTAL_ITEMS_RETAIL) ,
		sum(lv7finc.TOTAL_ITEMS_COST) ,
		sum(lv7finc.MIN_PRES_ITEMS ),
		sum(lv7finc.MIN_PRES_RETAIL),
		sum(lv7finc.MIN_PRES_COST)
 from maxdata.lv7finc
      ,maxdata.lv7loc
      ,maxdata.lv6loc
where(lv7loc.lv7loc_id=lv7finc.lv7loc_id)
      and(lv6loc.lv6loc_id=lv7loc.lv6loc_id)
      and(lv7finc.period=period_id) and(lv7finc.cycle=cycle_id)
group by lv7loc.lv6loc_id,
      lv7finc.period,
      lv7finc.cycle,
      lv6loc.height,
      lv6loc.width,
      lv6loc.depth;

/* Populate LV5Finc from LV7Finc */
insert into maxdata.lv5finc(last_update,
    changed_by_batch,
    period,
    days_in_period,
    cycle,
    version_id,
    lv5loc_id,
    cubic_meters,
    dsp_sqmeters,
    flr_sqmeters,
    linear_meters,
    used_cubic_meters,
    used_dsp_sqmeters,
    used_linear_meters,
    proj_sales,
    proj_gp,
    loss_sales,
    loss_gp,
    days_supply,
    dpp_dollar,
    dpp_item,
    cost_of_invent,
    dir_cost_of_sales,
    indir_cost_of_sale,
    gm_roii,
    posit_sales,
    posit_mvmt,
    posit_norm_mvmt,
    count_inc_in_avg,
    total_caps,
    total_items,
    total_units,
    vat,
    supp_total_sales,
    supp_cost_of_sales,
    supp_posit_mvmt,
    supplier_norm_mvmt,
    num_user1,
    num_user2,
    num_user3,
    num_user4,
    num_user5,num_user6,
    oh_qty,
    oh_cost,
    oh_retail,
    pog_retail,
/* Added columns on 06/22/1999  Suresh */
		ALLOC_CUBIC_METERS,
		ALLOC_DSP_SQMETERS,
		ALLOC_FLR_SQMETERS,
		ALLOC_LINEAR_METER,
		POSIT_MVMT_REG ,
		POSIT_SALES_REG,
		POSIT_COST_REG ,
		POSIT_MVMT_PROMO ,
		POSIT_SALES_PROMO,
		POSIT_COST_PROMO ,
		POSIT_MVMT_CLRNC ,
		POSIT_SALES_CLRNC,
		POSIT_COST_CLRNC ,
		POSIT_MVMT_RETN,
		POSIT_SALES_RETN ,
		POSIT_COST_RETN,
		INVENTORY_ITEMS,
		INVENTORY_RETAIL ,
		INVENTORY_COST ,
		RECEIVED_ITEMS ,
		RECEIVED_RETAIL,
		RECEIVED_COST,
		TOTAL_ITEMS_RETAIL ,
		TOTAL_ITEMS_COST ,
		MIN_PRES_ITEMS ,
		MIN_PRES_RETAIL,
		MIN_PRES_COST )
    select SYSDATE,
      1,
      lv7finc.period,
      sum(lv7finc.days_in_period),
      lv7finc.cycle,
      1,
      lv7loc.lv5loc_id,
      (lv5loc.height*lv5loc.width*lv5loc.depth),
      (lv5loc.height*lv5loc.width),
      (lv5loc.width*lv5loc.depth),
      lv5loc.width,
      sum(lv7finc.used_cubic_meters),
      sum(lv7finc.used_dsp_sqmeters),
      sum(lv7finc.used_linear_meters),
      sum(lv7finc.proj_sales),
      sum(lv7finc.proj_gp),
      sum(lv7finc.loss_sales),
      sum(lv7finc.loss_gp),
      1,
      sum(lv7finc.dpp_dollar),
      sum(lv7finc.dpp_item),
      sum(cost_of_invent),
      sum(dir_cost_of_sales),
      sum(indir_cost_of_sale),
      sum(gm_roii),
      sum(lv7finc.posit_sales),
      sum(lv7finc.posit_mvmt),
      sum(lv7finc.posit_norm_mvmt),
      sum(lv7finc.count_inc_in_avg),
      sum(lv7finc.total_caps),
      sum(lv7finc.total_items),
      sum(lv7finc.total_units),
      sum(lv7finc.vat),
      sum(supp_total_sales),
      sum(supp_cost_of_sales),
      sum(lv7finc.supp_posit_mvmt),
      sum(lv7finc.supplier_norm_mvmt),
      sum(lv7finc.num_user1),
      sum(lv7finc.num_user2),
      sum(lv7finc.num_user3),
      sum(lv7finc.num_user4),
      avg(lv7finc.num_user5),
      avg(lv7finc.num_user6),
      sum(lv7finc.oh_qty),
      sum(lv7finc.oh_cost),
      sum(lv7finc.oh_retail),
      sum(lv7finc.pog_retail),
		sum(lv7finc.ALLOC_CUBIC_METERS),
		sum(lv7finc.ALLOC_DSP_SQMETERS),
		sum(lv7finc.ALLOC_FLR_SQMETERS),
		sum(lv7finc.ALLOC_LINEAR_METER),
		sum(lv7finc.POSIT_MVMT_REG ),
		sum(lv7finc.POSIT_SALES_REG),
		sum(lv7finc.POSIT_COST_REG ),
		sum(lv7finc.POSIT_MVMT_PROMO ),
		sum(lv7finc.POSIT_SALES_PROMO),
		sum(lv7finc.POSIT_COST_PROMO ),
		sum(lv7finc.POSIT_MVMT_CLRNC ),
		sum(lv7finc.POSIT_SALES_CLRNC),
		sum(lv7finc.POSIT_COST_CLRNC) ,
		sum(lv7finc.POSIT_MVMT_RETN),
		sum(lv7finc.POSIT_SALES_RETN) ,
		sum(lv7finc.POSIT_COST_RETN),
		sum(lv7finc.INVENTORY_ITEMS),
		sum(lv7finc.INVENTORY_RETAIL) ,
		sum(lv7finc.INVENTORY_COST) ,
		sum(lv7finc.RECEIVED_ITEMS) ,
		sum(lv7finc.RECEIVED_RETAIL),
		sum(lv7finc.RECEIVED_COST),
		sum(lv7finc.TOTAL_ITEMS_RETAIL) ,
		sum(lv7finc.TOTAL_ITEMS_COST) ,
		sum(lv7finc.MIN_PRES_ITEMS ),
		sum(lv7finc.MIN_PRES_RETAIL),
		sum(lv7finc.MIN_PRES_COST)
from maxdata.lv7finc
      ,maxdata.lv7loc
      ,maxdata.lv5loc
where(lv7loc.lv7loc_id=lv7finc.lv7loc_id)
      and(lv5loc.lv5loc_id=lv7loc.lv5loc_id)
      and(lv7finc.period=period_id) and(lv7finc.cycle=cycle_id)
group by lv7loc.lv5loc_id,
      lv7finc.period,
      lv7finc.cycle,
      lv5loc.height,
      lv5loc.width,
      lv5loc.depth;

/* Populate LV4Finc from LV7Finc */
 insert into maxdata.lv4finc(last_update,
    changed_by_batch,
    period,
    days_in_period,
    cycle,
    version_id,
    lv4loc_id,
    cubic_meters,
    dsp_sqmeters,
    flr_sqmeters,
    linear_meters,
    used_cubic_meters,
    used_dsp_sqmeters,
    used_linear_meters,
    proj_sales,
    proj_gp,
    loss_sales,
    loss_gp,
    days_supply,
    dpp_dollar,
    dpp_item,
    cost_of_invent,
    dir_cost_of_sales,
    indir_cost_of_sale,
    gm_roii,
    posit_sales,
    posit_mvmt,
    posit_norm_mvmt,
    count_inc_in_avg,
    total_caps,
    total_items,
    total_units,
    vat,
    supp_total_sales,
    supp_cost_of_sales,
    supp_posit_mvmt,
    supplier_norm_mvmt,
    num_user1,
    num_user2,
    num_user3,
    num_user4,
    num_user5,num_user6,
    oh_qty,
    oh_cost,
    oh_retail,
    pog_retail,
/* Added columns on 06/22/1999  Suresh */
		ALLOC_CUBIC_METERS,
		ALLOC_DSP_SQMETERS,
		ALLOC_FLR_SQMETERS,
		ALLOC_LINEAR_METER,
		POSIT_MVMT_REG ,
		POSIT_SALES_REG,
		POSIT_COST_REG ,
		POSIT_MVMT_PROMO ,
		POSIT_SALES_PROMO,
		POSIT_COST_PROMO ,
		POSIT_MVMT_CLRNC ,
		POSIT_SALES_CLRNC,
		POSIT_COST_CLRNC ,
		POSIT_MVMT_RETN,
		POSIT_SALES_RETN ,
		POSIT_COST_RETN,
		INVENTORY_ITEMS,
		INVENTORY_RETAIL ,
		INVENTORY_COST ,
		RECEIVED_ITEMS ,
		RECEIVED_RETAIL,
		RECEIVED_COST,
		TOTAL_ITEMS_RETAIL ,
		TOTAL_ITEMS_COST ,
		MIN_PRES_ITEMS ,
		MIN_PRES_RETAIL,
		MIN_PRES_COST)
    select SYSDATE,
      1,
      lv7finc.period,
      sum(lv7finc.days_in_period),
      lv7finc.cycle,
      1,
      lv7loc.lv4loc_id,
      (lv4loc.height*lv4loc.width*lv4loc.depth),
      (lv4loc.height*lv4loc.width),
      (lv4loc.width*lv4loc.depth),
      lv4loc.width,
      sum(lv7finc.used_cubic_meters),
      sum(lv7finc.used_dsp_sqmeters),
      sum(lv7finc.used_linear_meters),
      sum(lv7finc.proj_sales),
      sum(lv7finc.proj_gp),
      sum(lv7finc.loss_sales),
      sum(lv7finc.loss_gp),
      1,
      sum(lv7finc.dpp_dollar),
      sum(lv7finc.dpp_item),
      sum(cost_of_invent),
      sum(dir_cost_of_sales),
      sum(indir_cost_of_sale),
      sum(gm_roii),
      sum(lv7finc.posit_sales),
      sum(lv7finc.posit_mvmt),
      sum(lv7finc.posit_norm_mvmt),
      sum(lv7finc.count_inc_in_avg),
      sum(lv7finc.total_caps),
      sum(lv7finc.total_items),
      sum(lv7finc.total_units),
      sum(lv7finc.vat),
      sum(supp_total_sales),
      sum(supp_cost_of_sales),
      sum(lv7finc.supp_posit_mvmt),
      sum(lv7finc.supplier_norm_mvmt),
      sum(lv7finc.num_user1),
      sum(lv7finc.num_user2),
      sum(lv7finc.num_user3),
      sum(lv7finc.num_user4),
      avg(lv7finc.num_user5),
      avg(lv7finc.num_user6),
      sum(lv7finc.oh_qty),
      sum(lv7finc.oh_cost),
      sum(lv7finc.oh_retail),
      sum(lv7finc.pog_retail),
		sum(lv7finc.ALLOC_CUBIC_METERS),
		sum(lv7finc.ALLOC_DSP_SQMETERS),
		sum(lv7finc.ALLOC_FLR_SQMETERS),
		sum(lv7finc.ALLOC_LINEAR_METER),
		sum(lv7finc.POSIT_MVMT_REG ),
		sum(lv7finc.POSIT_SALES_REG),
		sum(lv7finc.POSIT_COST_REG ),
		sum(lv7finc.POSIT_MVMT_PROMO ),
		sum(lv7finc.POSIT_SALES_PROMO),
		sum(lv7finc.POSIT_COST_PROMO ),
		sum(lv7finc.POSIT_MVMT_CLRNC ),
		sum(lv7finc.POSIT_SALES_CLRNC),
		sum(lv7finc.POSIT_COST_CLRNC) ,
		sum(lv7finc.POSIT_MVMT_RETN),
		sum(lv7finc.POSIT_SALES_RETN) ,
		sum(lv7finc.POSIT_COST_RETN),
		sum(lv7finc.INVENTORY_ITEMS),
		sum(lv7finc.INVENTORY_RETAIL) ,
		sum(lv7finc.INVENTORY_COST) ,
		sum(lv7finc.RECEIVED_ITEMS) ,
		sum(lv7finc.RECEIVED_RETAIL),
		sum(lv7finc.RECEIVED_COST),
		sum(lv7finc.TOTAL_ITEMS_RETAIL) ,
		sum(lv7finc.TOTAL_ITEMS_COST) ,
		sum(lv7finc.MIN_PRES_ITEMS ),
		sum(lv7finc.MIN_PRES_RETAIL),
		sum(lv7finc.MIN_PRES_COST)
      from maxdata.lv7finc
      ,maxdata.lv7loc
      ,maxdata.lv4loc
 where(lv7loc.lv7loc_id=lv7finc.lv7loc_id)
      and(lv4loc.lv4loc_id=lv7loc.lv4loc_id)
      and(lv7finc.period=period_id) and(lv7finc.cycle=cycle_id)
group by lv7loc.lv4loc_id,
      lv7finc.period,
      lv7finc.cycle,
      lv4loc.height,
      lv4loc.width,
      lv4loc.depth;

/* Populate LV3Finc from LV7Finc */
 insert into maxdata.lv3finc(last_update,
    changed_by_batch,
    period,
    days_in_period,
    cycle,
    version_id,
    lv3loc_id,
    cubic_meters,
    dsp_sqmeters,
    flr_sqmeters,
    linear_meters,
    used_cubic_meters,
    used_dsp_sqmeters,
    used_linear_meters,
    proj_sales,
    proj_gp,
    loss_sales,
    loss_gp,
    days_supply,
    dpp_dollar,
    dpp_item,
    cost_of_invent,
    dir_cost_of_sales,
    indir_cost_of_sale,
    gm_roii,
    posit_sales,
    posit_mvmt,
    posit_norm_mvmt,
    count_inc_in_avg,
    total_caps,
    total_items,
    total_units,
    vat,
    supp_total_sales,
    supp_cost_of_sales,
    supp_posit_mvmt,
    supplier_norm_mvmt,
    num_user1,
    num_user2,
    num_user3,
    num_user4,
    num_user5,num_user6,
    oh_qty,
    oh_cost,
    oh_retail,
    pog_retail,
/* Added columns on 06/22/1999  Suresh */
		ALLOC_CUBIC_METERS,
		ALLOC_DSP_SQMETERS,
		ALLOC_FLR_SQMETERS,
		ALLOC_LINEAR_METER,
		POSIT_MVMT_REG ,
		POSIT_SALES_REG,
		POSIT_COST_REG ,
		POSIT_MVMT_PROMO ,
		POSIT_SALES_PROMO,
		POSIT_COST_PROMO ,
		POSIT_MVMT_CLRNC ,
		POSIT_SALES_CLRNC,
		POSIT_COST_CLRNC ,
		POSIT_MVMT_RETN,
		POSIT_SALES_RETN ,
		POSIT_COST_RETN,
		INVENTORY_ITEMS,
		INVENTORY_RETAIL ,
		INVENTORY_COST ,
		RECEIVED_ITEMS ,
		RECEIVED_RETAIL,
		RECEIVED_COST,
		TOTAL_ITEMS_RETAIL ,
		TOTAL_ITEMS_COST ,
		MIN_PRES_ITEMS ,
		MIN_PRES_RETAIL,
		MIN_PRES_COST)
  select SYSDATE,
      1,
      lv7finc.period,
      sum(lv7finc.days_in_period),
      lv7finc.cycle,
      1,
      lv7loc.lv3loc_id,
      (lv3loc.height*lv3loc.width*lv3loc.depth),
      (lv3loc.height*lv3loc.width),
      (lv3loc.width*lv3loc.depth),
      lv3loc.width,
      sum(lv7finc.used_cubic_meters),
      sum(lv7finc.used_dsp_sqmeters),
      sum(lv7finc.used_linear_meters),
      sum(lv7finc.proj_sales),
      sum(lv7finc.proj_gp),
      sum(lv7finc.loss_sales),
      sum(lv7finc.loss_gp),
      1,
      sum(lv7finc.dpp_dollar),
      sum(lv7finc.dpp_item),
      sum(cost_of_invent),
      sum(dir_cost_of_sales),
      sum(indir_cost_of_sale),
      sum(gm_roii),
      sum(lv7finc.posit_sales),
      sum(lv7finc.posit_mvmt),
      sum(lv7finc.posit_norm_mvmt),
      sum(lv7finc.count_inc_in_avg),
      sum(lv7finc.total_caps),
      sum(lv7finc.total_items),
      sum(lv7finc.total_units),
      sum(lv7finc.vat),
      sum(supp_total_sales),
      sum(supp_cost_of_sales),
      sum(lv7finc.supp_posit_mvmt),
      sum(lv7finc.supplier_norm_mvmt),
      sum(lv7finc.num_user1),
      sum(lv7finc.num_user2),
      sum(lv7finc.num_user3),
      sum(lv7finc.num_user4),
      avg(lv7finc.num_user5),
      avg(lv7finc.num_user6),
      sum(lv7finc.oh_qty),
      sum(lv7finc.oh_cost),
      sum(lv7finc.oh_retail),
      sum(lv7finc.pog_retail),
		sum(lv7finc.ALLOC_CUBIC_METERS),
		sum(lv7finc.ALLOC_DSP_SQMETERS),
		sum(lv7finc.ALLOC_FLR_SQMETERS),
		sum(lv7finc.ALLOC_LINEAR_METER),
		sum(lv7finc.POSIT_MVMT_REG ),
		sum(lv7finc.POSIT_SALES_REG),
		sum(lv7finc.POSIT_COST_REG ),
		sum(lv7finc.POSIT_MVMT_PROMO ),
		sum(lv7finc.POSIT_SALES_PROMO),
		sum(lv7finc.POSIT_COST_PROMO ),
		sum(lv7finc.POSIT_MVMT_CLRNC ),
		sum(lv7finc.POSIT_SALES_CLRNC),
		sum(lv7finc.POSIT_COST_CLRNC) ,
		sum(lv7finc.POSIT_MVMT_RETN),
		sum(lv7finc.POSIT_SALES_RETN) ,
		sum(lv7finc.POSIT_COST_RETN),
		sum(lv7finc.INVENTORY_ITEMS),
		sum(lv7finc.INVENTORY_RETAIL) ,
		sum(lv7finc.INVENTORY_COST) ,
		sum(lv7finc.RECEIVED_ITEMS) ,
		sum(lv7finc.RECEIVED_RETAIL),
		sum(lv7finc.RECEIVED_COST),
		sum(lv7finc.TOTAL_ITEMS_RETAIL) ,
		sum(lv7finc.TOTAL_ITEMS_COST) ,
		sum(lv7finc.MIN_PRES_ITEMS ),
		sum(lv7finc.MIN_PRES_RETAIL),
		sum(lv7finc.MIN_PRES_COST)
 from maxdata.lv7finc
      ,maxdata.lv7loc
      ,maxdata.lv3loc
where(lv7loc.lv7loc_id=lv7finc.lv7loc_id)
      and(lv3loc.lv3loc_id=lv7loc.lv3loc_id)
      and(lv7finc.period=period_id) and(lv7finc.cycle=cycle_id)
group by lv7loc.lv3loc_id,
      lv7finc.period,
      lv7finc.cycle,
      lv3loc.height,
      lv3loc.width,
      lv3loc.depth;

/* Populate LV2Finc from LV7Finc */
 insert into maxdata.lv2finc(last_update,
    changed_by_batch,
    period,
    days_in_period,
    cycle,
    version_id,
    lv2loc_id,
    cubic_meters,
    dsp_sqmeters,
    flr_sqmeters,
    linear_meters,
    used_cubic_meters,
    used_dsp_sqmeters,
    used_linear_meters,
    proj_sales,
    proj_gp,
    loss_sales,
    loss_gp,
    days_supply,
    dpp_dollar,
    dpp_item,
    cost_of_invent,
    dir_cost_of_sales,
    indir_cost_of_sale,
    gm_roii,
    posit_sales,
    posit_mvmt,
    posit_norm_mvmt,
    count_inc_in_avg,
    total_caps,
    total_items,
    total_units,
    vat,
    supp_total_sales,
    supp_cost_of_sales,
    supp_posit_mvmt,
    supplier_norm_mvmt,
    num_user1,
    num_user2,
    num_user3,
    num_user4,
    num_user5,num_user6,
    oh_qty,
    oh_cost,
    oh_retail,
    pog_retail,
/* Added columns on 06/22/1999  Suresh */
		ALLOC_CUBIC_METERS,
		ALLOC_DSP_SQMETERS,
		ALLOC_FLR_SQMETERS,
		ALLOC_LINEAR_METER,
		POSIT_MVMT_REG ,
		POSIT_SALES_REG,
		POSIT_COST_REG ,
		POSIT_MVMT_PROMO ,
		POSIT_SALES_PROMO,
		POSIT_COST_PROMO ,
		POSIT_MVMT_CLRNC ,
		POSIT_SALES_CLRNC,
		POSIT_COST_CLRNC ,
		POSIT_MVMT_RETN,
		POSIT_SALES_RETN ,
		POSIT_COST_RETN,
		INVENTORY_ITEMS,
		INVENTORY_RETAIL ,
		INVENTORY_COST ,
		RECEIVED_ITEMS ,
		RECEIVED_RETAIL,
		RECEIVED_COST,
		TOTAL_ITEMS_RETAIL ,
		TOTAL_ITEMS_COST ,
		MIN_PRES_ITEMS ,
		MIN_PRES_RETAIL,
		MIN_PRES_COST)
    select SYSDATE,
      1,
      lv7finc.period,
      sum(lv7finc.days_in_period),
      lv7finc.cycle,
      1,
      lv7loc.lv2loc_id,
      (lv2loc.height*lv2loc.width*lv2loc.depth),
      (lv2loc.height*lv2loc.width),
      (lv2loc.width*lv2loc.depth),
      lv2loc.width,
      sum(lv7finc.used_cubic_meters),
      sum(lv7finc.used_dsp_sqmeters),
      sum(lv7finc.used_linear_meters),
      sum(lv7finc.proj_sales),
      sum(lv7finc.proj_gp),
      sum(lv7finc.loss_sales),
      sum(lv7finc.loss_gp),
      1,
      sum(lv7finc.dpp_dollar),
      sum(lv7finc.dpp_item),
      sum(cost_of_invent),
      sum(dir_cost_of_sales),
      sum(indir_cost_of_sale),
      sum(gm_roii),
      sum(lv7finc.posit_sales),
      sum(lv7finc.posit_mvmt),
      sum(lv7finc.posit_norm_mvmt),
      sum(lv7finc.count_inc_in_avg),
      sum(lv7finc.total_caps),
      sum(lv7finc.total_items),
      sum(lv7finc.total_units),
      sum(lv7finc.vat),
      sum(supp_total_sales),
      sum(supp_cost_of_sales),
      sum(lv7finc.supp_posit_mvmt),
      sum(lv7finc.supplier_norm_mvmt),
      sum(lv7finc.num_user1),
      sum(lv7finc.num_user2),
      sum(lv7finc.num_user3),
      sum(lv7finc.num_user4),
      avg(lv7finc.num_user5),
      avg(lv7finc.num_user6),
      sum(lv7finc.oh_qty),
      sum(lv7finc.oh_cost),
      sum(lv7finc.oh_retail),
      sum(lv7finc.pog_retail),
		sum(lv7finc.ALLOC_CUBIC_METERS),
		sum(lv7finc.ALLOC_DSP_SQMETERS),
		sum(lv7finc.ALLOC_FLR_SQMETERS),
		sum(lv7finc.ALLOC_LINEAR_METER),
		sum(lv7finc.POSIT_MVMT_REG ),
		sum(lv7finc.POSIT_SALES_REG),
		sum(lv7finc.POSIT_COST_REG ),
		sum(lv7finc.POSIT_MVMT_PROMO ),
		sum(lv7finc.POSIT_SALES_PROMO),
		sum(lv7finc.POSIT_COST_PROMO ),
		sum(lv7finc.POSIT_MVMT_CLRNC ),
		sum(lv7finc.POSIT_SALES_CLRNC),
		sum(lv7finc.POSIT_COST_CLRNC) ,
		sum(lv7finc.POSIT_MVMT_RETN),
		sum(lv7finc.POSIT_SALES_RETN) ,
		sum(lv7finc.POSIT_COST_RETN),
		sum(lv7finc.INVENTORY_ITEMS),
		sum(lv7finc.INVENTORY_RETAIL) ,
		sum(lv7finc.INVENTORY_COST) ,
		sum(lv7finc.RECEIVED_ITEMS) ,
		sum(lv7finc.RECEIVED_RETAIL),
		sum(lv7finc.RECEIVED_COST),
		sum(lv7finc.TOTAL_ITEMS_RETAIL) ,
		sum(lv7finc.TOTAL_ITEMS_COST) ,
		sum(lv7finc.MIN_PRES_ITEMS ),
		sum(lv7finc.MIN_PRES_RETAIL),
		sum(lv7finc.MIN_PRES_COST)
      from maxdata.lv7finc
      ,maxdata.lv7loc
      ,maxdata.lv2loc
where(lv7loc.lv7loc_id=lv7finc.lv7loc_id)
      and(lv2loc.lv2loc_id=lv7loc.lv2loc_id)
      and(lv7finc.period=period_id) and(lv7finc.cycle=cycle_id)
group by lv7loc.lv2loc_id,
      lv7finc.period,
      lv7finc.cycle,
      lv2loc.height,
      lv2loc.width,
      lv2loc.depth;

/* Populate LV1Finc from LV7Finc */
 insert into maxdata.lv1finc(last_update,
    changed_by_batch,
    period,
    days_in_period,
    cycle,
    version_id,
    lv1loc_id,
    cubic_meters,
    dsp_sqmeters,
    flr_sqmeters,
    linear_meters,
    used_cubic_meters,
    used_dsp_sqmeters,
    used_linear_meters,
    proj_sales,
    proj_gp,
    loss_sales,
    loss_gp,
    days_supply,
    dpp_dollar,
    dpp_item,
    cost_of_invent,
    dir_cost_of_sales,
    indir_cost_of_sale,
    gm_roii,
    posit_sales,
    posit_mvmt,
    posit_norm_mvmt,
    count_inc_in_avg,
    total_caps,
    total_items,
    total_units,
    vat,
    supp_total_sales,
    supp_cost_of_sales,
    supp_posit_mvmt,
    supplier_norm_mvmt,
    num_user1,
    num_user2,
    num_user3,
    num_user4,
    num_user5,num_user6,
    oh_qty,
    oh_cost,
    oh_retail,
    pog_retail,
/* Added columns on 06/22/1999  Suresh */
		ALLOC_CUBIC_METERS,
		ALLOC_DSP_SQMETERS,
		ALLOC_FLR_SQMETERS,
		ALLOC_LINEAR_METER,
		POSIT_MVMT_REG ,
		POSIT_SALES_REG,
		POSIT_COST_REG ,
		POSIT_MVMT_PROMO ,
		POSIT_SALES_PROMO,
		POSIT_COST_PROMO ,
		POSIT_MVMT_CLRNC ,
		POSIT_SALES_CLRNC,
		POSIT_COST_CLRNC ,
		POSIT_MVMT_RETN,
		POSIT_SALES_RETN ,
		POSIT_COST_RETN,
		INVENTORY_ITEMS,
		INVENTORY_RETAIL ,
		INVENTORY_COST ,
		RECEIVED_ITEMS ,
		RECEIVED_RETAIL,
		RECEIVED_COST,
		TOTAL_ITEMS_RETAIL ,
		TOTAL_ITEMS_COST ,
		MIN_PRES_ITEMS ,
		MIN_PRES_RETAIL,
		MIN_PRES_COST)
    select SYSDATE,
      1,
      lv7finc.period,
      sum(lv7finc.days_in_period),
      lv7finc.cycle,
      1,
      lv7loc.lv1loc_id,
      (lv1loc.height*lv1loc.width*lv1loc.depth),
      (lv1loc.height*lv1loc.width),
      (lv1loc.width*lv1loc.depth),
      lv1loc.width,
      sum(lv7finc.used_cubic_meters),
      sum(lv7finc.used_dsp_sqmeters),
      sum(lv7finc.used_linear_meters),
      sum(lv7finc.proj_sales),
      sum(lv7finc.proj_gp),
      sum(lv7finc.loss_sales),
      sum(lv7finc.loss_gp),
      1,
      sum(lv7finc.dpp_dollar),
      sum(lv7finc.dpp_item),
      sum(cost_of_invent),
      sum(dir_cost_of_sales),
      sum(indir_cost_of_sale),
      sum(gm_roii),
      sum(lv7finc.posit_sales),
      sum(lv7finc.posit_mvmt),
      sum(lv7finc.posit_norm_mvmt),
      sum(lv7finc.count_inc_in_avg),
      sum(lv7finc.total_caps),
      sum(lv7finc.total_items),
      sum(lv7finc.total_units),
      sum(lv7finc.vat),
      sum(supp_total_sales),
      sum(supp_cost_of_sales),
      sum(lv7finc.supp_posit_mvmt),
      sum(lv7finc.supplier_norm_mvmt),
      sum(lv7finc.num_user1),
      sum(lv7finc.num_user2),
      sum(lv7finc.num_user3),
      sum(lv7finc.num_user4),
      avg(lv7finc.num_user5),
      avg(lv7finc.num_user6),
      sum(lv7finc.oh_qty),
      sum(lv7finc.oh_cost),
      sum(lv7finc.oh_retail),
      sum(lv7finc.pog_retail),
		sum(lv7finc.ALLOC_CUBIC_METERS),
		sum(lv7finc.ALLOC_DSP_SQMETERS),
		sum(lv7finc.ALLOC_FLR_SQMETERS),
		sum(lv7finc.ALLOC_LINEAR_METER),
		sum(lv7finc.POSIT_MVMT_REG ),
		sum(lv7finc.POSIT_SALES_REG),
		sum(lv7finc.POSIT_COST_REG ),
		sum(lv7finc.POSIT_MVMT_PROMO ),
		sum(lv7finc.POSIT_SALES_PROMO),
		sum(lv7finc.POSIT_COST_PROMO ),
		sum(lv7finc.POSIT_MVMT_CLRNC ),
		sum(lv7finc.POSIT_SALES_CLRNC),
		sum(lv7finc.POSIT_COST_CLRNC) ,
		sum(lv7finc.POSIT_MVMT_RETN),
		sum(lv7finc.POSIT_SALES_RETN) ,
		sum(lv7finc.POSIT_COST_RETN),
		sum(lv7finc.INVENTORY_ITEMS),
		sum(lv7finc.INVENTORY_RETAIL) ,
		sum(lv7finc.INVENTORY_COST) ,
		sum(lv7finc.RECEIVED_ITEMS) ,
		sum(lv7finc.RECEIVED_RETAIL),
		sum(lv7finc.RECEIVED_COST),
		sum(lv7finc.TOTAL_ITEMS_RETAIL) ,
		sum(lv7finc.TOTAL_ITEMS_COST) ,
		sum(lv7finc.MIN_PRES_ITEMS ),
		sum(lv7finc.MIN_PRES_RETAIL),
		sum(lv7finc.MIN_PRES_COST)
 from maxdata.lv7finc
      ,maxdata.lv7loc
      ,maxdata.lv1loc
 where(lv7loc.lv7loc_id=lv7finc.lv7loc_id)
      and(lv1loc.lv1loc_id=lv7loc.lv1loc_id)
      and(lv7finc.period=period_id) and(lv7finc.cycle=cycle_id)
group by lv7loc.lv1loc_id,
      lv7finc.period,
      lv7finc.cycle,
      lv1loc.height,
      lv1loc.width,
      lv1loc.depth ;
end ;

/

  GRANT EXECUTE ON "MAXDATA"."P_LV6_1FINC_PERIOD" TO "MADMAX";
  GRANT EXECUTE ON "MAXDATA"."P_LV6_1FINC_PERIOD" TO "MAXUSER";
