--------------------------------------------------------
--  DDL for Procedure P_LV2_FINC_ALL
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "MAXDATA"."P_LV2_FINC_ALL" 
as

 t_period_type  char(20);

begin

select period_type into t_period_type
from maxapp.mmax_config;


DELETE FROM maxdata.lv2finc;
commit;
insert into maxdata.lv2finc
        (last_update,
         changed_by_batch,
         period,
         days_in_period,
         cycle,
         version_id,
         lv2loc_id,
         cubic_meters,
         dsp_sqmeters,
         flr_sqmeters,
         linear_meters,
         used_cubic_meters,
         used_dsp_sqmeters,
         used_linear_meters,
         proj_sales,
         proj_gp,
         loss_sales,
         loss_gp,
         days_supply,
         dpp_dollar,
         dpp_item,
         cost_of_invent,
         dir_cost_of_sales,
         indir_cost_of_sale,
         gm_roii,
         posit_sales,
         posit_mvmt,
         posit_norm_mvmt,
         count_inc_in_avg,
         total_caps,
         total_items,
         total_units,
         vat,
         supp_total_sales,
         supp_cost_of_sales,
         supp_posit_mvmt,
         supplier_norm_mvmt,
         num_user1,
         num_user2,
         num_user3,
         num_user4,
         num_user5,
         num_user6,
         oh_qty,
         oh_cost,
         oh_retail,
         pog_retail,
         inventory_items,
         inventory_cost,
         inventory_retail,
         alloc_cubic_meters,
         alloc_dsp_sqmeters,
         alloc_flr_sqmeters,
         alloc_linear_meter,
         posit_mvmt_reg,
         posit_sales_reg,
         posit_cost_reg,
         posit_mvmt_promo,
         posit_sales_promo,
         posit_cost_promo,
         posit_mvmt_clrnc,
         posit_sales_clrnc,
         posit_cost_clrnc,
         posit_mvmt_retn,
         posit_sales_retn,
         posit_cost_retn,
         min_pres_items,
         min_pres_retail,
         min_pres_cost,
       	RECEIVED_ITEMS ,
	RECEIVED_RETAIL,
	RECEIVED_COST,
	TOTAL_ITEMS_RETAIL ,
	TOTAL_ITEMS_COST,
-- new columns added by diwakar 0n 08/09/00
 --	 Begin_inv_cost,
 --        Begin_inv_retail,
 --        Begin_inv_items,
 --        end_inv_retail,
 --        end_inv_cost,
 --        end_inv_items,
	 posit_indcost_reg,
	 posit_indcost_promo,
	 posit_indcost_clrnc,
	 posit_indcost_retn,
         Sales_retail_5,
         Sales_Cost_5 ,
         Sales_Items_5,
         Sales_indcost_5,
         Sales_retail_6,
         Sales_Cost_6,
         Sales_Items_6,
         Sales_indcost_6,
         Sales_retail_7,
         Sales_Cost_7,
         Sales_Items_7,
         Sales_indcost_7,
         Sales_retail_8,
         Sales_Cost_8,
         Sales_Items_8,
         Sales_indcost_8,
         Sales_retail_9,
         Sales_Cost_9,
         Sales_Items_9,
         Sales_indcost_9,
         Sales_retail_10,
         Sales_Cost_10,
         Sales_Items_10,
         Sales_indcost_10,
         Inv_retail_1,
         Inv_Cost_1,
         Inv_Items_1,
         Inv_indcost_1,
         Inv_retail_2,
         Inv_Cost_2,
         Inv_Items_2,
         Inv_indcost_2,
         Inv_retail_3,
         Inv_Cost_3,
         Inv_Items_3,
         Inv_indcost_3,
         Inv_retail_4,
         Inv_Cost_4,
         Inv_Items_4,
         Inv_indcost_4,
         Inv_retail_5,
         Inv_Cost_5,
         Inv_Items_5,
         Inv_indcost_5,
         Inv_retail_6,
         Inv_Cost_6,
         Inv_Items_6,
         Inv_indcost_6,
         Inv_retail_7,
         Inv_Cost_7,
         Inv_Items_7,
         Inv_indcost_7,
         Inv_retail_8,
         Inv_Cost_8,
         Inv_Items_8,
         Inv_indcost_8,
         Inv_retail_9,
         Inv_Cost_9,
         Inv_Items_9,
         Inv_indcost_9,
         Inv_retail_10,
         Inv_Cost_10,
         Inv_Items_10,
         Inv_indcost_10,
         Sum_user1,
         Sum_user2,
         Sum_user3,
         Sum_user4,
         Sum_user5,
         Avg_user1,
         Avg_user2,
         Avg_user3,
         Avg_user4,
         Avg_user5,

--Added for DataManager 4.5.3 by Santosh 01/16/2001
	 Ceiling_avg_user1,
	 Ceiling_avg_user2,
	 Ceiling_avg_user3,
	 Ceiling_avg_user4,
	 Ceiling_avg_user5,
	 Xcoord_facings,
	 Main_flr_space)


  select
         sysdate,
         1,
         lv4finc.period,
         sum(lv4finc.days_in_period),
         lv4finc.cycle,
         1,
         lv4loc.lv2loc_id,

         sum(lv4finc.cubic_meters),
         sum(lv4finc.dsp_sqmeters),
         sum(lv4finc.flr_sqmeters),
         sum(lv4finc.linear_meters),

         sum(lv4finc.used_cubic_meters),
         sum(lv4finc.used_dsp_sqmeters),
         sum(lv4finc.used_linear_meters),
         sum(lv4finc.proj_sales),
         sum(lv4finc.proj_gp),
         sum(lv4finc.loss_sales),
         sum(lv4finc.loss_gp),
         1,
         sum(lv4finc.dpp_dollar),
         sum(lv4finc.dpp_item),
         sum(lv4finc.cost_of_invent),
         sum(lv4finc.dir_cost_of_sales),
         sum(lv4finc.indir_cost_of_sale),
         sum(lv4finc.gm_roii),
         sum(lv4finc.posit_sales),
         sum(lv4finc.posit_mvmt),
         sum(lv4finc.posit_norm_mvmt),
         sum(lv4finc.count_inc_in_avg),
         sum(lv4finc.total_caps),
         sum(lv4finc.total_items),
         sum(lv4finc.total_units),
         sum(lv4finc.vat),
         sum(lv4finc.supp_total_sales),
         sum(lv4finc.supp_cost_of_sales),
         sum(lv4finc.supp_posit_mvmt),
         sum(lv4finc.supplier_norm_mvmt),
         sum(lv4finc.num_user1),
         sum(lv4finc.num_user2),
         sum(lv4finc.num_user3),
         sum(lv4finc.num_user4),
         avg(lv4finc.num_user5),
         avg(lv4finc.num_user6),
-- aggregation was changed from sum to avg to reflect more close inventory.
-- Needs calculation in 5.2 for exact figure as per Bob.
         avg(lv4finc.oh_qty),
         avg(lv4finc.oh_cost),
         avg(lv4finc.oh_retail),
         sum(lv4finc.pog_retail),
         avg(lv4finc.inventory_items),
         avg(lv4finc.inventory_cost),
         avg(lv4finc.inventory_retail),
         sum(lv4finc.alloc_cubic_meters),
         sum(lv4finc.alloc_dsp_sqmeters),
         sum(lv4finc.alloc_flr_sqmeters),
         sum(lv4finc.alloc_linear_meter),
         sum(lv4finc.posit_mvmt_reg),
         sum(lv4finc.posit_sales_reg),
         sum(lv4finc.posit_cost_reg),
         sum(lv4finc.posit_mvmt_promo),
         sum(lv4finc.posit_sales_promo),
         sum(lv4finc.posit_cost_promo),
         sum(lv4finc.posit_mvmt_clrnc),
         sum(lv4finc.posit_sales_clrnc),
         sum(lv4finc.posit_cost_clrnc),
         sum(lv4finc.posit_mvmt_retn),
         sum(lv4finc.posit_sales_retn),
         sum(lv4finc.posit_cost_retn),
         sum(lv4finc.min_pres_items),
         sum(lv4finc.min_pres_retail),
         sum(lv4finc.min_pres_cost),
       	sum(lv4finc.RECEIVED_ITEMS) ,
	sum(lv4finc.RECEIVED_RETAIL),
	sum(lv4finc.RECEIVED_COST),
	sum(lv4finc.TOTAL_ITEMS_RETAIL) ,
	sum(lv4finc.TOTAL_ITEMS_COST),
	 --    avg(lv4finc.Begin_inv_cost),
     --    avg(lv4finc.Begin_inv_retail),
     --    avg(lv4finc.Begin_inv_items),
     --    avg(lv4finc.end_inv_retail),
     --    avg(lv4finc.end_inv_cost),
     --    avg(lv4finc.end_inv_items),
	 sum(lv4finc.posit_indcost_reg),
	 sum(lv4finc.posit_indcost_promo),
	 sum(lv4finc.posit_indcost_clrnc),
	 sum(lv4finc.posit_indcost_retn),
         sum(lv4finc.Sales_retail_5),
         sum(lv4finc.Sales_Cost_5),
         sum(lv4finc.Sales_Items_5),
         sum(lv4finc.Sales_indcost_5),
         sum(lv4finc.Sales_retail_6),
         sum(lv4finc.Sales_Cost_6),
         sum(lv4finc.Sales_Items_6),
         sum(lv4finc.Sales_indcost_6),
         sum(lv4finc.Sales_retail_7),
         sum(lv4finc.Sales_Cost_7),
         sum(lv4finc.Sales_Items_7),
         sum(lv4finc.Sales_indcost_7),
         sum(lv4finc.Sales_retail_8),
         sum(lv4finc.Sales_Cost_8),
         sum(lv4finc.Sales_Items_8),
         sum(lv4finc.Sales_indcost_8),
         sum(lv4finc.Sales_retail_9),
         sum(lv4finc.Sales_Cost_9),
         sum(lv4finc.Sales_Items_9),
         sum(lv4finc.Sales_indcost_9),
         sum(lv4finc.Sales_retail_10),
         sum(lv4finc.Sales_Cost_10),
         sum(lv4finc.Sales_Items_10),
         sum(lv4finc.Sales_indcost_10),
         sum(lv4finc.Inv_retail_1),
         sum(lv4finc.Inv_Cost_1),
         sum(lv4finc.Inv_Items_1),
         sum(lv4finc.Inv_indcost_1),
         sum(lv4finc.Inv_retail_2),
         sum(lv4finc.Inv_Cost_2),
         sum(lv4finc.Inv_Items_2),
         sum(lv4finc.Inv_indcost_2),
         sum(lv4finc.Inv_retail_3),
         sum(lv4finc.Inv_Cost_3),
         sum(lv4finc.Inv_Items_3),
         sum(lv4finc.Inv_indcost_3),
         sum(lv4finc.Inv_retail_4),
         sum(lv4finc.Inv_Cost_4),
         sum(lv4finc.Inv_Items_4),
         sum(lv4finc.Inv_indcost_4),
         sum(lv4finc.Inv_retail_5),
         sum(lv4finc.Inv_Cost_5),
         sum(lv4finc.Inv_Items_5),
         sum(lv4finc.Inv_indcost_5),
         sum(lv4finc.Inv_retail_6),
         sum(lv4finc.Inv_Cost_6),
         sum(lv4finc.Inv_Items_6),
         sum(lv4finc.Inv_indcost_6),
         sum(lv4finc.Inv_retail_7),
         sum(lv4finc.Inv_Cost_7),
         sum(lv4finc.Inv_Items_7),
         sum(lv4finc.Inv_indcost_7),
         sum(lv4finc.Inv_retail_8),
         sum(lv4finc.Inv_Cost_8),
         sum(lv4finc.Inv_Items_8),
         sum(lv4finc.Inv_indcost_8),
         sum(lv4finc.Inv_retail_9),
         sum(lv4finc.Inv_Cost_9),
         sum(lv4finc.Inv_Items_9),
         sum(lv4finc.Inv_indcost_9),
         sum(lv4finc.Inv_retail_10),
         sum(lv4finc.Inv_Cost_10),
         sum(lv4finc.Inv_Items_10),
         sum(lv4finc.Inv_indcost_10),
         sum(lv4finc.Sum_user1),
         sum(lv4finc.Sum_user2),
         sum(lv4finc.Sum_user3),
         sum(lv4finc.Sum_user4),
         sum(lv4finc.Sum_user5),
         avg(lv4finc.Avg_user1),
         avg(lv4finc.Avg_user2),
         avg(lv4finc.Avg_user3),
         avg(lv4finc.Avg_user4),
         avg(lv4finc.Avg_user5),
--Added for DataManager 4.5.3 by Santosh 01/16/2001
	  sum(lv4finc.ceiling_avg_user1),
	  sum(lv4finc.ceiling_avg_user2),
	  sum(lv4finc.ceiling_avg_user3),
	  sum(lv4finc.ceiling_avg_user4),
	  sum(lv4finc.ceiling_avg_user5),
	  sum(lv4finc.xcoord_facings),
	   sum(lv4finc.main_flr_space)

    from maxdata.lv4finc,
         maxdata.lv4loc

   where (lv4loc.lv4loc_id=lv4finc.lv4loc_id)

group by lv4loc.lv2loc_id,
         lv4finc.period,
         lv4finc.cycle;

--Added by Maurice to populate period_start_date on 02/12/2001
Update maxdata.lv2finc set period_start_date
= ( select period_start_date from maxapp.period_lkup
where period_id = lv2finc.period and cycle_id = lv2finc.cycle
and period_type = t_period_type);

commit;
end ;

/

  GRANT EXECUTE ON "MAXDATA"."P_LV2_FINC_ALL" TO "MADMAX";
  GRANT EXECUTE ON "MAXDATA"."P_LV2_FINC_ALL" TO "MAXUSER";
