--------------------------------------------------------
--  DDL for Procedure P_POG_ANALYZER
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "MAXDATA"."P_POG_ANALYZER" (li_model_lv7loc_id number)
as

-- changed to run only if roll records dont already exist for this model planogram.
   -- a select st added, deletes removed.
-- fix to lv7 to check if pog is current.
-- added levels 7,8 , 9
-- 10/26
-- Build average roll from lv10roll of all live sections for a model pog
t_periods_rolled 	 integer;
t_new_10roll_id		number(10,0);

-- cursor thru LV10LOC for the model pog

    cursor   c_lv10loc is
    select   lv10loc_id
    from     lv10loc
    where    lv7loc_id = li_model_lv7loc_id ;

--  cursor thru LV9LOC for the model pog

    cursor   c_lv9loc is
    select   lv9loc_id
    from     lv9loc
    where    lv7loc_id = li_model_lv7loc_id ;

--  cursor thru LV8LOC for the model pog

    cursor   c_lv8loc is
    select   lv8loc_id
    from     lv8loc
    where    lv7loc_id = li_model_lv7loc_id ;

-- declare cursor to sum lv10roll by lv10loc


  cursor c_lv10roll(li_lv10loc_id number) is
    select
      max(lv10roll.cycle) cycle,
      lv10roll.lv10loc_id,
      sum(lv10roll.used_cubic_meters)  c_col1,
      sum(lv10roll.used_dsp_sqmeters)  c_col2,
      sum(lv10roll.used_flr_sqmeters)  c_col3,
      sum(lv10roll.used_linear_meters) c_col4,
      sum(lv10roll.loss_sales)         c_col5,
      sum(lv10roll.loss_Gp)            c_col6,
      sum(lv10roll.proj_sales)         c_col7,
      sum(lv10roll.proj_gp)            c_col8,
      sum(lv10roll.gm_roii)            c_col9,
      sum(lv10roll.days_in_period)     c_col10,
      sum(lv10roll.days_supply)        c_col11,
      sum(lv10roll.dpp_dollar)         c_col12,
      sum(lv10roll.dpp_item)           c_col13,
      sum(lv10roll.cost_of_invent)     c_col14,
      sum(lv10roll.dir_cost_of_sales)  c_col15,
      sum(lv10roll.indir_cost_of_sale) c_col16,
      sum(lv10roll.posit_sales)        c_col17,
      sum(lv10roll.posit_mvmt)         c_col18,
      sum(lv10roll.posit_norm_mvmt)    c_col19,
      sum(lv10roll.include_in_avg)     c_col20,
      sum(lv10roll.total_caps)         c_col21,
      sum(lv10roll.total_units)        c_col22,
      sum(lv10roll.total_items)        c_col23,
      sum(lv10roll.vat)                c_col24,
      sum(lv10roll.supp_total_sales)   c_col25,
      sum(lv10roll.supp_cost_of_sales) c_col26,
      sum(lv10roll.supp_posit_mvmt)    c_col27,
      sum(lv10roll.supplier_norm_mvmt) c_col28,
      sum(lv10roll.oh_qty)             c_col35,
      sum(lv10roll.oh_cost)            c_col36,
      sum(lv10roll.oh_retail)		c_col37,
      sum(lv10roll.pog_retail) 	   	c_col38,
      sum(lv10roll.alloc_cubic_meters) c_col39,
      sum(lv10roll.alloc_dsp_sqmeters) c_col40,
      sum(lv10roll.alloc_flr_sqmeters) c_col41,
      sum(lv10roll.alloc_linear_meter) c_col42,
      sum(lv10roll.posit_mvmt_reg)     c_col43,
      sum(lv10roll.posit_sales_reg)    c_col44,
      sum(lv10roll.posit_cost_reg)     c_col45,
      sum(lv10roll.posit_mvmt_promo)   c_col46,
      sum(lv10roll.posit_sales_promo)  c_col47,
      sum(lv10roll.posit_cost_promo)   c_col48,
      sum(lv10roll.posit_mvmt_clrnc)   c_col49,
      sum(lv10roll.posit_sales_clrnc)  c_col50,
      sum(lv10roll.posit_cost_clrnc)   c_col51,
      sum(lv10roll.posit_mvmt_retn)    c_col52,
      sum(lv10roll.posit_sales_retn)   c_col53,
      sum(lv10roll.posit_cost_retn)    c_col54,
      sum(lv10roll.inventory_items)    c_col55,
      sum(lv10roll.inventory_retail)   c_col56,
      sum(lv10roll.inventory_cost)     c_col57,
      sum(lv10roll.received_items)     c_col58,
      sum(lv10roll.received_retail)    c_col59,
      sum(lv10roll.received_cost)      c_col60,
      sum(lv10roll.total_items_retail) c_col61,
      sum(lv10roll.total_items_cost)   c_col62,
      sum(lv10roll.min_pres_items)     c_col63,
      sum(lv10roll.min_pres_retail)    c_col64,
      sum(lv10roll.min_pres_cost)      c_col65,
      sum(lv10roll.Lv10mast_id)  c_col66,
      sum(lv10roll.posit_indcost_reg)  c_col67,
      sum(lv10roll.posit_indcost_promo)  c_col68,
      sum(lv10roll.posit_indcost_clrnc)  c_col69,
      sum(lv10roll.posit_indcost_retn)  c_col70,
      sum(lv10roll.Sales_retail_5)  c_col71,
      sum(lv10roll.Sales_Cost_5)  c_col72,
      sum(lv10roll.Sales_Items_5)  c_col73,
      sum(lv10roll.Sales_indcost_5)  c_col74,
      sum(lv10roll.Sales_retail_6)  c_col75,
      sum(lv10roll.Sales_Cost_6)  c_col76,
      sum(lv10roll.Sales_Items_6)  c_col77,
      sum(lv10roll.Sales_indcost_6)  c_col78,
      sum(lv10roll.Sales_retail_7)  c_col79,
      sum(lv10roll.Sales_Cost_7)  c_col80,
      sum(lv10roll.Sales_Items_7)  c_col81,
      sum(lv10roll.Sales_indcost_7)  c_col82,
      sum(lv10roll.Sales_retail_8)  c_col83,
      sum(lv10roll.Sales_Cost_8)  c_col84,
      sum(lv10roll.Sales_Items_8)  c_col85,
      sum(lv10roll.Sales_indcost_8)  c_col86,
      sum(lv10roll.Sales_retail_9)  c_col87,
      sum(lv10roll.Sales_Cost_9)  c_col88,
      sum(lv10roll.Sales_Items_9)  c_col89,
      sum(lv10roll.Sales_indcost_9)  c_col90,
      sum(lv10roll.Sales_retail_10)  c_col91,
      sum(lv10roll.Sales_Cost_10)  c_col92,
      sum(lv10roll.Sales_Items_10)  c_col93,
      sum(lv10roll.Sales_indcost_10)  c_col94,
      sum(lv10roll.Inv_retail_1)  c_col95,
      sum(lv10roll.Inv_Cost_1)  c_col96,
      sum(lv10roll.Inv_Items_1)  c_col97,
      sum(lv10roll.Inv_indcost_1)  c_col98,
      sum(lv10roll.Inv_retail_2)  c_col99,
      sum(lv10roll.Inv_Cost_2)  c_col100,
      sum(lv10roll.Inv_Items_2)  c_col101,
      sum(lv10roll.Inv_indcost_2)  c_col102,
      sum(lv10roll.Inv_retail_3)  c_col103,
      sum(lv10roll.Inv_Cost_3)  c_col104,
      sum(lv10roll.Inv_Items_3)  c_col105,
      sum(lv10roll.Inv_indcost_3)  c_col106,
      sum(lv10roll.Inv_retail_4)  c_col107,
      sum(lv10roll.Inv_Cost_4)  c_col108,
      sum(lv10roll.Inv_Items_4)  c_col109,
      sum(lv10roll.Inv_indcost_4)  c_col110,
      sum(lv10roll.Inv_retail_5)  c_col112,
      sum(lv10roll.Inv_Cost_5)  c_col113,
      sum(lv10roll.Inv_Items_5)  c_col114,
      sum(lv10roll.Inv_indcost_5)  c_col115,
      sum(lv10roll.Inv_retail_6)  c_col116,
      sum(lv10roll.Inv_Cost_6)  c_col117,
      sum(lv10roll.Inv_Items_6)  c_col118,
      sum(lv10roll.Inv_indcost_6)  c_col119,
      sum(lv10roll.Inv_retail_7)  c_col120,
      sum(lv10roll.Inv_Cost_7)  c_col121,
      sum(lv10roll.Inv_Items_7)  c_col122,
      sum(lv10roll.Inv_indcost_7)  c_col123,
      sum(lv10roll.Inv_retail_8)  c_col124,
      sum(lv10roll.Inv_Cost_8)  c_col125,
      sum(lv10roll.Inv_Items_8)  c_col126,
      sum(lv10roll.Inv_indcost_8)  c_col127,
      sum(lv10roll.Inv_retail_9)  c_col128,
      sum(lv10roll.Inv_Cost_9)  c_col129,
      sum(lv10roll.Inv_Items_9)  c_col130,
      sum(lv10roll.Inv_indcost_9)  c_col131,
      sum(lv10roll.Inv_retail_10)  c_col132,
      sum(lv10roll.Inv_Cost_10)  c_col133,
      sum(lv10roll.Inv_Items_10)  c_col134,
      sum(lv10roll.Inv_indcost_10)  c_col135,
      sum(lv10roll.Sum_user1)  c_col136,
      sum(lv10roll.Sum_user2)  c_col137,
      sum(lv10roll.Sum_user3)  c_col138,
      sum(lv10roll.Sum_user4)  c_col139,
      sum(lv10roll.Sum_user5)  c_col140,
      avg(lv10roll.Avg_user1)  c_col141,
      avg(lv10roll.Avg_user2)  c_col142,
      avg(lv10roll.Avg_user3)  c_col143,
      avg(lv10roll.Avg_user4)  c_col144,
      avg(lv10roll.Avg_user5)  c_col145,
      sum(lv10roll.inventory_indcost)   c_col146,
      sum(lv10roll.oh_indcost)	   c_col147,
      sum(lv10roll.cum_eop_units)    c_col148,
      sum(lv10roll.cum_eop_retail)   c_col149,
      sum(lv10roll.cum_eop_cost)     c_col150       ,
      sum(lv10roll.cum_eop_indcost)  c_col151	,
      sum(lv10roll.received_indcost) c_col152	,
      sum(lv10roll.active_loc_flag)  c_col153 ,
      sum(lv10roll.store_count)	     c_col154
    from   lv10roll
    where  lv10roll.lv10loc_id= li_lv10loc_id
    group by lv10roll.lv10loc_id;

--	Commented out as fix for bug #9056
	--, lv10roll.cycle;

-- Cursor on lv9roll

cursor c_lv9roll(li_lv9loc_id number) is
    select
      max(lv9roll.cycle)  cycle,
      lv9roll.lv9loc_id,
      sum(lv9roll.cubic_meters) 		c_col1,
      sum(lv9roll.dsp_sqmeters) 		c_col2,
      sum(lv9roll.flr_sqmeters) 		c_col3,
      sum(lv9roll.linear_meters) 		c_col4,
      sum(lv9roll.used_cubic_meters) 	c_col5,
      sum(lv9roll.used_dsp_sqmeters) 	c_col6,
      sum(lv9roll.used_linear_meters) 	c_col7,
      sum(lv9roll.loss_sales) 		c_col8,
      sum(lv9roll.loss_gp) 			c_col9,
      sum(lv9roll.proj_sales) 		c_col10,
      sum(lv9roll.proj_gp) 			c_col11,
      sum(lv9roll.gm_roii) 			c_col12,
      sum(lv9roll.days_in_period)		c_col13,
      sum(lv9roll.days_supply) 		c_col14,
      sum(lv9roll.dpp_dollar) 		c_col15,
      sum(lv9roll.dpp_item) 			c_col16,
      sum(lv9roll.cost_of_invent) 		c_col17,
      sum(lv9roll.dir_cost_of_sales) 	c_col18,
      sum(lv9roll.indir_cost_of_sale) 	c_col19,
      sum(lv9roll.posit_sales) 		c_col20,
      sum(lv9roll.posit_mvmt) 		c_col21,
      sum(lv9roll.posit_norm_mvmt) 		c_col22,
      sum(lv9roll.count_num_prodloc) 	c_col23,
      sum(lv9roll.count_inc_in_avg) 	c_col24,
      sum(lv9roll.total_caps) 		c_col25,
      sum(lv9roll.total_units) 		c_col26,
      sum(lv9roll.total_items) 		c_col27,
      sum(lv9roll.vat) 				c_col28,
      sum(lv9roll.supp_total_sales) 	c_col29,
      sum(lv9roll.supp_cost_of_sales) 	c_col30,
      sum(lv9roll.supp_posit_mvmt) 		c_col31,
      sum(lv9roll.supplier_norm_mvmt) 	c_col32,
      sum(lv9roll.oh_qty) 			c_col39,
      sum(lv9roll.oh_cost) 			c_col40,
      sum(lv9roll.oh_retail) 			c_col41,
      sum(lv9roll. pog_retail) 		c_col42,
      t_periods_rolled 			c_col43,
         sum(lv9roll.posit_indcost_reg)  c_col45,
	 sum(lv9roll.posit_indcost_promo)  c_col46,
	 sum(lv9roll.posit_indcost_clrnc)  c_col47,
	 sum(lv9roll.posit_indcost_retn)  c_col48,
         sum(lv9roll.Sales_retail_5)  c_col49,
         sum(lv9roll.Sales_Cost_5)  c_col50,
         sum(lv9roll.Sales_Items_5)  c_col51,
         sum(lv9roll.Sales_indcost_5)  c_col52,
         sum(lv9roll.Sales_retail_6)  c_col53,
         sum(lv9roll.Sales_Cost_6)  c_col54,
         sum(lv9roll.Sales_Items_6)  c_col55,
         sum(lv9roll.Sales_indcost_6)  c_col56,
         sum(lv9roll.Sales_retail_7)  c_col57,
         sum(lv9roll.Sales_Cost_7)  c_col58,
         sum(lv9roll.Sales_Items_7)  c_col59,
         sum(lv9roll.Sales_indcost_7)  c_col60,
         sum(lv9roll.Sales_retail_8)  c_col61,
         sum(lv9roll.Sales_Cost_8)  c_col62,
         sum(lv9roll.Sales_Items_8)  c_col63,
         sum(lv9roll.Sales_indcost_8)  c_col64,
         sum(lv9roll.Sales_retail_9)  c_col65,
         sum(lv9roll.Sales_Cost_9)  c_col66,
         sum(lv9roll.Sales_Items_9)  c_col67,
         sum(lv9roll.Sales_indcost_9)  c_col68,
         sum(lv9roll.Sales_retail_10)  c_col69,
         sum(lv9roll.Sales_Cost_10)  c_col70,
         sum(lv9roll.Sales_Items_10)  c_col71,
         sum(lv9roll.Sales_indcost_10)  c_col72,
         sum(lv9roll.Inv_retail_1)  c_col73,
         sum(lv9roll.Inv_Cost_1)  c_col74,
         sum(lv9roll.Inv_Items_1)  c_col75,
         sum(lv9roll.Inv_indcost_1)  c_col76,
         sum(lv9roll.Inv_retail_2)  c_col77,
         sum(lv9roll.Inv_Cost_2)  c_col78,
         sum(lv9roll.Inv_Items_2)  c_col79,
         sum(lv9roll.Inv_indcost_2)  c_col80,
         sum(lv9roll.Inv_retail_3)  c_col81,
         sum(lv9roll.Inv_Cost_3)  c_col82,
         sum(lv9roll.Inv_Items_3)  c_col83,
         sum(lv9roll.Inv_indcost_3)  c_col84,
         sum(lv9roll.Inv_retail_4)  c_col85,
         sum(lv9roll.Inv_Cost_4)  c_col86,
         sum(lv9roll.Inv_Items_4)  c_col87,
         sum(lv9roll.Inv_indcost_4)  c_col88,
         sum(lv9roll.Inv_retail_5)  c_col89,
         sum(lv9roll.Inv_Cost_5)  c_col90,
         sum(lv9roll.Inv_Items_5)  c_col91,
         sum(lv9roll.Inv_indcost_5)  c_col92,
         sum(lv9roll.Inv_retail_6)  c_col93,
         sum(lv9roll.Inv_Cost_6)  c_col94,
         sum(lv9roll.Inv_Items_6)  c_col95,
         sum(lv9roll.Inv_indcost_6)  c_col96,
         sum(lv9roll.Inv_retail_7)  c_col97,
         sum(lv9roll.Inv_Cost_7)  c_col98,
         sum(lv9roll.Inv_Items_7)  c_col99,
         sum(lv9roll.Inv_indcost_7)  c_col100,
         sum(lv9roll.Inv_retail_8)  c_col101,
         sum(lv9roll.Inv_Cost_8)  c_col102,
         sum(lv9roll.Inv_Items_8)  c_col103,
         sum(lv9roll.Inv_indcost_8)  c_col104,
         sum(lv9roll.Inv_retail_9)  c_col105,
         sum(lv9roll.Inv_Cost_9)  c_col106,
         sum(lv9roll.Inv_Items_9)  c_col107,
         sum(lv9roll.Inv_indcost_9)  c_col108,
         sum(lv9roll.Inv_retail_10)  c_col109,
         sum(lv9roll.Inv_Cost_10)  c_col110,
         sum(lv9roll.Inv_Items_10)  c_col111,
         sum(lv9roll.Inv_indcost_10)  c_col112,
         sum(lv9roll.Sum_user1)  c_col113,
         sum(lv9roll.Sum_user2)  c_col114,
         sum(lv9roll.Sum_user3)  c_col115,
         sum(lv9roll.Sum_user4)  c_col116,
         sum(lv9roll.Sum_user5)  c_col117,
         avg(lv9roll.Avg_user1)  c_col118,
         avg(lv9roll.Avg_user2)  c_col119,
         avg(lv9roll.Avg_user3)  c_col120,
         avg(lv9roll.Avg_user4)  c_col121,
         avg(lv9roll.Avg_user5)  c_col122,
          sum(lv9roll.oh_indcost)	   c_col123,
      sum(lv9roll.cum_eop_units)    c_col124,
      sum(lv9roll.cum_eop_retail)   c_col125,
      sum(lv9roll.cum_eop_cost)     c_col126       ,
      sum(lv9roll.cum_eop_indcost)  c_col127	,
      sum(lv9roll.received_indcost) c_col128	,
      sum(lv9roll.active_loc_flag)  c_col129,
       sum(lv9roll.store_count)	     c_col130

       from   lv9roll
    where    lv9roll.lv9loc_id= li_lv9loc_id
    group by lv9roll.lv9loc_id;
--	Commented out as fix for bug #9056
	-- , lv9roll.cycle;

   -- Cursor on lv8roll

     cursor c_lv8roll(li_lv8loc_id number) is
    select
      max(lv8roll.cycle)  cycle,
      lv8roll.lv8loc_id,
      sum(lv8roll.cubic_meters) 		c_col1,
      sum(lv8roll.dsp_sqmeters) 		c_col2,
      sum(lv8roll.flr_sqmeters) 		c_col3,
      sum(lv8roll.linear_meters) 		c_col4,
      sum(lv8roll.used_cubic_meters) 	c_col5,
      sum(lv8roll.used_dsp_sqmeters) 	c_col6,
      sum(lv8roll.used_linear_meters) 	c_col7,
      sum(lv8roll.loss_sales) 		c_col8,
      sum(lv8roll.loss_gp) 			c_col9,
      sum(lv8roll.proj_sales) 		c_col10,
      sum(lv8roll.proj_gp) 			c_col11,
      sum(lv8roll.gm_roii) 			c_col12,
      sum(lv8roll.days_in_period)		c_col13,
      sum(lv8roll.days_supply) 		c_col14,
      sum(lv8roll.dpp_dollar) 		c_col15,
      sum(lv8roll.dpp_item) 			c_col16,
      sum(lv8roll.cost_of_invent) 		c_col17,
      sum(lv8roll.dir_cost_of_sales) 	c_col18,
      sum(lv8roll.indir_cost_of_sale) 	c_col19,
      sum(lv8roll.posit_sales) 		c_col20,
      sum(lv8roll.posit_mvmt) 		c_col21,
      sum(lv8roll.posit_norm_mvmt) 		c_col22,
      sum(lv8roll.count_num_prodloc) 	c_col23,
      sum(lv8roll.count_inc_in_avg) 	c_col24,
      sum(lv8roll.total_caps) 		c_col25,
      sum(lv8roll.total_units) 		c_col26,
      sum(lv8roll.total_items) 		c_col27,
      sum(lv8roll.vat) 				c_col28,
      sum(lv8roll.supp_total_sales) 	c_col29,
      sum(lv8roll.supp_cost_of_sales) 	c_col30,
      sum(lv8roll.supp_posit_mvmt) 		c_col31,
      sum(lv8roll.supplier_norm_mvmt) 	c_col32,
      sum(lv8roll.oh_qty) 			c_col39,
      sum(lv8roll.oh_cost) 			c_col40,
      sum(lv8roll.oh_retail) 			c_col41,
      sum(lv8roll. pog_retail) 		c_col42,
      t_periods_rolled 			c_col43,
         sum(lv8roll.posit_indcost_reg)  c_col45,
	 sum(lv8roll.posit_indcost_promo)  c_col46,
	 sum(lv8roll.posit_indcost_clrnc)  c_col47,
	 sum(lv8roll.posit_indcost_retn)  c_col48,
         sum(lv8roll.Sales_retail_5)  c_col49,
         sum(lv8roll.Sales_Cost_5)  c_col50,
         sum(lv8roll.Sales_Items_5)  c_col51,
         sum(lv8roll.Sales_indcost_5)  c_col52,
         sum(lv8roll.Sales_retail_6)  c_col53,
         sum(lv8roll.Sales_Cost_6)  c_col54,
         sum(lv8roll.Sales_Items_6)  c_col55,
         sum(lv8roll.Sales_indcost_6)  c_col56,
         sum(lv8roll.Sales_retail_7)  c_col57,
         sum(lv8roll.Sales_Cost_7)  c_col58,
         sum(lv8roll.Sales_Items_7)  c_col59,
         sum(lv8roll.Sales_indcost_7)  c_col60,
         sum(lv8roll.Sales_retail_8)  c_col61,
         sum(lv8roll.Sales_Cost_8)  c_col62,
         sum(lv8roll.Sales_Items_8)  c_col63,
         sum(lv8roll.Sales_indcost_8)  c_col64,
         sum(lv8roll.Sales_retail_9)  c_col65,
         sum(lv8roll.Sales_Cost_9)  c_col66,
         sum(lv8roll.Sales_Items_9)  c_col67,
         sum(lv8roll.Sales_indcost_9)  c_col68,
         sum(lv8roll.Sales_retail_10)  c_col69,
         sum(lv8roll.Sales_Cost_10)  c_col70,
         sum(lv8roll.Sales_Items_10)  c_col71,
         sum(lv8roll.Sales_indcost_10)  c_col72,
         sum(lv8roll.Inv_retail_1)  c_col73,
         sum(lv8roll.Inv_Cost_1)  c_col74,
         sum(lv8roll.Inv_Items_1)  c_col75,
         sum(lv8roll.Inv_indcost_1)  c_col76,
         sum(lv8roll.Inv_retail_2)  c_col77,
         sum(lv8roll.Inv_Cost_2)  c_col78,
         sum(lv8roll.Inv_Items_2)  c_col79,
         sum(lv8roll.Inv_indcost_2)  c_col80,
         sum(lv8roll.Inv_retail_3)  c_col81,
         sum(lv8roll.Inv_Cost_3)  c_col82,
         sum(lv8roll.Inv_Items_3)  c_col83,
         sum(lv8roll.Inv_indcost_3)  c_col84,
         sum(lv8roll.Inv_retail_4)  c_col85,
         sum(lv8roll.Inv_Cost_4)  c_col86,
         sum(lv8roll.Inv_Items_4)  c_col87,
         sum(lv8roll.Inv_indcost_4)  c_col88,
         sum(lv8roll.Inv_retail_5)  c_col89,
         sum(lv8roll.Inv_Cost_5)  c_col90,
         sum(lv8roll.Inv_Items_5)  c_col91,
         sum(lv8roll.Inv_indcost_5)  c_col92,
         sum(lv8roll.Inv_retail_6)  c_col93,
         sum(lv8roll.Inv_Cost_6)  c_col94,
         sum(lv8roll.Inv_Items_6)  c_col95,
         sum(lv8roll.Inv_indcost_6)  c_col96,
         sum(lv8roll.Inv_retail_7)  c_col97,
         sum(lv8roll.Inv_Cost_7)  c_col98,
         sum(lv8roll.Inv_Items_7)  c_col99,
         sum(lv8roll.Inv_indcost_7)  c_col100,
         sum(lv8roll.Inv_retail_8)  c_col101,
         sum(lv8roll.Inv_Cost_8)  c_col102,
         sum(lv8roll.Inv_Items_8)  c_col103,
         sum(lv8roll.Inv_indcost_8)  c_col104,
         sum(lv8roll.Inv_retail_9)  c_col105,
         sum(lv8roll.Inv_Cost_9)  c_col106,
         sum(lv8roll.Inv_Items_9)  c_col107,
         sum(lv8roll.Inv_indcost_9)  c_col108,
         sum(lv8roll.Inv_retail_10)  c_col109,
         sum(lv8roll.Inv_Cost_10)  c_col110,
         sum(lv8roll.Inv_Items_10)  c_col111,
         sum(lv8roll.Inv_indcost_10)  c_col112,
         sum(lv8roll.Sum_user1)  c_col113,
         sum(lv8roll.Sum_user2)  c_col114,
         sum(lv8roll.Sum_user3)  c_col115,
         sum(lv8roll.Sum_user4)  c_col116,
         sum(lv8roll.Sum_user5)  c_col117,
         avg(lv8roll.Avg_user1)  c_col118,
         avg(lv8roll.Avg_user2)  c_col119,
         avg(lv8roll.Avg_user3)  c_col120,
         avg(lv8roll.Avg_user4)  c_col121,
         avg(lv8roll.Avg_user5)  c_col122,
          sum(lv8roll.oh_indcost)	   c_col123,
      sum(lv8roll.cum_eop_units)    c_col124,
      sum(lv8roll.cum_eop_retail)   c_col125,
      sum(lv8roll.cum_eop_cost)     c_col126       ,
      sum(lv8roll.cum_eop_indcost)  c_col127	,
      sum(lv8roll.received_indcost) c_col128	,
      sum(lv8roll.active_loc_flag)  c_col129,
      sum(lv8roll.store_count)	     c_col130
        from   lv8roll
    where    lv8roll.lv8loc_id= li_lv8loc_id
    group by lv8roll.lv8loc_id;
--	Commented out as fix for bug #9056
	-- , lv8roll.cycle;


--	Commented out as fix for bug #9056
	-- , lv8roll.cycle ;

  next_lv10rollid  number ;
  t_model_lv7loc_id number(10) ;
  ctr number(10);

begin

   select count(*)
   into ctr
   from maxdata.lv7roll
   where lv7loc_id = li_model_lv7loc_id;

  If ctr = 0 then

    select MAX(periods_rolled) into t_periods_rolled from maxdata.lv7roll;

  -- Delete Model Roll data
  -- delete from lv10roll where live_lv7loc_id = li_model_lv7loc_id;
  -- Get each product location for the model pog

  for c1 in c_lv10loc loop
    -- Sum roll for each location

    for cur_rec in c_lv10roll(c1.lv10loc_id) loop
      -- Insert new Model roll data

	maxapp.f_get_seq ( 10, 6, t_new_10roll_id);

       insert into lv10roll
      ( lv10roll_id,
	last_update,
        version_id,
        lv10loc_id,
        live_lv7loc_id,
        cycle,
        used_cubic_meters,
        used_dsp_sqmeters,
        used_flr_sqmeters,
        used_linear_meters,
        loss_sales,
        loss_gp,
        proj_sales,
        proj_gp,
        gm_roii,
        days_in_period,
        days_supply,
        dpp_dollar,
        dpp_item,
        cost_of_invent,
        dir_cost_of_sales,
        indir_cost_of_sale,
        posit_sales,
        posit_mvmt,
        posit_norm_mvmt,
        include_in_avg,
        total_caps,
        total_units,
        total_items,
        vat,
        supp_total_sales,
        supp_cost_of_sales,
        supp_posit_mvmt,
        supplier_norm_mvmt,
        concat_id,
        oh_qty,
        oh_cost,
	oh_retail,
        pog_retail,
        alloc_cubic_meters,
        alloc_dsp_sqmeters,
        alloc_flr_sqmeters,
        alloc_linear_meter,
        posit_mvmt_reg,
        posit_sales_reg,
        posit_cost_reg,
        posit_mvmt_promo,
        posit_sales_promo,
        posit_cost_promo,
        posit_mvmt_clrnc,
        posit_sales_clrnc,
        posit_cost_clrnc,
        posit_mvmt_retn,
        posit_sales_retn,
        posit_cost_retn,
        inventory_items,
        inventory_retail,
        inventory_cost,
        received_items,
        received_retail,
        received_cost,
        total_items_retail,
        total_items_cost,
        min_pres_items,
        min_pres_retail,
        min_pres_cost,
	lv10mast_id,
	 posit_indcost_reg,
	 posit_indcost_promo,
	 posit_indcost_clrnc,
	 posit_indcost_retn,
         Sales_retail_5,
         Sales_Cost_5,
         Sales_Items_5,
         Sales_indcost_5,
         Sales_retail_6,
         Sales_Cost_6,
         Sales_Items_6,
         Sales_indcost_6,
         Sales_retail_7,
         Sales_Cost_7,
         Sales_Items_7,
         Sales_indcost_7,
         Sales_retail_8,
         Sales_Cost_8,
         Sales_Items_8,
         Sales_indcost_8,
         Sales_retail_9,
         Sales_Cost_9,
         Sales_Items_9,
         Sales_indcost_9,
         Sales_retail_10,
         Sales_Cost_10,
         Sales_Items_10,
         Sales_indcost_10,
         Inv_retail_1,
         Inv_Cost_1,
         Inv_Items_1,
         Inv_indcost_1,
         Inv_retail_2,
         Inv_Cost_2,
         Inv_Items_2,
         Inv_indcost_2,
         Inv_retail_3,
         Inv_Cost_3,
         Inv_Items_3,
         Inv_indcost_3,
         Inv_retail_4,
         Inv_Cost_4,
         Inv_Items_4,
         Inv_indcost_4,
         Inv_retail_5,
         Inv_Cost_5,
         Inv_Items_5,
         Inv_indcost_5,
         Inv_retail_6,
         Inv_Cost_6,
         Inv_Items_6,
         Inv_indcost_6,
         Inv_retail_7,
         Inv_Cost_7,
         Inv_Items_7,
         Inv_indcost_7,
         Inv_retail_8,
         Inv_Cost_8,
         Inv_Items_8,
         Inv_indcost_8,
         Inv_retail_9,
         Inv_Cost_9,
         Inv_Items_9,
         Inv_indcost_9,
         Inv_retail_10,
         Inv_Cost_10,
         Inv_Items_10,
         Inv_indcost_10,
         Sum_user1,
         Sum_user2,
         Sum_user3,
         Sum_user4,
         Sum_user5,
         Avg_user1,
         Avg_user2,
         Avg_user3,
         Avg_user4,
         Avg_user5,
		 inventory_indcost,
         oh_indcost,
      cum_eop_units,
      cum_eop_retail,
      cum_eop_cost,
      cum_eop_indcost,
      received_indcost,
      active_loc_flag ,
      store_count
       )
      values
      ( t_new_10roll_id,
	sysdate,
        1,
        cur_rec.lv10loc_id,
        li_model_lv7loc_id,
        cur_rec.cycle,
        cur_rec.c_col1,
        cur_rec.c_col2,
        cur_rec.c_col3,
        cur_rec.c_col4,
        cur_rec.c_col5,
        cur_rec.c_col6,
        cur_rec.c_col7,
        cur_rec.c_col8,
        cur_rec.c_col9,
        cur_rec.c_col10,
        cur_rec.c_col11,
        cur_rec.c_col12,
        cur_rec.c_col13,
        cur_rec.c_col14,
        cur_rec.c_col15,
        cur_rec.c_col16,
        cur_rec.c_col17,
        cur_rec.c_col18,
        cur_rec.c_col19,
        cur_rec.c_col20,
        cur_rec.c_col21,
        cur_rec.c_col22,
        cur_rec.c_col23,
        cur_rec.c_col24,
        cur_rec.c_col25,
        cur_rec.c_col26,
        cur_rec.c_col27,
        cur_rec.c_col28,
        -- add model_id to concat
        cur_rec.lv10loc_id||'-'||li_model_lv7loc_id,
        cur_rec.c_col35,
        cur_rec.c_col36,
        cur_rec.c_col37,
        cur_rec.c_col38,
        cur_rec.c_col39,
        cur_rec.c_col40,
        cur_rec.c_col41,
        cur_rec.c_col42,
        cur_rec.c_col43,
        cur_rec.c_col44,
        cur_rec.c_col45,
        cur_rec.c_col46,
        cur_rec.c_col47,
        cur_rec.c_col48,
        cur_rec.c_col49,
        cur_rec.c_col50,
        cur_rec.c_col51,
        cur_rec.c_col52,
        cur_rec.c_col53,
        cur_rec.c_col54,
        cur_rec.c_col55,
        cur_rec.c_col56,
        cur_rec.c_col57,
        cur_rec.c_col58,
        cur_rec.c_col59,
        cur_rec.c_col60,
        cur_rec.c_col61,
        cur_rec.c_col62,
        cur_rec.c_col63,
        cur_rec.c_col64,
        cur_rec.c_col65,
	cur_rec.c_col66,
       cur_rec.c_col67,
       cur_rec.c_col68,
       cur_rec.c_col69,
       cur_rec.c_col70,
       cur_rec.c_col71,
       cur_rec.c_col72,
       cur_rec.c_col73,
       cur_rec.c_col74,
       cur_rec.c_col75,
       cur_rec.c_col76,
       cur_rec.c_col77,
       cur_rec.c_col78,
       cur_rec.c_col79,
       cur_rec.c_col80,
       cur_rec.c_col81,
       cur_rec.c_col82,
       cur_rec.c_col83,
       cur_rec.c_col84,
       cur_rec.c_col85,
       cur_rec.c_col86,
       cur_rec.c_col87,
       cur_rec.c_col88,
       cur_rec.c_col89,
       cur_rec.c_col90,
       cur_rec.c_col91,
       cur_rec.c_col92,
       cur_rec.c_col93,
       cur_rec.c_col94,
       cur_rec.c_col95,
       cur_rec.c_col96,
       cur_rec.c_col97,
       cur_rec.c_col98,
       cur_rec.c_col99,
       cur_rec.c_col100,
       cur_rec.c_col101,
       cur_rec.c_col102,
       cur_rec.c_col103,
       cur_rec.c_col104,
       cur_rec.c_col105,
       cur_rec.c_col106,
       cur_rec.c_col107,
       cur_rec.c_col108,
       cur_rec.c_col109,
       cur_rec.c_col110,
       cur_rec.c_col112,
       cur_rec.c_col113,
       cur_rec.c_col114,
       cur_rec.c_col115,
       cur_rec.c_col116,
       cur_rec.c_col117,
       cur_rec.c_col118,
       cur_rec.c_col119,
       cur_rec.c_col120,
       cur_rec.c_col121,
       cur_rec.c_col122,
       cur_rec.c_col123,
       cur_rec.c_col124,
       cur_rec.c_col125,
       cur_rec.c_col126,
       cur_rec.c_col127,
       cur_rec.c_col128,
       cur_rec.c_col129,
       cur_rec.c_col130,
       cur_rec.c_col131,
       cur_rec.c_col132,
       cur_rec.c_col133,
       cur_rec.c_col134,
       cur_rec.c_col135,
       cur_rec.c_col136,
       cur_rec.c_col137,
       cur_rec.c_col138,
       cur_rec.c_col139,
       cur_rec.c_col140,
       cur_rec.c_col141,
       cur_rec.c_col142,
       cur_rec.c_col143,
       cur_rec.c_col144,
       cur_rec.c_col145,
       cur_rec.c_col146,
       cur_rec.c_col147,
       cur_rec.c_col148,
       cur_rec.c_col149,
       cur_rec.c_col150,
       cur_rec.c_col151,
       cur_rec.c_col152,
       cur_rec.c_col153 ,
       cur_rec.c_col154
	) ;

   end loop;

end loop;

begin

  --delete from lv9roll where live_lv7loc_id = li_model_lv7loc_id;
  --Select max(periods_rolled)  into t_periods_rolled from lv9roll;

  for c2 in c_lv9loc loop
    -- Sum roll for each location

    for cur_rec2 in c_lv9roll(c2.lv9loc_id) loop
      -- Insert new Model roll data

       insert into lv9roll
      ( last_update,
        version_id,
        lv9loc_id,
        live_lv7loc_id,
        cycle,
        cubic_meters,
        dsp_sqmeters,
        flr_sqmeters,
        linear_meters,
        used_cubic_meters,
        used_dsp_sqmeters,
        used_linear_meters,
        loss_sales,
        loss_gp,
        proj_sales,
        proj_gp,
        gm_roii,
        days_in_period,
        days_supply,
        dpp_dollar,
        dpp_item,
        cost_of_invent,
        dir_cost_of_sales,
        indir_cost_of_sale,
        posit_sales,
        posit_mvmt,
        posit_norm_mvmt,
        count_num_prodloc,
        count_inc_in_avg,
        total_caps,
        total_units,
        total_items,
        vat,
        supp_total_sales,
        supp_cost_of_sales,
        supp_posit_mvmt,
        supplier_norm_mvmt,
        oh_qty,
        oh_cost,
        oh_retail,
        pog_retail,
        periods_rolled,
        concat_id,
	 posit_indcost_reg,
	 posit_indcost_promo,
	 posit_indcost_clrnc,
	 posit_indcost_retn,
         Sales_retail_5,
         Sales_Cost_5,
         Sales_Items_5,
         Sales_indcost_5,
         Sales_retail_6,
         Sales_Cost_6,
         Sales_Items_6,
         Sales_indcost_6,
         Sales_retail_7,
         Sales_Cost_7,
         Sales_Items_7,
         Sales_indcost_7,
         Sales_retail_8,
         Sales_Cost_8,
         Sales_Items_8,
         Sales_indcost_8,
         Sales_retail_9,
         Sales_Cost_9,
         Sales_Items_9,
         Sales_indcost_9,
         Sales_retail_10,
         Sales_Cost_10,
         Sales_Items_10,
         Sales_indcost_10,
         Inv_retail_1,
         Inv_Cost_1,
         Inv_Items_1,
         Inv_indcost_1,
         Inv_retail_2,
         Inv_Cost_2,
         Inv_Items_2,
         Inv_indcost_2,
         Inv_retail_3,
         Inv_Cost_3,
         Inv_Items_3,
         Inv_indcost_3,
         Inv_retail_4,
         Inv_Cost_4,
         Inv_Items_4,
         Inv_indcost_4,
         Inv_retail_5,
         Inv_Cost_5,
         Inv_Items_5,
         Inv_indcost_5,
         Inv_retail_6,
         Inv_Cost_6,
         Inv_Items_6,
         Inv_indcost_6,
         Inv_retail_7,
         Inv_Cost_7,
         Inv_Items_7,
         Inv_indcost_7,
         Inv_retail_8,
         Inv_Cost_8,
         Inv_Items_8,
         Inv_indcost_8,
         Inv_retail_9,
         Inv_Cost_9,
         Inv_Items_9,
         Inv_indcost_9,
         Inv_retail_10,
         Inv_Cost_10,
         Inv_Items_10,
         Inv_indcost_10,
         Sum_user1,
         Sum_user2,
         Sum_user3,
         Sum_user4,
         Sum_user5,
         Avg_user1,
         Avg_user2,
         Avg_user3,
         Avg_user4,
         Avg_user5,
		 oh_indcost,
      cum_eop_units,
      cum_eop_retail,
      cum_eop_cost,
      cum_eop_indcost,
      received_indcost,
      active_loc_flag ,
      store_count
       )
      values
      ( sysdate,
        1,
        cur_rec2.lv9loc_id,
        li_model_lv7loc_id,
        cur_rec2.cycle,
        cur_rec2.c_col1,
        cur_rec2.c_col2,
        cur_rec2.c_col3,
        cur_rec2.c_col4,
        cur_rec2.c_col5,
        cur_rec2.c_col6,
        cur_rec2.c_col7,
        cur_rec2.c_col8,
        cur_rec2.c_col9,
        cur_rec2.c_col10,
        cur_rec2.c_col11,
        cur_rec2.c_col12,
        cur_rec2.c_col13,
        cur_rec2.c_col14,
        cur_rec2.c_col15,
        cur_rec2.c_col16,
        cur_rec2.c_col17,
        cur_rec2.c_col18,
        cur_rec2.c_col19,
        cur_rec2.c_col20,
        cur_rec2.c_col21,
        cur_rec2.c_col22,
        cur_rec2.c_col23,
        cur_rec2.c_col24,
        cur_rec2.c_col25,
        cur_rec2.c_col26,
        cur_rec2.c_col27,
        cur_rec2.c_col28,
        cur_rec2.c_col29,
        cur_rec2.c_col30,
        cur_rec2.c_col31,
        cur_rec2.c_col32,
        cur_rec2.c_col39,
        cur_rec2.c_col40,
        cur_rec2.c_col41,
        cur_rec2.c_col42,
        cur_rec2.c_col43,
       cur_rec2.lv9loc_id||'-'||li_model_lv7loc_id,
       cur_rec2.c_col45,
       cur_rec2.c_col46,
       cur_rec2.c_col47,
       cur_rec2.c_col48,
       cur_rec2.c_col49,
       cur_rec2.c_col50,
       cur_rec2.c_col51,
       cur_rec2.c_col52,
       cur_rec2.c_col53,
       cur_rec2.c_col54,
       cur_rec2.c_col55,
       cur_rec2.c_col56,
       cur_rec2.c_col57,
       cur_rec2.c_col58,
       cur_rec2.c_col59,
       cur_rec2.c_col60,
       cur_rec2.c_col61,
       cur_rec2.c_col62,
       cur_rec2.c_col63,
       cur_rec2.c_col64,
       cur_rec2.c_col65,
       cur_rec2.c_col66,
       cur_rec2.c_col67,
       cur_rec2.c_col68,
       cur_rec2.c_col69,
       cur_rec2.c_col70,
       cur_rec2.c_col71,
       cur_rec2.c_col72,
       cur_rec2.c_col73,
       cur_rec2.c_col74,
       cur_rec2.c_col75,
       cur_rec2.c_col76,
       cur_rec2.c_col77,
       cur_rec2.c_col78,
       cur_rec2.c_col79,
       cur_rec2.c_col80,
       cur_rec2.c_col81,
       cur_rec2.c_col82,
       cur_rec2.c_col83,
       cur_rec2.c_col84,
       cur_rec2.c_col85,
       cur_rec2.c_col86,
       cur_rec2.c_col87,
       cur_rec2.c_col88,
       cur_rec2.c_col89,
       cur_rec2.c_col90,
       cur_rec2.c_col91,
       cur_rec2.c_col92,
       cur_rec2.c_col93,
       cur_rec2.c_col94,
       cur_rec2.c_col95,
       cur_rec2.c_col96,
       cur_rec2.c_col97,
       cur_rec2.c_col98,
       cur_rec2.c_col99,
       cur_rec2.c_col100,
       cur_rec2.c_col101,
       cur_rec2.c_col102,
       cur_rec2.c_col103,
       cur_rec2.c_col104,
       cur_rec2.c_col105,
       cur_rec2.c_col106,
       cur_rec2.c_col107,
       cur_rec2.c_col108,
       cur_rec2.c_col109,
       cur_rec2.c_col110,
       cur_rec2.c_col111,
       cur_rec2.c_col112,
       cur_rec2.c_col113,
       cur_rec2.c_col114,
       cur_rec2.c_col115,
       cur_rec2.c_col116,
       cur_rec2.c_col117,
       cur_rec2.c_col118,
       cur_rec2.c_col119,
       cur_rec2.c_col120,
       cur_rec2.c_col121,
       cur_rec2.c_col122,
	   cur_rec2.c_col23,
        cur_rec2.c_col24,
        cur_rec2.c_col25,
        cur_rec2.c_col26,
        cur_rec2.c_col27,
        cur_rec2.c_col28,
	cur_rec2.c_col29,
	cur_rec2.c_col30
 	--cur_rec2.c_col44,
        -- add model_id to concat
       ) ;

    end loop ;

  end loop ;

  begin
    for c3 in c_lv8loc loop
    -- Sum roll for each location

    for cur_rec3 in c_lv8roll(c3.lv8loc_id) loop
      -- Insert new Model roll data

       insert into lv8roll
      ( last_update,
        version_id,
        lv8loc_id,
        live_lv7loc_id,
        cycle,
        cubic_meters,
        dsp_sqmeters,
        flr_sqmeters,
        linear_meters,
        used_cubic_meters,
        used_dsp_sqmeters,
        used_linear_meters,
        loss_sales,
        loss_gp,
        proj_sales,
        proj_gp,
        gm_roii,
        days_in_period,
        days_supply,
        dpp_dollar,
        dpp_item,
        cost_of_invent,
        dir_cost_of_sales,
        indir_cost_of_sale,
        posit_sales,
        posit_mvmt,
        posit_norm_mvmt,
        count_num_prodloc,
        count_inc_in_avg,
        total_caps,
        total_units,
        total_items,
        vat,
        supp_total_sales,
        supp_cost_of_sales,
        supp_posit_mvmt,
        supplier_norm_mvmt,
        oh_qty,
        oh_cost,
        oh_retail,
        pog_retail,
        periods_rolled,
        concat_id,
	 posit_indcost_reg,
	 posit_indcost_promo,
	 posit_indcost_clrnc,
	 posit_indcost_retn,
         Sales_retail_5,
         Sales_Cost_5,
         Sales_Items_5,
         Sales_indcost_5,
         Sales_retail_6,
         Sales_Cost_6,
         Sales_Items_6,
         Sales_indcost_6,
         Sales_retail_7,
         Sales_Cost_7,
         Sales_Items_7,
         Sales_indcost_7,
         Sales_retail_8,
         Sales_Cost_8,
         Sales_Items_8,
         Sales_indcost_8,
         Sales_retail_9,
         Sales_Cost_9,
         Sales_Items_9,
         Sales_indcost_9,
         Sales_retail_10,
         Sales_Cost_10,
         Sales_Items_10,
         Sales_indcost_10,
         Inv_retail_1,
         Inv_Cost_1,
         Inv_Items_1,
         Inv_indcost_1,
         Inv_retail_2,
         Inv_Cost_2,
         Inv_Items_2,
         Inv_indcost_2,
         Inv_retail_3,
         Inv_Cost_3,
         Inv_Items_3,
         Inv_indcost_3,
         Inv_retail_4,
         Inv_Cost_4,
         Inv_Items_4,
         Inv_indcost_4,
         Inv_retail_5,
         Inv_Cost_5,
         Inv_Items_5,
         Inv_indcost_5,
         Inv_retail_6,
         Inv_Cost_6,
         Inv_Items_6,
         Inv_indcost_6,
         Inv_retail_7,
         Inv_Cost_7,
         Inv_Items_7,
         Inv_indcost_7,
         Inv_retail_8,
         Inv_Cost_8,
         Inv_Items_8,
         Inv_indcost_8,
         Inv_retail_9,
         Inv_Cost_9,
         Inv_Items_9,
         Inv_indcost_9,
         Inv_retail_10,
         Inv_Cost_10,
         Inv_Items_10,
         Inv_indcost_10,
         Sum_user1,
         Sum_user2,
         Sum_user3,
         Sum_user4,
         Sum_user5,
         Avg_user1,
         Avg_user2,
         Avg_user3,
         Avg_user4,
         Avg_user5,
		 oh_indcost,
      cum_eop_units,
      cum_eop_retail,
      cum_eop_cost,
      cum_eop_indcost,
      received_indcost,
      active_loc_flag ,
      store_count
       )
      values
      ( sysdate,
        1,
        cur_rec3.lv8loc_id,
        li_model_lv7loc_id,
        cur_rec3.cycle,
        cur_rec3.c_col1,
        cur_rec3.c_col2,
        cur_rec3.c_col3,
        cur_rec3.c_col4,
        cur_rec3.c_col5,
        cur_rec3.c_col6,
        cur_rec3.c_col7,
        cur_rec3.c_col8,
        cur_rec3.c_col9,
        cur_rec3.c_col10,
        cur_rec3.c_col11,
        cur_rec3.c_col12,
        cur_rec3.c_col13,
        cur_rec3.c_col14,
        cur_rec3.c_col15,
        cur_rec3.c_col16,
        cur_rec3.c_col17,
        cur_rec3.c_col18,
        cur_rec3.c_col19,
        cur_rec3.c_col20,
        cur_rec3.c_col21,
        cur_rec3.c_col22,
        cur_rec3.c_col23,
        cur_rec3.c_col24,
        cur_rec3.c_col25,
        cur_rec3.c_col26,
        cur_rec3.c_col27,
        cur_rec3.c_col28,
        cur_rec3.c_col29,
        cur_rec3.c_col30,
        cur_rec3.c_col31,
        cur_rec3.c_col32,
        cur_rec3.c_col39,
        cur_rec3.c_col40,
        cur_rec3.c_col41,
        cur_rec3.c_col42,
        cur_rec3.c_col43,
       cur_rec3.lv8loc_id||'-'||li_model_lv7loc_id,
       cur_rec3.c_col45,
       cur_rec3.c_col46,
       cur_rec3.c_col47,
       cur_rec3.c_col48,
       cur_rec3.c_col49,
       cur_rec3.c_col50,
       cur_rec3.c_col51,
       cur_rec3.c_col52,
       cur_rec3.c_col53,
       cur_rec3.c_col54,
       cur_rec3.c_col55,
       cur_rec3.c_col56,
       cur_rec3.c_col57,
       cur_rec3.c_col58,
       cur_rec3.c_col59,
       cur_rec3.c_col60,
       cur_rec3.c_col61,
       cur_rec3.c_col62,
       cur_rec3.c_col63,
       cur_rec3.c_col64,
       cur_rec3.c_col65,
       cur_rec3.c_col66,
       cur_rec3.c_col67,
       cur_rec3.c_col68,
       cur_rec3.c_col69,
       cur_rec3.c_col70,
       cur_rec3.c_col71,
       cur_rec3.c_col72,
       cur_rec3.c_col73,
       cur_rec3.c_col74,
       cur_rec3.c_col75,
       cur_rec3.c_col76,
       cur_rec3.c_col77,
       cur_rec3.c_col78,
       cur_rec3.c_col79,
       cur_rec3.c_col80,
       cur_rec3.c_col81,
       cur_rec3.c_col82,
       cur_rec3.c_col83,
       cur_rec3.c_col84,
       cur_rec3.c_col85,
       cur_rec3.c_col86,
       cur_rec3.c_col87,
       cur_rec3.c_col88,
       cur_rec3.c_col89,
       cur_rec3.c_col90,
       cur_rec3.c_col91,
       cur_rec3.c_col92,
       cur_rec3.c_col93,
       cur_rec3.c_col94,
       cur_rec3.c_col95,
       cur_rec3.c_col96,
       cur_rec3.c_col97,
       cur_rec3.c_col98,
       cur_rec3.c_col99,
       cur_rec3.c_col100,
       cur_rec3.c_col101,
       cur_rec3.c_col102,
       cur_rec3.c_col103,
       cur_rec3.c_col104,
       cur_rec3.c_col105,
       cur_rec3.c_col106,
       cur_rec3.c_col107,
       cur_rec3.c_col108,
       cur_rec3.c_col109,
       cur_rec3.c_col110,
       cur_rec3.c_col111,
       cur_rec3.c_col112,
       cur_rec3.c_col113,
       cur_rec3.c_col114,
       cur_rec3.c_col115,
       cur_rec3.c_col116,
       cur_rec3.c_col117,
       cur_rec3.c_col118,
       cur_rec3.c_col119,
       cur_rec3.c_col120,
       cur_rec3.c_col121,
       cur_rec3.c_col122,
	   cur_rec3.c_col23,
        cur_rec3.c_col24,
        cur_rec3.c_col25,
        cur_rec3.c_col26,
        cur_rec3.c_col27,
        cur_rec3.c_col28,
	cur_rec3.c_col29,
	cur_rec3.c_col30
 	--cur_rec3.c_col44,
        -- add model_id to concat
       ) ;

    end loop ;

  end loop ;

begin

    --delete from lv7roll where lv7loc_id = li_model_lv7loc_id;

 -- select live locs to which this model has been assigned.

   insert into temp_pogmaster (live_lv7loc_id)
    select   live_lv7loc_id
    from     pogmaster
    where    pog_model_id = li_model_lv7loc_id
    and      pogmaster.current_pog = 1 ;

       -- Insert Model roll data into a temp table

       insert into temp_lv7roll
      ( last_update,
        version_id,
        lv7loc_id,
        cycle,
        cubic_meters,
        dsp_sqmeters,
        flr_sqmeters,
        linear_meters,
        used_cubic_meters,
        used_dsp_sqmeters,
        used_linear_meters,
        loss_sales,
        loss_gp,
        proj_sales,
        proj_gp,
        gm_roii,
        days_in_period,
        days_supply,
        dpp_dollar,
        dpp_item,
        cost_of_invent,
        dir_cost_of_sales,
        indir_cost_of_sale,
        posit_sales,
        posit_mvmt,
        posit_norm_mvmt,
        count_num_prodloc,
        count_inc_in_avg,
        total_caps,
        total_units,
        total_items,
        vat,
        supp_total_sales,
        supp_cost_of_sales,
        supp_posit_mvmt,
        supplier_norm_mvmt,
        oh_qty,
        oh_cost,
        oh_retail,
        pog_retail,
        periods_rolled,
        pa_dollar,
        alloc_cubic_meters,
        alloc_dsp_sqmeters,
        alloc_flr_sqmeters,
        alloc_linear_meter,
        posit_mvmt_reg,
        posit_sales_reg,
        posit_cost_reg,
        posit_mvmt_promo,
        posit_sales_promo,
        posit_cost_promo,
        posit_mvmt_clrnc,
        posit_sales_clrnc,
        posit_cost_clrnc,
        posit_mvmt_retn,
        posit_sales_retn,
        posit_cost_retn,
        inventory_items,
        inventory_retail,
        inventory_cost,
        received_items,
        received_retail,
        received_cost,
        total_items_retail,
        total_items_cost,
        min_pres_items,
        min_pres_retail,
        min_pres_cost,
	 posit_indcost_reg,
	 posit_indcost_promo,
	 posit_indcost_clrnc,
	 posit_indcost_retn,
         Sales_retail_5,
         Sales_Cost_5,
         Sales_Items_5,
         Sales_indcost_5,
         Sales_retail_6,
         Sales_Cost_6,
         Sales_Items_6,
         Sales_indcost_6,
         Sales_retail_7,
         Sales_Cost_7,
         Sales_Items_7,
         Sales_indcost_7,
         Sales_retail_8,
         Sales_Cost_8,
         Sales_Items_8,
         Sales_indcost_8,
         Sales_retail_9,
         Sales_Cost_9,
         Sales_Items_9,
         Sales_indcost_9,
         Sales_retail_10,
         Sales_Cost_10,
         Sales_Items_10,
         Sales_indcost_10,
         Inv_retail_1,
         Inv_Cost_1,
         Inv_Items_1,
         Inv_indcost_1,
         Inv_retail_2,
         Inv_Cost_2,
         Inv_Items_2,
         Inv_indcost_2,
         Inv_retail_3,
         Inv_Cost_3,
         Inv_Items_3,
         Inv_indcost_3,
         Inv_retail_4,
         Inv_Cost_4,
         Inv_Items_4,
         Inv_indcost_4,
         Inv_retail_5,
         Inv_Cost_5,
         Inv_Items_5,
         Inv_indcost_5,
         Inv_retail_6,
         Inv_Cost_6,
         Inv_Items_6,
         Inv_indcost_6,
         Inv_retail_7,
         Inv_Cost_7,
         Inv_Items_7,
         Inv_indcost_7,
         Inv_retail_8,
         Inv_Cost_8,
         Inv_Items_8,
         Inv_indcost_8,
         Inv_retail_9,
         Inv_Cost_9,
         Inv_Items_9,
         Inv_indcost_9,
         Inv_retail_10,
         Inv_Cost_10,
         Inv_Items_10,
         Inv_indcost_10,
         Sum_user1,
         Sum_user2,
         Sum_user3,
         Sum_user4,
         Sum_user5,
         Avg_user1,
         Avg_user2,
         Avg_user3,
         Avg_user4,
         Avg_user5,
		 oh_indcost,
      cum_eop_units,
      cum_eop_retail,
      cum_eop_cost,
      cum_eop_indcost,
      received_indcost,
      active_loc_flag ,
      store_count
                )
      select
       lv7roll.last_update,
        lv7roll.version_id,
        li_model_lv7loc_id,
        lv7roll.cycle,
        lv7roll.cubic_meters,
        lv7roll.dsp_sqmeters,
        lv7roll.flr_sqmeters,
        lv7roll.linear_meters,
        lv7roll.used_cubic_meters,
        lv7roll.used_dsp_sqmeters,
        lv7roll.used_linear_meters,
        lv7roll.loss_sales,
        lv7roll.loss_gp,
        lv7roll.proj_sales,
        lv7roll.proj_gp,
        lv7roll.gm_roii,
        lv7roll.days_in_period,
        lv7roll.days_supply,
        lv7roll.dpp_dollar,
        lv7roll.dpp_item,
        lv7roll.cost_of_invent,
        lv7roll.dir_cost_of_sales,
        lv7roll.indir_cost_of_sale,
        lv7roll.posit_sales,
        lv7roll.posit_mvmt,
        lv7roll.posit_norm_mvmt,
        lv7roll.count_num_prodloc,
        lv7roll.count_inc_in_avg,
        lv7roll.total_caps,
        lv7roll.total_units,
        lv7roll.total_items,
        lv7roll.vat,
        lv7roll.supp_total_sales,
        lv7roll.supp_cost_of_sales,
        lv7roll.supp_posit_mvmt,
        lv7roll.supplier_norm_mvmt,
        lv7roll.oh_qty,
        lv7roll.oh_cost,
        lv7roll.oh_retail,
        lv7roll.pog_retail,
        lv7roll.periods_rolled,
        lv7roll.pa_dollar,
        lv7roll.alloc_cubic_meters,
        lv7roll.alloc_dsp_sqmeters,
        lv7roll.alloc_flr_sqmeters,
        lv7roll.alloc_linear_meter,
        lv7roll.posit_mvmt_reg,
        lv7roll.posit_sales_reg,
        lv7roll.posit_cost_reg,
        lv7roll.posit_mvmt_promo,
        lv7roll.posit_sales_promo,
        lv7roll.posit_cost_promo,
        lv7roll.posit_mvmt_clrnc,
        lv7roll.posit_sales_clrnc,
        lv7roll.posit_cost_clrnc,
        lv7roll.posit_mvmt_retn,
        lv7roll.posit_sales_retn,
        lv7roll.posit_cost_retn,
        lv7roll.inventory_items,
        lv7roll.inventory_retail,
        lv7roll.inventory_cost,
        lv7roll.received_items,
        lv7roll.received_retail,
        lv7roll.received_cost,
        lv7roll.total_items_retail,
        lv7roll.total_items_cost,
        lv7roll.min_pres_items,
        lv7roll.min_pres_retail,
        lv7roll.min_pres_cost,
         lv7roll.posit_indcost_reg,
	 lv7roll.posit_indcost_promo,
	 lv7roll.posit_indcost_clrnc,
	 lv7roll.posit_indcost_retn,
         lv7roll.Sales_retail_5,
         lv7roll.Sales_Cost_5,
         lv7roll.Sales_Items_5,
         lv7roll.Sales_indcost_5,
         lv7roll.Sales_retail_6,
         lv7roll.Sales_Cost_6,
         lv7roll.Sales_Items_6,
         lv7roll.Sales_indcost_6,
         lv7roll.Sales_retail_7,
         lv7roll.Sales_Cost_7,
         lv7roll.Sales_Items_7,
         lv7roll.Sales_indcost_7,
         lv7roll.Sales_retail_8,
         lv7roll.Sales_Cost_8,
         lv7roll.Sales_Items_8,
         lv7roll.Sales_indcost_8,
         lv7roll.Sales_retail_9,
         lv7roll.Sales_Cost_9,
         lv7roll.Sales_Items_9,
         lv7roll.Sales_indcost_9,
         lv7roll.Sales_retail_10,
         lv7roll.Sales_Cost_10,
         lv7roll.Sales_Items_10,
         lv7roll.Sales_indcost_10,
         lv7roll.Inv_retail_1,
         lv7roll.Inv_Cost_1,
         lv7roll.Inv_Items_1,
         lv7roll.Inv_indcost_1,
         lv7roll.Inv_retail_2,
         lv7roll.Inv_Cost_2,
         lv7roll.Inv_Items_2,
         lv7roll.Inv_indcost_2,
         lv7roll.Inv_retail_3,
         lv7roll.Inv_Cost_3,
         lv7roll.Inv_Items_3,
         lv7roll.Inv_indcost_3,
         lv7roll.Inv_retail_4,
         lv7roll.Inv_Cost_4,
         lv7roll.Inv_Items_4,
         lv7roll.Inv_indcost_4,
         lv7roll.Inv_retail_5,
         lv7roll.Inv_Cost_5,
         lv7roll.Inv_Items_5,
         lv7roll.Inv_indcost_5,
         lv7roll.Inv_retail_6,
         lv7roll.Inv_Cost_6,
         lv7roll.Inv_Items_6,
         lv7roll.Inv_indcost_6,
         lv7roll.Inv_retail_7,
         lv7roll.Inv_Cost_7,
         lv7roll.Inv_Items_7,
         lv7roll.Inv_indcost_7,
         lv7roll.Inv_retail_8,
         lv7roll.Inv_Cost_8,
         lv7roll.Inv_Items_8,
         lv7roll.Inv_indcost_8,
         lv7roll.Inv_retail_9,
         lv7roll.Inv_Cost_9,
         lv7roll.Inv_Items_9,
         lv7roll.Inv_indcost_9,
         lv7roll.Inv_retail_10,
         lv7roll.Inv_Cost_10,
         lv7roll.Inv_Items_10,
         lv7roll.Inv_indcost_10,
         lv7roll.Sum_user1,
         lv7roll.Sum_user2,
         lv7roll.Sum_user3,
         lv7roll.Sum_user4,
         lv7roll.Sum_user5,
         lv7roll.Avg_user1,
         lv7roll.Avg_user2,
         lv7roll.Avg_user3,
         lv7roll.Avg_user4,
         lv7roll.Avg_user5,
		 lv7roll.oh_indcost,
      lv7roll.cum_eop_units,
      lv7roll.cum_eop_retail,
      lv7roll.cum_eop_cost,
      lv7roll.cum_eop_indcost,
      lv7roll.received_indcost,
      lv7roll.active_loc_flag,
      lv7roll.store_count
	    from lv7roll ,temp_pogmaster
        where lv7roll.lv7loc_id = temp_pogmaster.live_lv7loc_id;

-- insert new model data

        insert into maxdata.lv7roll
         (last_update,
        version_id,
        lv7loc_id,
        cycle,
        cubic_meters,
        dsp_sqmeters,
        flr_sqmeters,
        linear_meters,
        used_cubic_meters,
        used_dsp_sqmeters,
        used_linear_meters,
        loss_sales,
        loss_gp,
        proj_sales,
        proj_gp,
        gm_roii,
        days_in_period,
        days_supply,
        dpp_dollar,
        dpp_item,
        cost_of_invent,
        dir_cost_of_sales,
        indir_cost_of_sale,
        posit_sales,
        posit_mvmt,
        posit_norm_mvmt,
        count_num_prodloc,
        count_inc_in_avg,
        total_caps,
        total_units,
        total_items,
        vat,
        supp_total_sales,
        supp_cost_of_sales,
        supp_posit_mvmt,
        supplier_norm_mvmt,
        oh_qty,
        oh_cost,
        oh_retail,
        pog_retail,
        periods_rolled,
        pa_dollar,
        alloc_cubic_meters,
        alloc_dsp_sqmeters,
        alloc_flr_sqmeters,
        alloc_linear_meter,
        posit_mvmt_reg,
        posit_sales_reg,
        posit_cost_reg,
        posit_mvmt_promo,
        posit_sales_promo,
        posit_cost_promo,
        posit_mvmt_clrnc,
        posit_sales_clrnc,
        posit_cost_clrnc,
        posit_mvmt_retn,
        posit_sales_retn,
        posit_cost_retn,
        inventory_items,
        inventory_retail,
        inventory_cost,
        received_items,
        received_retail,
        received_cost,
        total_items_retail,
        total_items_cost,
        min_pres_items,
        min_pres_retail,
        min_pres_cost,
	 posit_indcost_reg,
	 posit_indcost_promo,
	 posit_indcost_clrnc,
	 posit_indcost_retn,
         Sales_retail_5,
         Sales_Cost_5,
         Sales_Items_5,
         Sales_indcost_5,
         Sales_retail_6,
         Sales_Cost_6,
         Sales_Items_6,
         Sales_indcost_6,
         Sales_retail_7,
         Sales_Cost_7,
         Sales_Items_7,
         Sales_indcost_7,
         Sales_retail_8,
         Sales_Cost_8,
         Sales_Items_8,
         Sales_indcost_8,
         Sales_retail_9,
         Sales_Cost_9,
         Sales_Items_9,
         Sales_indcost_9,
         Sales_retail_10,
         Sales_Cost_10,
         Sales_Items_10,
         Sales_indcost_10,
         Inv_retail_1,
         Inv_Cost_1,
         Inv_Items_1,
         Inv_indcost_1,
         Inv_retail_2,
         Inv_Cost_2,
         Inv_Items_2,
         Inv_indcost_2,
         Inv_retail_3,
         Inv_Cost_3,
         Inv_Items_3,
         Inv_indcost_3,
         Inv_retail_4,
         Inv_Cost_4,
         Inv_Items_4,
         Inv_indcost_4,
         Inv_retail_5,
         Inv_Cost_5,
         Inv_Items_5,
         Inv_indcost_5,
         Inv_retail_6,
         Inv_Cost_6,
         Inv_Items_6,
         Inv_indcost_6,
         Inv_retail_7,
         Inv_Cost_7,
         Inv_Items_7,
         Inv_indcost_7,
         Inv_retail_8,
         Inv_Cost_8,
         Inv_Items_8,
         Inv_indcost_8,
         Inv_retail_9,
         Inv_Cost_9,
         Inv_Items_9,
         Inv_indcost_9,
         Inv_retail_10,
         Inv_Cost_10,
         Inv_Items_10,
         Inv_indcost_10,
         Sum_user1,
         Sum_user2,
         Sum_user3,
         Sum_user4,
         Sum_user5,
         Avg_user1,
         Avg_user2,
         Avg_user3,
         Avg_user4,
         Avg_user5,
		 oh_indcost,
      cum_eop_units,
      cum_eop_retail,
      cum_eop_cost,
      cum_eop_indcost,
      received_indcost,
      active_loc_flag,
      store_count
         )
     select
      sysdate,
      1,
      temp_lv7roll.lv7loc_id,
      max(temp_lv7roll.cycle),
      sum(temp_lv7roll.cubic_meters),
      sum(temp_lv7roll.dsp_sqmeters),
      sum(temp_lv7roll.flr_sqmeters),
      sum(temp_lv7roll.linear_meters),
      sum(temp_lv7roll.used_cubic_meters),
      sum(temp_lv7roll.used_dsp_sqmeters),
      sum(temp_lv7roll.used_linear_meters),
      sum(temp_lv7roll.loss_sales),
      sum(temp_lv7roll.loss_gp),
      sum(temp_lv7roll.proj_sales),
      sum(temp_lv7roll.proj_gp),
      sum(temp_lv7roll.gm_roii),
      sum(temp_lv7roll.days_in_period),
      sum(temp_lv7roll.days_supply) ,
      sum(temp_lv7roll.dpp_dollar),
      sum(temp_lv7roll.dpp_item) ,
      sum(temp_lv7roll.cost_of_invent),
      sum(temp_lv7roll.dir_cost_of_sales),
      sum(temp_lv7roll.indir_cost_of_sale),
      sum(temp_lv7roll.posit_sales) ,
      sum(temp_lv7roll.posit_mvmt),
      sum(temp_lv7roll.posit_norm_mvmt) ,
      sum(temp_lv7roll.count_num_prodloc),
      sum(temp_lv7roll.count_inc_in_avg),
      sum(temp_lv7roll.total_caps),
      sum(temp_lv7roll.total_units) ,
      sum(temp_lv7roll.total_items),
      sum(temp_lv7roll.vat) ,
      sum(temp_lv7roll.supp_total_sales),
      sum(temp_lv7roll.supp_cost_of_sales),
      sum(temp_lv7roll.supp_posit_mvmt),
      sum(temp_lv7roll.supplier_norm_mvmt) ,
      sum(temp_lv7roll.oh_qty),
      sum(temp_lv7roll.oh_cost) ,
      sum(temp_lv7roll.oh_retail),
      sum(temp_lv7roll. pog_retail) ,
      max(temp_lv7roll.periods_rolled) ,
      sum(temp_lv7roll.pa_dollar),
      sum(temp_lv7roll.alloc_cubic_meters),
      sum(temp_lv7roll.alloc_dsp_sqmeters),
      sum(temp_lv7roll.alloc_flr_sqmeters) ,
      sum(temp_lv7roll.alloc_linear_meter) ,
      sum(temp_lv7roll.posit_mvmt_reg)     ,
      sum(temp_lv7roll.posit_sales_reg)    ,
      sum(temp_lv7roll.posit_cost_reg)     ,
      sum(temp_lv7roll.posit_mvmt_promo)   ,
      sum(temp_lv7roll.posit_sales_promo)  ,
      sum(temp_lv7roll.posit_cost_promo)   ,
      sum(temp_lv7roll.posit_mvmt_clrnc)   ,
      sum(temp_lv7roll.posit_sales_clrnc)  ,
      sum(temp_lv7roll.posit_cost_clrnc)   ,
      sum(temp_lv7roll.posit_mvmt_retn)    ,
      sum(temp_lv7roll.posit_sales_retn)   ,
      sum(temp_lv7roll.posit_cost_retn)    ,
      sum(temp_lv7roll.inventory_items)    ,
      sum(temp_lv7roll.inventory_retail)   ,
      sum(temp_lv7roll.inventory_cost)     ,
      sum(temp_lv7roll.received_items)     ,
      sum(temp_lv7roll.received_retail)    ,
      sum(temp_lv7roll.received_cost)      ,
      sum(temp_lv7roll.total_items_retail) ,
      sum(temp_lv7roll.total_items_cost)   ,
      sum(temp_lv7roll.min_pres_items)     ,
      sum(temp_lv7roll.min_pres_retail)    ,
      sum(temp_lv7roll.min_pres_cost),
         sum(temp_lv7roll.posit_indcost_reg),
	 sum(temp_lv7roll.posit_indcost_promo),
	 sum(temp_lv7roll.posit_indcost_clrnc),
	 sum(temp_lv7roll.posit_indcost_retn),
         sum(temp_lv7roll.Sales_retail_5),
         sum(temp_lv7roll.Sales_Cost_5),
         sum(temp_lv7roll.Sales_Items_5),
         sum(temp_lv7roll.Sales_indcost_5),
         sum(temp_lv7roll.Sales_retail_6),
         sum(temp_lv7roll.Sales_Cost_6),
         sum(temp_lv7roll.Sales_Items_6),
         sum(temp_lv7roll.Sales_indcost_6),
         sum(temp_lv7roll.Sales_retail_7),
         sum(temp_lv7roll.Sales_Cost_7),
         sum(temp_lv7roll.Sales_Items_7),
         sum(temp_lv7roll.Sales_indcost_7),
         sum(temp_lv7roll.Sales_retail_8),
         sum(temp_lv7roll.Sales_Cost_8),
         sum(temp_lv7roll.Sales_Items_8),
         sum(temp_lv7roll.Sales_indcost_8),
         sum(temp_lv7roll.Sales_retail_9),
         sum(temp_lv7roll.Sales_Cost_9),
         sum(temp_lv7roll.Sales_Items_9),
         sum(temp_lv7roll.Sales_indcost_9),
         sum(temp_lv7roll.Sales_retail_10),
         sum(temp_lv7roll.Sales_Cost_10),
         sum(temp_lv7roll.Sales_Items_10),
         sum(temp_lv7roll.Sales_indcost_10),
         sum(temp_lv7roll.Inv_retail_1),
         sum(temp_lv7roll.Inv_Cost_1),
         sum(temp_lv7roll.Inv_Items_1),
         sum(temp_lv7roll.Inv_indcost_1),
         sum(temp_lv7roll.Inv_retail_2),
         sum(temp_lv7roll.Inv_Cost_2),
         sum(temp_lv7roll.Inv_Items_2),
         sum(temp_lv7roll.Inv_indcost_2),
         sum(temp_lv7roll.Inv_retail_3),
         sum(temp_lv7roll.Inv_Cost_3),
         sum(temp_lv7roll.Inv_Items_3),
         sum(temp_lv7roll.Inv_indcost_3),
         sum(temp_lv7roll.Inv_retail_4),
         sum(temp_lv7roll.Inv_Cost_4),
         sum(temp_lv7roll.Inv_Items_4),
         sum(temp_lv7roll.Inv_indcost_4),
         sum(temp_lv7roll.Inv_retail_5),
         sum(temp_lv7roll.Inv_Cost_5),
         sum(temp_lv7roll.Inv_Items_5),
         sum(temp_lv7roll.Inv_indcost_5),
         sum(temp_lv7roll.Inv_retail_6),
         sum(temp_lv7roll.Inv_Cost_6),
         sum(temp_lv7roll.Inv_Items_6),
         sum(temp_lv7roll.Inv_indcost_6),
         sum(temp_lv7roll.Inv_retail_7),
         sum(temp_lv7roll.Inv_Cost_7),
         sum(temp_lv7roll.Inv_Items_7),
         sum(temp_lv7roll.Inv_indcost_7),
         sum(temp_lv7roll.Inv_retail_8),
         sum(temp_lv7roll.Inv_Cost_8),
         sum(temp_lv7roll.Inv_Items_8),
         sum(temp_lv7roll.Inv_indcost_8),
         sum(temp_lv7roll.Inv_retail_9),
         sum(temp_lv7roll.Inv_Cost_9),
         sum(temp_lv7roll.Inv_Items_9),
         sum(temp_lv7roll.Inv_indcost_9),
         sum(temp_lv7roll.Inv_retail_10),
         sum(temp_lv7roll.Inv_Cost_10),
         sum(temp_lv7roll.Inv_Items_10),
         sum(temp_lv7roll.Inv_indcost_10),
         sum(temp_lv7roll.Sum_user1),
         sum(temp_lv7roll.Sum_user2),
         sum(temp_lv7roll.Sum_user3),
         sum(temp_lv7roll.Sum_user4),
         sum(temp_lv7roll.Sum_user5),
         avg(temp_lv7roll.Avg_user1),
         avg(temp_lv7roll.Avg_user2),
         avg(temp_lv7roll.Avg_user3),
         avg(temp_lv7roll.Avg_user4),
         avg(temp_lv7roll.Avg_user5),
	 sum(temp_lv7roll.oh_indcost),
         sum(temp_lv7roll.cum_eop_units),
         sum(temp_lv7roll.cum_eop_retail),
         sum(temp_lv7roll.cum_eop_cost),
         sum(temp_lv7roll.cum_eop_indcost),
         sum(temp_lv7roll.received_indcost),
         sum(temp_lv7roll.active_loc_flag),
	 sum(temp_lv7roll.store_count)
        from temp_lv7roll
       where lv7loc_id = li_model_lv7loc_id
       group by temp_lv7roll.lv7loc_id;

--	Commented out as fix for bug #9056
--	, cycle;

delete from temp_pogmaster;

delete from temp_lv7roll;

     end;

   end;

  end ;

 else
 -- if roll records exist, then exit the procedure.
  return;

  end if;

 end;

/

  GRANT EXECUTE ON "MAXDATA"."P_POG_ANALYZER" TO "MAXAPP";
  GRANT EXECUTE ON "MAXDATA"."P_POG_ANALYZER" TO "MADMAX";
  GRANT EXECUTE ON "MAXDATA"."P_POG_ANALYZER" TO "MAXUSER";
