--------------------------------------------------------
--  DDL for Procedure UPDATE_LV10MERCH
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "MAXDATA"."UPDATE_LV10MERCH" 
AS
Begin

Update maxdata.lv10merch
Set
(

HEIGHT,
WIDTH,
DEPTH,
WEIGHT,
ITEMS_PER_UNIT,
INTERVAL_LEFT1,
INTERVAL_LEFT2,
INTERVAL_LEFT3,
INTERVAL_TOP1,
INTERVAL_TOP2,
INTERVAL_TOP3,
IMAGE_BACK,
IMAGE_BOTTOM,
IMAGE_FRONT,
IMAGE_LEFT,
IMAGE_RIGHT,
IMAGE_TOP,
LINE_BACK,
LINE_BOTTOM,
LINE_TOP,
LINE_FRONT,
LINE_LEFT,
LINE_RIGHT,
INTERVAL_1USED,
INTERVAL_2USED,
INTERVAL_3USED,
NUM_USER1,
NUM_USER2,
NUM_USER3,
NUM_USER4,
NUM_USER5,
NUM_USER6,
DATE_USER7,
DATE_USER8,
CHAR_USER9,
CHAR_USER10,
CHAR_USER11,
CHAR_USER12,
CHAR_USER13,
BIGCHAR_USER14,
BIGCHAR_USER15


)=
((Select
 HEIGHT,
WIDTH,
DEPTH,
WEIGHT,
ITEMS_PER_UNIT,
INTERVAL_LEFT1,
INTERVAL_LEFT2,
INTERVAL_LEFT3,
INTERVAL_TOP1,
INTERVAL_TOP2,
INTERVAL_TOP3,
IMAGE_BACK,
IMAGE_BOTTOM,
IMAGE_FRONT,
IMAGE_LEFT,
IMAGE_RIGHT,
IMAGE_TOP,
LINE_BACK,
LINE_BOTTOM,
LINE_TOP,
LINE_FRONT,
LINE_LEFT,
LINE_RIGHT,
INTERVAL_1USED,
INTERVAL_2USED,
INTERVAL_3USED,
NUM_USER1,
NUM_USER2,
NUM_USER3,
NUM_USER4,
-NUM_USER5,
NUM_USER6,
DATE_USER7,
DATE_USER8,
CHAR_USER9,
CHAR_USER10,
CHAR_USER11,
CHAR_USER12,
CHAR_USER13,
BIGCHAR_USER14,
BIGCHAR_USER15
From maxdata.dm_lv10merch where
dm_lv10merch.lv10merch_id
= lv10merch.lv10merch_id
)) where  exists ( select * from dm_lv10merch where dm_lv10merch.lv10merch_id = lv10merch.lv10merch_id);

End;

/
